// Key terms for AP Chemistry: a one- or two-sentence definition and the lesson that explains it.
// The test suite checks that every lesson exists and really uses the term (or the `find` text).

import type { GlossaryEntry } from '../types'

export const CHEM_GLOSSARY: GlossaryEntry[] = [
  // ---- Toolkit ----
  { term: 'Scientific notation', def: 'A way to write very large or very small numbers as a number from 1 up to 10, times a power of ten. Example: 6.022 × 10^{23}.', lesson: 'chem-0.1' },
  { term: 'Significant figures', def: 'The digits in a measurement that carry real information about its precision. Your answer can only be as precise as your least precise measurement.', lesson: 'chem-0.1' },
  { term: 'Dimensional analysis', def: 'Solving a problem by multiplying by conversion factors so that unwanted units cancel and the unit you want is left.', lesson: 'chem-0.2' },
  { term: 'Conversion factor', def: 'A fraction equal to 1 that relates two units, such as 1000 mL over 1 L. Multiplying by it changes the unit, not the amount.', lesson: 'chem-0.2' },
  { term: 'Atomic number', def: 'The number of protons in the nucleus of an atom. It identifies the element.', lesson: 'chem-0.3' },
  { term: 'Mass number', def: 'The number of protons plus neutrons in one atom.', lesson: 'chem-0.3' },
  { term: 'Isotope', def: 'Atoms of the same element (same number of protons) with different numbers of neutrons, and so different masses.', lesson: 'chem-0.3' },
  { term: 'Ion', def: 'An atom or group of atoms with an electric charge because it has gained or lost electrons.', lesson: 'chem-0.3' },
  { term: 'Cation', def: 'A positively charged ion: it has lost electrons.', lesson: 'chem-0.3' },
  { term: 'Anion', def: 'A negatively charged ion: it has gained electrons.', lesson: 'chem-0.3' },
  { term: 'Polyatomic ion', def: 'A charged group of atoms bonded together that acts as one unit, such as sulfate, {{SO4^2-}}.', lesson: 'chem-0.4' },
  { term: 'Coefficient', def: 'The number in front of a formula in a balanced equation. It tells how many of that particle (or how many moles) react or form.', lesson: 'chem-0.5' },
  { term: 'Logarithm', def: 'The power to which 10 must be raised to give a number. Example: log(1000) = 3 because 10^{3} = 1000.', lesson: 'chem-0.6', find: 'log' },

  // ---- Unit 1 ----
  { term: 'Mole', def: 'A counting unit for particles: one mole is 6.022 × 10^{23} of anything.', lesson: 'chem-1.1' },
  { term: "Avogadro's number", def: '6.022 × 10^{23}: the number of particles in one mole.', lesson: 'chem-1.1', find: 'Avogadro' },
  { term: 'Molar mass', def: 'The mass of one mole of a substance, in grams per mole. For an element it is the atomic mass from the periodic table.', lesson: 'chem-1.1' },
  { term: 'Electron configuration', def: "The arrangement of an atom's electrons in shells and subshells, such as 1s^{2} 2s^{2} 2p^{6}.", lesson: 'chem-1.5' },
  { term: "Coulomb's law", def: 'The force between two charges is larger when the charges are bigger and when they are closer together.', lesson: 'chem-1.5', find: 'Coulomb' },
  { term: 'Mass spectrum', def: 'A graph that shows the relative abundance of each isotope of an element at its mass.', lesson: 'chem-1.2', find: 'mass spectr' },
  { term: 'Average atomic mass', def: "The weighted average of the masses of an element's isotopes, using how common each one is.", lesson: 'chem-1.2', find: 'average' },
  { term: 'Empirical formula', def: 'The simplest whole-number ratio of the atoms in a compound.', lesson: 'chem-1.3' },
  { term: 'Percent composition', def: 'The percent by mass of each element in a compound.', lesson: 'chem-1.3', find: 'percent' },
  { term: 'Atomic radius', def: 'The size of an atom. It increases down a group and decreases across a period.', lesson: 'chem-1.7' },
  { term: 'Ionization energy', def: 'The energy needed to remove an electron from a gaseous atom or ion.', lesson: 'chem-1.7' },
  { term: 'Electronegativity', def: 'How strongly an atom in a bond pulls shared electrons toward itself. Fluorine is the highest.', lesson: 'chem-1.7' },
  { term: 'Valence electrons', def: 'The electrons in the outermost shell of an atom. They are the ones that take part in bonding.', lesson: 'chem-1.8', find: 'valence' },
  { term: 'Photoelectron spectroscopy (PES)', def: 'A technique that measures the energy needed to remove electrons from each subshell of an atom. The height of each peak shows how many electrons are in that subshell.', lesson: 'chem-1.6', find: 'PES' },

  // ---- Unit 2 ----
  { term: 'Ionic bond', def: 'The attraction between positive and negative ions, usually formed when a metal transfers electrons to a nonmetal.', lesson: 'chem-2.1', find: 'ionic' },
  { term: 'Covalent bond', def: 'A bond in which two atoms share electrons.', lesson: 'chem-2.1', find: 'covalent' },
  { term: 'Polar covalent bond', def: 'A covalent bond in which the electrons are shared unequally because the two atoms differ in electronegativity.', lesson: 'chem-2.1', find: 'polar covalent' },
  { term: 'Metallic bond', def: 'The attraction between metal cations and a "sea" of valence electrons that are free to move.', lesson: 'chem-2.4', find: 'sea' },
  { term: 'Bond length', def: 'The distance between the nuclei of two bonded atoms, where the potential energy is lowest.', lesson: 'chem-2.2' },
  { term: 'Bond energy', def: 'The energy needed to break a bond. Shorter bonds and multiple bonds are stronger.', lesson: 'chem-2.2' },
  { term: 'Lattice energy', def: 'A measure of how strongly the ions in an ionic solid attract each other. It is larger for higher charges and smaller ions.', lesson: 'chem-2.3', find: 'lattice' },
  { term: 'Alloy', def: 'A mixture of a metal with one or more other elements.', lesson: 'chem-2.4' },
  { term: 'Lewis diagram', def: "A drawing that shows a molecule's valence electrons as bonds (lines) and lone pairs (dots).", lesson: 'chem-2.5', find: 'Lewis' },
  { term: 'Octet rule', def: 'Atoms tend to bond until they have eight valence electrons around them (hydrogen needs only two).', lesson: 'chem-2.5', find: 'octet' },
  { term: 'Lone pair', def: 'A pair of valence electrons on one atom that is not shared in a bond.', lesson: 'chem-2.5' },
  { term: 'Resonance', def: 'When two or more valid Lewis diagrams can be drawn for a molecule. The real structure is an average of them.', lesson: 'chem-2.6' },
  { term: 'Formal charge', def: 'Valence electrons minus (lone-pair electrons plus half the bonding electrons). It is used to choose the best Lewis diagram.', lesson: 'chem-2.6' },
  { term: 'VSEPR', def: 'A model that predicts the shape of a molecule: electron groups around a central atom spread out as far from each other as they can.', lesson: 'chem-2.7a' },
  { term: 'Hybridization', def: 'The mixing of atomic orbitals into new, equal orbitals (sp, sp^{2}, sp^{3}) that match the geometry of a molecule.', lesson: 'chem-2.7b', find: 'hybridiz' },
  { term: 'Sigma bond', def: 'A bond formed by end-to-end overlap of orbitals. Every single bond is a sigma bond.', lesson: 'chem-2.7b', find: 'sigma' },
  { term: 'Pi bond', def: 'A bond formed by side-by-side overlap of p orbitals. A double bond has one pi bond and a triple bond has two.', lesson: 'chem-2.7b', find: 'pi' },

  // ---- Unit 3 ----
  { term: 'Intermolecular forces', def: 'Attractions between separate molecules. They are much weaker than the bonds inside a molecule.', lesson: 'chem-3.1a', find: 'intermolecular' },
  { term: 'London dispersion forces', def: 'Temporary attractions caused by shifting electron clouds. Every molecule has them, and they are stronger for larger molecules with more electrons.', lesson: 'chem-3.1a', find: 'dispersion' },
  { term: 'Dipole–dipole forces', def: 'Attractions between the positive end of one polar molecule and the negative end of another.', lesson: 'chem-3.1a', find: 'dipole' },
  { term: 'Hydrogen bonding', def: 'A strong attraction between an H atom bonded to N, O or F and a lone pair on an N, O or F atom of a nearby molecule.', lesson: 'chem-3.1a', find: 'hydrogen bond' },
  { term: 'Vapor pressure', def: 'The pressure of a vapor in equilibrium with its liquid. Weaker intermolecular forces give a higher vapor pressure.', lesson: 'chem-3.1b' },
  { term: 'Molarity', def: 'Concentration in moles of solute per liter of solution (mol/L, written M).', lesson: 'chem-3.7' },
  { term: 'Solute', def: 'The substance that is dissolved in a solution.', lesson: 'chem-3.7' },
  { term: 'Solvent', def: 'The substance that does the dissolving in a solution, usually the one present in the larger amount.', lesson: 'chem-3.10' },
  { term: 'Ideal gas law', def: 'PV = nRT: relates the pressure, volume, amount and temperature of a gas.', lesson: 'chem-3.4', find: 'PV = nRT' },
  { term: 'Partial pressure', def: 'The pressure that one gas in a mixture would have if it were alone. The partial pressures add up to the total pressure.', lesson: 'chem-3.4' },
  { term: 'Kinetic molecular theory', def: 'A model of gases as tiny particles in constant random motion. Temperature measures their average kinetic energy.', lesson: 'chem-3.5', find: 'kinetic' },
  { term: 'Chromatography', def: 'A way to separate a mixture by how strongly each part is attracted to a moving phase compared with a stationary phase.', lesson: 'chem-3.9' },
  { term: 'Distillation', def: 'Separating liquids by their different boiling points.', lesson: 'chem-3.9' },
  { term: 'Photon', def: 'A particle of light. Its energy is E = hν.', lesson: 'chem-3.12' },
  { term: 'Wavelength', def: 'The distance between one wave peak and the next. A shorter wavelength means a higher frequency and more energy.', lesson: 'chem-3.12' },
  { term: 'Frequency', def: 'The number of waves that pass a point each second.', lesson: 'chem-3.12' },
  { term: 'Absorbance', def: 'A measure of how much light a sample absorbs.', lesson: 'chem-3.13' },
  { term: 'Beer–Lambert law', def: 'A = εbc: absorbance is proportional to concentration (and to the path length).', lesson: 'chem-3.13', find: 'εbc' },

  // ---- Unit 4 ----
  { term: 'Stoichiometry', def: 'Using the mole ratios in a balanced equation to calculate the amounts of reactants and products.', lesson: 'chem-4.5a' },
  { term: 'Mole ratio', def: 'The ratio of the coefficients of two substances in a balanced equation.', lesson: 'chem-4.5a' },
  { term: 'Limiting reactant', def: 'The reactant that runs out first, so it limits how much product can form.', lesson: 'chem-4.5b', find: 'limiting' },
  { term: 'Precipitate', def: 'An insoluble solid that forms when two solutions are mixed.', lesson: 'chem-4.7a' },
  { term: 'Net ionic equation', def: 'An equation that shows only the particles that actually change in a reaction.', lesson: 'chem-4.2', find: 'net ionic' },
  { term: 'Spectator ion', def: 'An ion that is present in a reaction mixture but does not change. It is left out of the net ionic equation.', lesson: 'chem-4.2', find: 'spectator' },
  { term: 'Titration', def: 'Adding a solution of known concentration to another solution until the reaction is just complete, to find an unknown concentration.', lesson: 'chem-4.6' },
  { term: 'Equivalence point', def: 'The point in a titration when exactly enough titrant has been added to react with all of the substance being analyzed.', lesson: 'chem-4.6' },
  { term: 'Brønsted–Lowry acid', def: 'A substance that donates a proton (H^{+}).', lesson: 'chem-4.8', find: 'donat' },
  { term: 'Brønsted–Lowry base', def: 'A substance that accepts a proton (H^{+}).', lesson: 'chem-4.8', find: 'accept' },
  { term: 'Conjugate acid–base pair', def: 'Two species that differ by one proton (H^{+}), such as {{NH4^+}} and {{NH3}}.', lesson: 'chem-4.8', find: 'conjugate' },
  { term: 'Oxidation number', def: 'A bookkeeping charge assigned to each atom, used to track electrons in redox reactions.', lesson: 'chem-4.7b' },
  { term: 'Oxidation', def: 'Loss of electrons. The oxidation number goes up.', lesson: 'chem-4.7b' },
  { term: 'Reduction', def: 'Gain of electrons. The oxidation number goes down.', lesson: 'chem-4.7b' },
  { term: 'Half-reaction', def: 'An equation showing only the oxidation or only the reduction part of a redox reaction, with its electrons.', lesson: 'chem-4.9' },

  // ---- Unit 5 ----
  { term: 'Reaction rate', def: 'How fast the concentration of a reactant or product changes with time.', lesson: 'chem-5.1', find: 'rate' },
  { term: 'Rate law', def: 'An equation that relates the rate of a reaction to the concentrations of the reactants: rate = k[A]^{m}[B]^{n}.', lesson: 'chem-5.2' },
  { term: 'Reaction order', def: 'The exponent on a concentration in the rate law. It must be found from experiment.', lesson: 'chem-5.2', find: 'order' },
  { term: 'Rate constant', def: 'The k in a rate law. It depends on temperature (and on any catalyst), not on concentration.', lesson: 'chem-5.2' },
  { term: 'Half-life', def: 'The time needed for half of a reactant to be used up. For a first-order reaction it is constant.', lesson: 'chem-5.3' },
  { term: 'Collision model', def: 'Particles react only when they collide with enough energy and in the right orientation.', lesson: 'chem-5.5', find: 'collision' },
  { term: 'Activation energy', def: 'The minimum energy a collision needs for a reaction to happen: the height of the energy hill.', lesson: 'chem-5.5' },
  { term: 'Elementary reaction', def: 'A reaction that happens in a single step, exactly as written.', lesson: 'chem-5.4', find: 'elementary' },
  { term: 'Reaction mechanism', def: 'The series of elementary steps by which a reaction really happens.', lesson: 'chem-5.7', find: 'mechanism' },
  { term: 'Intermediate', def: 'A species that is made in one step of a mechanism and used up in a later step, so it does not appear in the overall equation.', lesson: 'chem-5.7' },
  { term: 'Rate-determining step', def: 'The slowest step of a mechanism. It sets the rate of the whole reaction.', lesson: 'chem-5.8', find: 'slow' },
  { term: 'Catalyst', def: 'A substance that speeds up a reaction by giving it a path with lower activation energy. It is not used up.', lesson: 'chem-5.11' },

  // ---- Unit 6 ----
  { term: 'Exothermic', def: 'A process that releases energy to the surroundings (ΔH is negative).', lesson: 'chem-6.1' },
  { term: 'Endothermic', def: 'A process that absorbs energy from the surroundings (ΔH is positive).', lesson: 'chem-6.1' },
  { term: 'Specific heat capacity', def: 'The energy needed to raise the temperature of 1 gram of a substance by 1 °C.', lesson: 'chem-6.4', find: 'specific heat' },
  { term: 'Calorimetry', def: 'Measuring heat flow from a temperature change, using q = mcΔT.', lesson: 'chem-6.4', find: 'calorimet' },
  { term: 'Enthalpy of reaction (ΔH)', def: 'The heat absorbed or released by a reaction at constant pressure, for the amounts in the balanced equation.', lesson: 'chem-6.6', find: 'ΔH' },
  { term: 'Bond enthalpy', def: 'The energy needed to break one mole of a particular bond in the gas phase.', lesson: 'chem-6.7', find: 'bond enthalp' },
  { term: 'Enthalpy of formation', def: 'The enthalpy change when one mole of a compound forms from its elements in their standard states.', lesson: 'chem-6.8', find: 'formation' },
  { term: "Hess's law", def: 'The total enthalpy change is the same whichever path a reaction takes, so the enthalpy changes of steps can be added.', lesson: 'chem-6.9', find: 'Hess' },

  // ---- Unit 7 ----
  { term: 'Dynamic equilibrium', def: 'The state in which the forward and reverse reactions happen at the same rate, so the concentrations stop changing.', lesson: 'chem-7.1', find: 'equilibrium' },
  { term: 'Equilibrium constant (K)', def: 'The ratio of product to reactant concentrations (each raised to its coefficient) at equilibrium. It changes only with temperature.', lesson: 'chem-7.3', find: 'K' },
  { term: 'Reaction quotient (Q)', def: 'The same expression as K, but using the concentrations at any moment. Comparing Q with K tells which way the reaction will go.', lesson: 'chem-7.3', find: 'Q' },
  { term: 'ICE table', def: 'A table of Initial, Change and Equilibrium amounts used to solve equilibrium problems.', lesson: 'chem-7.7', find: 'ICE' },
  { term: "Le Châtelier's principle", def: 'When a system at equilibrium is disturbed, it shifts in the direction that partly undoes the disturbance.', lesson: 'chem-7.9', find: 'Le Châtelier' },
  { term: 'Solubility product (K_{sp})', def: 'The equilibrium constant for a slightly soluble ionic solid dissolving in water.', lesson: 'chem-7.11', find: 'K_{sp}' },
  { term: 'Molar solubility', def: 'The number of moles of a solid that dissolve in one liter of solution.', lesson: 'chem-7.11' },
  { term: 'Common-ion effect', def: 'A salt is less soluble in a solution that already contains one of its ions.', lesson: 'chem-7.12', find: 'common ion' },

  // ---- Unit 8 ----
  { term: 'pH', def: 'A measure of acidity: pH = −log[H_{3}O^{+}]. A lower pH means a more acidic solution.', lesson: 'chem-8.1' },
  { term: 'pOH', def: 'pOH = −log[OH^{−}]. At 25 °C, pH + pOH = 14.', lesson: 'chem-8.1' },
  { term: 'K_{w}', def: 'The equilibrium constant for water ionizing: K_{w} = [H_{3}O^{+}][OH^{−}] = 1.0 × 10^{−14} at 25 °C.', lesson: 'chem-8.1', find: 'K_{w}' },
  { term: 'Strong acid', def: 'An acid that ionizes completely in water, such as HCl.', lesson: 'chem-8.2' },
  { term: 'Weak acid', def: 'An acid that ionizes only partly in water, so most of its molecules stay intact.', lesson: 'chem-8.3a' },
  { term: 'K_{a}', def: 'The equilibrium constant for a weak acid ionizing in water. A larger K_{a} means a stronger acid.', lesson: 'chem-8.3a', find: 'K_{a}' },
  { term: 'K_{b}', def: 'The equilibrium constant for a weak base reacting with water. For a conjugate pair, K_{a} × K_{b} = K_{w}.', lesson: 'chem-8.3b', find: 'K_{b}' },
  { term: 'Buffer', def: 'A solution of a weak acid and its conjugate base (or a weak base and its conjugate acid) that resists changes in pH.', lesson: 'chem-8.8' },
  { term: 'Henderson–Hasselbalch equation', def: 'pH = pK_{a} + log([A^{−}]/[HA]): gives the pH of a buffer.', lesson: 'chem-8.9', find: 'pK_{a}' },
  { term: 'pK_{a}', def: 'pK_{a} = −log K_{a}. When pH equals pK_{a}, the acid and its conjugate base are present in equal amounts.', lesson: 'chem-8.7', find: 'pK_{a}' },
  { term: 'Indicator', def: 'A weak acid whose acid and base forms have different colors, so it changes color near its pK_{a}.', lesson: 'chem-8.7' },
  { term: 'Titration curve', def: 'A graph of pH against the volume of titrant added.', lesson: 'chem-8.5', find: 'curve' },
  { term: 'Buffer capacity', def: 'How much acid or base a buffer can absorb before its pH changes a lot. More concentrated buffers have more capacity.', lesson: 'chem-8.10', find: 'capacity' },

  // ---- Unit 9 ----
  { term: 'Entropy (S)', def: 'A measure of how spread out matter and energy are. Gases have much more entropy than liquids or solids.', lesson: 'chem-9.1', find: 'entropy' },
  { term: 'Gibbs free energy (ΔG)', def: 'ΔG = ΔH − TΔS. A negative ΔG means a process is thermodynamically favored.', lesson: 'chem-9.3', find: 'ΔG' },
  { term: 'Thermodynamically favored', def: 'A process with a negative ΔG. It can happen without a continuous input of energy, though it may still be slow.', lesson: 'chem-9.3', find: 'favored' },
  { term: 'Kinetic control', def: 'When a thermodynamically favored reaction happens too slowly to notice because its activation energy is high.', lesson: 'chem-9.4', find: 'kinetic' },
  { term: 'Galvanic cell', def: 'A cell in which a thermodynamically favored redox reaction produces an electric current.', lesson: 'chem-9.8', find: 'galvanic' },
  { term: 'Electrolytic cell', def: 'A cell in which an outside power source forces a redox reaction that is not thermodynamically favored to happen.', lesson: 'chem-9.8', find: 'electrolytic' },
  { term: 'Anode', def: 'The electrode where oxidation happens.', lesson: 'chem-9.8' },
  { term: 'Cathode', def: 'The electrode where reduction happens.', lesson: 'chem-9.8' },
  { term: 'Salt bridge', def: 'A path that lets ions move between the two halves of a cell so that charge does not build up.', lesson: 'chem-9.8' },
  { term: 'Standard cell potential (E°)', def: 'The voltage of a cell under standard conditions. A positive E° means the cell reaction is thermodynamically favored.', lesson: 'chem-9.9', find: 'E°' },
  { term: 'Electrolysis', def: 'Using an electric current to drive a chemical reaction that would not happen by itself.', lesson: 'chem-9.11' },
  { term: "Faraday's constant", def: 'The charge of one mole of electrons: 96,485 C/mol.', lesson: 'chem-9.11', find: '96' },
]
