import type { Unit } from '../types'
import { molarMass } from '../../lib/chem'

// Unit 0: prerequisite skills that the AP course assumes (not CED topics themselves).

export const unit0: Unit = {
  id: 'chem-u0',
  number: 0,
  title: 'Chemistry Toolkit',
  blurb:
    'The skills AP Chemistry assumes you already have: numbers and sig figs, unit conversions, atoms and ions, naming, balancing and logs. Ten minutes here saves hours later.',
  badge: { name: 'Toolkit Ready', emoji: '🧰' },
  lessons: [
    {
      id: 'chem-0.1',
      ced: [],
      title: 'Scientific Notation & Significant Figures',
      level: 'foundation',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'A drop of water holds about 1,700,000,000,000,000,000,000 molecules. Nobody wants to write that twice! Chemists use **scientific notation** for numbers like that, and **significant figures** to show how precisely something was measured.',
        },
        {
          kind: 'concept',
          title: 'Scientific notation',
          body: 'Write a number as **(a number from 1 to 10) × 10^{power}**.\n\n- 1,700,000 = 1.7 × 10^{6} (decimal moved 6 places left → positive power)\n- 0.00052 = 5.2 × 10^{-4} (decimal moved 4 places right → negative power)\n\nBig numbers get positive powers. Tiny numbers get negative powers.',
        },
        {
          kind: 'concept',
          title: 'Which digits are significant?',
          body: 'Significant figures (sig figs) are the digits you actually measured.\n\n- All **nonzero digits** count: 4.56 has 3.\n- **Zeros between** nonzero digits count: 1.05 has 3.\n- **Leading zeros** never count: 0.0045 has 2.\n- **Trailing zeros** count only if there is a decimal point: 2.50 has 3, 2.500 has 4.\n- Trailing zeros in a whole number with no decimal point (like 300) are ambiguous. Scientific notation fixes this: 3.00 × 10^{2} clearly has 3.\n- **Exact numbers** (counted objects, defined conversions like 1 m = 100 cm) have unlimited sig figs.',
        },
        {
          kind: 'hack',
          title: 'The Atlantic–Pacific trick',
          body: '**Decimal point Present** → start counting from the **Pacific** (left) side at the first nonzero digit, and count everything after it.\n**Decimal point Absent** → start from the **Atlantic** (right) side at the first nonzero digit.\n\nExample: 0.00340 has a decimal (Pacific): start at 3 → **3, 4, 0** = 3 sig figs.',
        },
        {
          kind: 'concept',
          title: 'Sig figs in calculations',
          body: '- **× and ÷:** the answer gets the **fewest sig figs** of any measurement. Example: 3.5 cm × 2.25 cm = 7.875 → **7.9 cm²** (2 sig figs).\n- **+ and −:** the answer gets the **fewest decimal places**. Example: 12.11 g + 0.3 g = 12.41 → **12.4 g** (1 decimal place).\n\nKeep extra digits while you calculate. Round only the final answer.',
        },
        {
          kind: 'try',
          question: {
            id: 'c0.1-t1',
            type: 'mcq',
            prompt: 'How many significant figures are in **0.004050**?',
            choices: ['3', '4', '6', '7'],
            answer: 1,
            hint: 'Leading zeros never count. Is there a decimal point? Then trailing zeros count.',
            explain: 'Leading zeros (0.00) are just placeholders. Start at the 4: **4, 0, 5, 0** = 4 sig figs. The trailing zero counts because there is a decimal point.',
          },
        },
        {
          kind: 'trap',
          body: 'Your calculator shows every digit, but it doesn\'t know how precise your measurements were. Writing 7.875 cm² from 3.5 cm × 2.25 cm claims precision you never measured. Round the final answer!',
        },
        {
          kind: 'summary',
          points: [
            'Scientific notation: a number from 1 to 10 × 10^{n}. Small numbers have negative n.',
            'Leading zeros never count. Trailing zeros count only with a decimal point.',
            '× ÷ → fewest sig figs. + − → fewest decimal places.',
          ],
        },
      ],
      check: [
        {
          id: 'c0.1-q1',
          type: 'mcq',
          prompt: 'Which is **0.000607** in scientific notation?',
          choices: ['6.07 × 10^{4}', '6.07 × 10^{-4}', '60.7 × 10^{-5}', '6.07 × 10^{-3}'],
          answer: 1,
          hint: 'Count how many places the decimal moves to get 6.07. Moving right means a negative power.',
          explain: 'Move the decimal 4 places right to get 6.07, so the power is −4: **6.07 × 10^{-4}**. (60.7 × 10^{-5} has the same value but isn\'t proper form, since the first part must be between 1 and 10.)',
        },
        {
          id: 'c0.1-q2',
          type: 'mcq',
          prompt: 'A student calculates 3.0 g ÷ 7.115 mL. How many sig figs should the answer have?',
          choices: ['1', '2', '3', '4'],
          answer: 1,
          hint: 'For division, find the measurement with the fewest sig figs.',
          explain: '3.0 has 2 sig figs and 7.115 has 4. For × and ÷ use the fewest, so the answer gets **2**.',
        },
        {
          id: 'c0.1-q3',
          type: 'mcq',
          prompt: '25.12 mL + 3.4 mL = ?',
          choices: ['28.52 mL', '28.5 mL', '29 mL', '28.520 mL'],
          answer: 1,
          hint: 'For addition, look at decimal places, not sig figs.',
          explain: '3.4 has only 1 decimal place, so the sum is rounded to 1 decimal place: 28.52 → **28.5 mL**.',
        },
      ],
      flashcards: [
        { front: 'Do leading zeros (0.00…) count as sig figs?', back: '**Never.** They only locate the decimal point.' },
        { front: 'Sig fig rule for × and ÷?', back: 'The answer gets the **fewest sig figs** of the measurements.' },
        { front: 'Sig fig rule for + and −?', back: 'The answer gets the **fewest decimal places**.' },
      ],
    },
    {
      id: 'chem-0.2',
      ced: [],
      title: 'Dimensional Analysis: Units Are Your GPS',
      level: 'foundation',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'Here\'s a secret great chem students know: **you can solve most AP calculation problems by just following the units.** If your units cancel to what the question asks for, you are almost certainly on the right track.',
        },
        {
          kind: 'concept',
          title: 'Conversion factors are fancy 1s',
          body: 'Because 1 kg = 1000 g, the fraction (1000 g)/(1 kg) equals 1. Multiplying by it changes the units but not the amount.\n\nSet up each factor so the unit you **don\'t want** is on the **bottom** and cancels:\n\n2.5 kg × (1000 g / 1 kg) = **2500 g**',
        },
        {
          kind: 'concept',
          title: 'Metric prefixes you must know',
          body: '| Prefix | Symbol | Factor |\n| giga | G | 10^{9} |\n| mega | M | 10^{6} |\n| kilo | k | 10^{3} |\n| centi | c | 10^{-2} |\n| milli | m | 10^{-3} |\n| micro | μ | 10^{-6} |\n| nano | n | 10^{-9} |\n| pico | p | 10^{-12} |\n\nThese are on the AP Equations & Constants sheet. Also: 1 mL = 1 cm³, and 1 L = 1000 mL.',
        },
        {
          kind: 'example',
          title: 'Chain conversions',
          problem: 'Convert **45 minutes** into seconds, then into hours.',
          steps: [
            '45 min × (60 s / 1 min) = **2700 s**. Minutes are on top in "45 min" and on the bottom of the factor, so they cancel.',
            '45 min × (1 h / 60 min) = **0.75 h**',
          ],
          answer: '2700 s, which is 0.75 h',
          verify: [
            { stated: 2700, compute: () => 45 * 60 },
            { stated: 0.75, compute: () => 45 / 60 },
          ],
        },
        {
          kind: 'example',
          title: 'Squared units: the sneaky one',
          problem: 'How many cm³ are in **1 m³**?',
          steps: [
            '1 m = 100 cm, but the unit is **cubed**, so the factor gets cubed too.',
            '1 m³ × (100 cm / 1 m)³ = 100³ cm³ = **1,000,000 cm³** = 1 × 10^{6} cm³',
          ],
          answer: '1 × 10^{6} cm³ (which is also 1000 L)',
          verify: [{ stated: 1e6, compute: () => 100 ** 3 }],
        },
        {
          kind: 'try',
          question: {
            id: 'c0.2-t1',
            type: 'num',
            prompt: 'Convert **350 mL** to liters.',
            answer: 0.35,
            unit: 'L',
            hint: '1 L = 1000 mL. Put mL on the bottom so it cancels.',
            explain: '350 mL × (1 L / 1000 mL) = **0.350 L**',
            compute: () => 350 / 1000,
          },
        },
        {
          kind: 'hack',
          title: 'Write the units every single time',
          body: 'It feels slow, but writing units on every number is the #1 way to catch mistakes. If your answer comes out in g²/mol when you wanted grams, you know right away a factor is upside down.',
        },
        {
          kind: 'summary',
          points: [
            'A conversion factor equals 1, so it changes units, not amount.',
            'Put the unit you want to get rid of on the bottom.',
            'Squared or cubed units: square or cube the conversion factor too.',
          ],
        },
      ],
      check: [
        {
          id: 'c0.2-q1',
          type: 'num',
          prompt: 'Convert **2.5 × 10^{-3} g** to milligrams.',
          answer: 2.5,
          unit: 'mg',
          hint: '1 g = 1000 mg.',
          explain: '2.5 × 10^{-3} g × (1000 mg / 1 g) = **2.5 mg**',
          compute: () => 2.5e-3 * 1000,
        },
        {
          id: 'c0.2-q2',
          type: 'num',
          prompt: 'A car travels at 72 km/h. What is its speed in **m/s**?',
          answer: 20,
          unit: 'm/s',
          hint: 'Two conversions: km → m (×1000) and h → s (1 h = 3600 s).',
          explain: '72 km/h × (1000 m/1 km) × (1 h/3600 s) = **20 m/s**',
          compute: () => (72 * 1000) / 3600,
        },
        {
          id: 'c0.2-q3',
          type: 'mcq',
          prompt: 'Which conversion factor correctly converts **nanometers to meters**?',
          choices: ['(1 m / 10^{9} nm)', '(10^{9} m / 1 nm)', '(1 nm / 10^{-9} m)', '(10^{-9} nm / 1 m)'],
          answer: 0,
          hint: 'nm must be on the bottom to cancel. A nanometer is tiny: one billion of them make a meter.',
          explain: '1 nm = 10^{-9} m, which means 10^{9} nm = 1 m. With nm on the bottom: **(1 m / 10^{9} nm)**.',
        },
      ],
      flashcards: [
        { front: 'milli (m) = ?', back: '10^{-3}' },
        { front: 'micro (μ) = ?', back: '10^{-6}' },
        { front: 'nano (n) = ?', back: '10^{-9}' },
        { front: '1 mL = ? cm³', back: '1 mL = **1 cm³**' },
      ],
    },
    {
      id: 'chem-0.3',
      ced: [],
      title: 'Atoms, Isotopes & Ions',
      level: 'foundation',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'Every carbon atom in the universe has exactly 6 protons. Change the protons and you change the element. Change the neutrons and you get an **isotope**. Change the electrons and you get an **ion**.',
        },
        {
          kind: 'concept',
          title: 'Three particles',
          body: '| Particle | Charge | Location | Mass |\n| proton (p⁺) | +1 | nucleus | ≈ 1 amu |\n| neutron (n⁰) | 0 | nucleus | ≈ 1 amu |\n| electron (e⁻) | −1 | around nucleus | ≈ 0.00055 amu (tiny) |\n\n- **Atomic number (Z)** = number of protons. This defines the element.\n- **Mass number (A)** = protons + neutrons.\n- A neutral atom has electrons = protons.',
        },
        {
          kind: 'concept',
          title: 'Isotopes and ions',
          body: '**Isotopes**: same element (same protons), different neutrons. Carbon-12 has 6 neutrons and carbon-14 has 8.\n\n**Ions**: atoms that gained or lost electrons.\n- Lost electrons → more protons than electrons → **positive** (cation), like Na⁺.\n- Gained electrons → **negative** (anion), like Cl⁻.\n\nProtons never change in chemical reactions. Only electrons move.',
        },
        {
          kind: 'example',
          title: 'Count the particles',
          problem: 'How many protons, neutrons and electrons are in ^{56}Fe^{3+}?',
          steps: [
            'Iron is element 26 on the periodic table → **26 protons**.',
            'Neutrons = mass number − protons = 56 − 26 = **30 neutrons**.',
            'The 3+ charge means it lost 3 electrons: 26 − 3 = **23 electrons**.',
          ],
          answer: '26 p⁺, 30 n⁰, 23 e⁻',
          verify: [
            { stated: 30, compute: () => 56 - 26 },
            { stated: 23, compute: () => 26 - 3 },
          ],
        },
        {
          kind: 'hack',
          title: 'Cations are "paws-itive" 🐾',
          body: 'Ca**t**ions have a "t" that looks like a **+** sign. An**ions** are **N**egative. And remember: losing a negative thing (an electron) makes you **more positive**.',
        },
        {
          kind: 'concept',
          title: 'Reading the periodic table map',
          body: '- **Rows** are periods. **Columns** are groups (families) with similar properties.\n- **Metals** are on the left and center, **nonmetals** on the upper right, with **metalloids** along the staircase.\n- Group 1: alkali metals. Group 2: alkaline earth metals. Group 17: halogens. Group 18: noble gases.\n- Typical ion charges: Group 1 → +1, Group 2 → +2, Al → +3, Group 16 → −2, Group 17 → −1.',
        },
        {
          kind: 'summary',
          points: [
            'Protons decide the element. Neutrons decide the isotope. Electrons decide the charge.',
            'Mass number = protons + neutrons.',
            'Positive ion = lost electrons. Negative ion = gained electrons.',
          ],
        },
      ],
      check: [
        {
          id: 'c0.3-q1',
          type: 'mcq',
          prompt: 'An ion has 16 protons, 18 electrons and 16 neutrons. What is it?',
          choices: ['^{32}S^{2-}', '^{32}S^{2+}', '^{34}Ar', '^{16}O^{2-}'],
          answer: 0,
          hint: 'Protons tell you the element. Compare protons and electrons to get the charge.',
          explain: '16 protons is sulfur. Mass number = 16 + 16 = 32. Two extra electrons give a 2− charge: **^{32}S^{2-}**.',
        },
        {
          id: 'c0.3-q2',
          type: 'mcq',
          prompt: 'Carbon-12 and carbon-14 differ in their number of…',
          choices: ['protons', 'electrons', 'neutrons', 'charge'],
          answer: 2,
          explain: 'Isotopes of the same element always have the same number of protons (6 for carbon) but different numbers of **neutrons** (6 vs. 8).',
        },
        {
          id: 'c0.3-q3',
          type: 'mcq',
          prompt: 'What ion does magnesium (Group 2) usually form?',
          choices: ['Mg⁺', 'Mg²⁺', 'Mg²⁻', 'Mg⁻'],
          answer: 1,
          hint: 'Group 2 metals lose their 2 outer electrons.',
          explain: 'Group 2 metals lose 2 valence electrons, giving **Mg²⁺**.',
        },
      ],
      flashcards: [
        { front: 'Mass number = ?', back: 'protons + neutrons' },
        { front: 'What makes isotopes of an element different?', back: 'Different numbers of **neutrons** (same protons).' },
        { front: 'Cation vs. anion?', back: 'Cation = **positive** (lost e⁻). Anion = **negative** (gained e⁻).' },
      ],
    },
    {
      id: 'chem-0.4',
      ced: [],
      title: 'Naming Compounds & Polyatomic Ions',
      level: 'foundation',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'NaCl is table salt. NaClO is bleach. One oxygen atom makes a big difference! Knowing names and formulas is the "vocabulary" of chemistry. Once you know it, problems become much easier to read.',
        },
        {
          kind: 'concept',
          title: 'Ionic compounds: balance the charges',
          body: 'Ionic compound = cation (usually a metal) + anion. The total charge must be **zero**.\n\n- Name: cation name + anion name. NaCl = sodium chlor**ide** (single-atom anions end in **-ide**).\n- Metals with more than one possible charge get a Roman numeral: FeCl₃ = iron(III) chloride.\n\n**Criss-cross trick:** Al³⁺ and O²⁻ → cross the charge numbers to get {{Al2O3}}. Then reduce if you can: Mg²⁺ and O²⁻ → Mg₂O₂ → {{MgO}}.',
        },
        {
          kind: 'concept',
          title: 'Polyatomic ions to memorize',
          body: '| Ion | Name |\n| {{NH4^+}} | ammonium |\n| {{OH^-}} | hydroxide |\n| {{NO3^-}} | nitrate |\n| {{NO2^-}} | nitrite |\n| {{SO4^2-}} | sulfate |\n| {{SO3^2-}} | sulfite |\n| {{CO3^2-}} | carbonate |\n| {{HCO3^-}} | hydrogen carbonate (bicarbonate) |\n| {{PO4^3-}} | phosphate |\n| {{C2H3O2^-}} (or CH₃COO⁻) | acetate |\n| {{ClO^-}} / {{ClO2^-}} / {{ClO3^-}} / {{ClO4^-}} | hypochlorite / chlorite / chlorate / perchlorate |\n| {{MnO4^-}} | permanganate |\n| {{Cr2O7^2-}} | dichromate |\n| {{CN^-}} | cyanide |',
        },
        {
          kind: 'hack',
          title: '"Nick the Camel ate a Clam for Supper in Phoenix"',
          body: 'Consonants in each word = number of **oxygens**. Vowels = the negative **charge**. "-ate" ions:\n\n- **Nick**: 3 consonants, 1 vowel → {{NO3^-}} nitrate\n- **Camel**: 3 consonants, 2 vowels → {{CO3^2-}} carbonate\n- **Clam**: 3 consonants, 1 vowel → {{ClO3^-}} chlorate\n- **Supper**: 4 consonants, 2 vowels → {{SO4^2-}} sulfate\n- **Phoenix**: 4 consonants, 3 vowels → {{PO4^3-}} phosphate\n\nThen **-ite** = one **fewer** oxygen, same charge: {{NO2^-}} is nitrite.',
        },
        {
          kind: 'concept',
          title: 'Molecular (covalent) compounds: use prefixes',
          body: 'Two nonmetals → use Greek prefixes: mono-, di-, tri-, tetra-, penta-, hexa-.\n\n- {{CO2}} = carbon **di**oxide\n- {{N2O4}} = **di**nitrogen **tetr**oxide\n- {{CO}} = carbon **mon**oxide (skip "mono" on the first element)\n\nNo prefixes for ionic compounds! {{CaCl2}} is calcium chloride, not calcium dichloride.',
        },
        {
          kind: 'try',
          question: {
            id: 'c0.4-t1',
            type: 'mcq',
            prompt: 'What is the formula of **calcium phosphate**?',
            choices: ['{{CaPO4}}', '{{Ca3(PO4)2}}', '{{Ca2(PO4)3}}', '{{Ca(PO4)2}}'],
            answer: 1,
            hint: 'Ca²⁺ and PO₄³⁻. What numbers make the total charge zero?',
            explain: '3 Ca²⁺ = +6 and 2 PO₄³⁻ = −6, total 0 → **Ca₃(PO₄)₂**. Use parentheses when you need more than one polyatomic ion.',
          },
        },
        {
          kind: 'trap',
          body: 'Don\'t change the formula *inside* a polyatomic ion to balance charges. {{SO4^2-}} is always SO₄. To get two of them, write (SO₄)₂, never S₂O₈.',
        },
        {
          kind: 'summary',
          points: [
            'Ionic: charges must add to zero. Use the criss-cross trick, then reduce.',
            'Memorize the polyatomic ions with "Nick the Camel…". -ite has one less O than -ate.',
            'Molecular (nonmetal + nonmetal): use prefixes.',
          ],
        },
      ],
      check: [
        {
          id: 'c0.4-q1',
          type: 'mcq',
          prompt: 'What is the name of {{Fe2O3}}?',
          choices: ['iron oxide', 'iron(II) oxide', 'iron(III) oxide', 'diiron trioxide'],
          answer: 2,
          hint: 'Each O is 2−, so three O = −6. Two Fe must add up to +6.',
          explain: '3 O²⁻ = −6, so each of the 2 Fe atoms is +3 → **iron(III) oxide**. Iron is a metal, so we use a Roman numeral, not prefixes.',
        },
        {
          id: 'c0.4-q2',
          type: 'mcq',
          prompt: 'Which is the formula for the **sulfite** ion?',
          choices: ['{{SO4^2-}}', '{{SO3^2-}}', '{{S^2-}}', '{{SO3^-}}'],
          answer: 1,
          hint: 'Sulfate is SO₄²⁻. "-ite" has one fewer oxygen and the same charge.',
          explain: 'Sulfate = SO₄²⁻, so sulfite has one fewer O and the same charge: **SO₃²⁻**. (S²⁻ is sulfide.)',
        },
        {
          id: 'c0.4-q3',
          type: 'mcq',
          prompt: 'What is the formula of **ammonium carbonate**?',
          choices: ['{{NH4CO3}}', '{{(NH4)2CO3}}', '{{NH4(CO3)2}}', '{{(NH3)2CO3}}'],
          answer: 1,
          explain: 'NH₄⁺ is +1 and CO₃²⁻ is −2, so you need two ammonium ions: **(NH₄)₂CO₃**.',
        },
      ],
      flashcards: [
        { front: 'Nitrate', back: '{{NO3^-}}' },
        { front: 'Sulfate', back: '{{SO4^2-}}' },
        { front: 'Carbonate', back: '{{CO3^2-}}' },
        { front: 'Phosphate', back: '{{PO4^3-}}' },
        { front: 'Ammonium', back: '{{NH4^+}}' },
        { front: 'Acetate', back: '{{C2H3O2^-}} (also written CH₃COO⁻)' },
        { front: 'Hydroxide', back: '{{OH^-}}' },
        { front: 'Permanganate', back: '{{MnO4^-}}' },
      ],
    },
    {
      id: 'chem-0.5',
      ced: [],
      title: 'Balancing Chemical Equations',
      level: 'foundation',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'Atoms are never created or destroyed in a chemical reaction. They are just rearranged, like LEGO bricks rebuilt into a new shape. A **balanced equation** shows that every brick is accounted for.',
        },
        {
          kind: 'concept',
          title: 'The golden rule',
          body: 'Change only the **coefficients** (the big numbers in front). **Never** change the subscripts, because that changes the substance itself. H₂O₂ is hydrogen peroxide, not water!\n\nUnbalanced: {{H2 + O2 -> H2O}}\nBalanced: [[eq: 2H2(g) + O2(g) -> 2H2O(l)]]\n\nCheck: H = 4 on both sides and O = 2 on both sides. ✓',
        },
        {
          kind: 'hack',
          title: 'The MINO order',
          body: 'Balance in this order to avoid going in circles:\n\n1. **M**etals\n2. **I**ons (polyatomic ions that appear on both sides as a unit)\n3. **N**onmetals (other than H and O)\n4. **O**xygen and hydrogen last\n\nFinally, check every element, and reduce the coefficients if they share a common factor.',
        },
        {
          kind: 'example',
          title: 'Burning propane',
          problem: 'Balance: {{C3H8 + O2 -> CO2 + H2O}}',
          steps: [
            'Carbon: 3 on the left, so put **3** in front of CO₂.',
            'Hydrogen: 8 on the left, so put **4** in front of H₂O (4 × 2 = 8).',
            'Oxygen on the right: 3 × 2 + 4 × 1 = 10 O atoms. So you need **5** O₂ on the left.',
          ],
          answer: '[[eq: C3H8(g) + 5O2(g) -> 3CO2(g) + 4H2O(l)]]',
        },
        {
          kind: 'try',
          question: {
            id: 'c0.5-t1',
            type: 'mcq',
            prompt: 'Which coefficients balance {{_Al + _O2 -> _Al2O3}}?',
            choices: ['1, 1, 1', '2, 3, 1', '4, 3, 2', '2, 1, 1'],
            answer: 2,
            hint: 'O is 2 on the left and 3 on the right. The lowest common multiple of 2 and 3 is 6.',
            explain: '6 O atoms: 3 O₂ and 2 Al₂O₃. Then 2 Al₂O₃ contains 4 Al, so 4 Al. [[eq: 4Al(s) + 3O2(g) -> 2Al2O3(s)]]',
          },
        },
        {
          kind: 'trap',
          body: 'Count atoms **inside parentheses** carefully: {{Ca(OH)2}} has 2 O and 2 H. And 3Ca(OH)₂ has 3 Ca, 6 O and 6 H.',
        },
        {
          kind: 'summary',
          points: [
            'Only change coefficients, never subscripts.',
            'Balance metals, then polyatomic ions, then nonmetals, then O and H last.',
            'Always do a final count of every element.',
          ],
        },
      ],
      check: [
        {
          id: 'c0.5-q1',
          type: 'mcq',
          prompt: 'Balance: {{_CH4 + _O2 -> _CO2 + _H2O}}. What is the coefficient of O₂?',
          choices: ['1', '2', '3', '4'],
          answer: 1,
          hint: 'Balance C, then H, then count the O atoms on the right.',
          explain: '[[eq: CH4(g) + 2O2(g) -> CO2(g) + 2H2O(l)]] The right side has 2 + 2 = 4 O atoms, so you need **2** O₂.',
        },
        {
          id: 'c0.5-q2',
          type: 'mcq',
          prompt: 'Which equation is balanced?',
          choices: [
            '{{Fe + O2 -> Fe2O3}}',
            '{{2Fe + 3O2 -> 2Fe2O3}}',
            '{{4Fe + 3O2 -> 2Fe2O3}}',
            '{{4Fe + 6O2 -> 2Fe2O3}}',
          ],
          answer: 2,
          explain: '4Fe + 3O₂ → 2Fe₂O₃: Fe = 4 on both sides and O = 6 on both sides. ✓ [[eq: 4Fe(s) + 3O2(g) -> 2Fe2O3(s)]]',
        },
        {
          id: 'c0.5-q3',
          type: 'mcq',
          prompt: 'How many oxygen atoms are in **3Ca(NO₃)₂**?',
          choices: ['6', '9', '12', '18'],
          answer: 3,
          hint: 'Each Ca(NO₃)₂ has 2 nitrate ions, and each nitrate has 3 O.',
          explain: 'One Ca(NO₃)₂ has 2 × 3 = 6 O. Three of them: 3 × 6 = **18** O atoms.',
        },
      ],
      flashcards: [
        { front: 'When balancing, what can you change?', back: 'Only **coefficients**, never subscripts.' },
        { front: 'Balancing order (MINO)?', back: 'Metals → polyatomic Ions → Nonmetals → O and H last' },
      ],
    },
    {
      id: 'chem-0.6',
      ced: [],
      title: 'Logs & Exponents for Chemistry',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'pH, pKa, rate laws and the Nernst equation all use logarithms. Logs look scary, but they ask one simple question: **"10 to what power gives me this number?"**',
        },
        {
          kind: 'concept',
          title: 'What a log means',
          body: 'log(1000) = 3, because 10^{3} = 1000.\nlog(0.01) = −2, because 10^{-2} = 0.01.\n\nThe "undo" button: if log(x) = y, then **x = 10^{y}**.\n\n**ln** is the "natural log," which uses base *e* ≈ 2.718 instead of 10. It shows up in kinetics and thermodynamics (ln[A], ln K). It works the same way: if ln(x) = y, then x = e^{y}.',
        },
        {
          kind: 'concept',
          title: 'Three log rules worth knowing',
          body: '- log(a × b) = log a + log b\n- log(a / b) = log a − log b\n- log(a^{n}) = n log a\n\nThe most useful consequence: **log(10^{n}) = n**. So for any number written as 1 × 10^{-n}, the log is just −n.',
        },
        {
          kind: 'hack',
          title: 'Estimate pH-style logs in your head',
          body: 'For a number like **3.2 × 10^{-5}**:\n- −log(1 × 10^{-5}) = 5\n- −log(10 × 10^{-5}) = 4\n- So −log(3.2 × 10^{-5}) is **between 4 and 5**. (It\'s 4.49.)\n\nCalculators are allowed on the AP exam, but this "between two integers" estimate is faster, catches calculator slips, and lets you eliminate wrong choices instantly.',
        },
        {
          kind: 'example',
          title: 'From a log back to a number',
          problem: 'If −log x = 3.00, what is x?',
          steps: ['−log x = 3.00 means log x = −3.00.', 'Undo the log: x = 10^{-3.00} = **0.0010** (1.0 × 10^{-3})'],
          answer: 'x = 1.0 × 10^{-3}',
          verify: [{ stated: 1e-3, compute: () => 10 ** -3 }],
        },
        {
          kind: 'try',
          question: {
            id: 'c0.6-t1',
            type: 'mcq',
            prompt: 'Without a calculator: −log(6 × 10^{-9}) is between…',
            choices: ['6 and 7', '8 and 9', '9 and 10', '−9 and −8'],
            answer: 1,
            hint: '−log(1 × 10^{-9}) = 9 and −log(1 × 10^{-8}) = 8. Where does 6 × 10^{-9} fall?',
            explain: '6 × 10^{-9} is between 1 × 10^{-9} and 1 × 10^{-8}, so −log is between **8 and 9**. (It\'s 8.22.)',
          },
        },
        {
          kind: 'summary',
          points: [
            'log(x) = the power of 10 that gives x. Undo it with x = 10^{log x}.',
            'log(10^{n}) = n.',
            'Estimate −log of (a × 10^{-n}): it falls between n − 1 and n.',
          ],
        },
      ],
      check: [
        {
          id: 'c0.6-q1',
          type: 'num',
          prompt: 'What is **log(10^{-4})**?',
          answer: -4,
          explain: 'log(10^{n}) = n, so log(10^{-4}) = **−4**.',
          compute: () => Math.log10(1e-4),
        },
        {
          id: 'c0.6-q2',
          type: 'num',
          prompt: 'If log x = 2.00, what is x?',
          answer: 100,
          explain: 'x = 10^{2.00} = **100**.',
          compute: () => 10 ** 2,
        },
        {
          id: 'c0.6-q3',
          type: 'mcq',
          prompt: 'log(2 × 10^{3}) equals…',
          choices: ['log 2 × 3', 'log 2 + 3', '2 + log 3', '3 − log 2'],
          answer: 1,
          hint: 'log(a × b) = log a + log b.',
          explain: 'log(2 × 10^{3}) = log 2 + log(10^{3}) = **log 2 + 3** ≈ 0.30 + 3 = 3.30.',
        },
      ],
      flashcards: [
        { front: 'log(10^{n}) = ?', back: '**n**' },
        { front: 'If log x = y, then x = ?', back: 'x = **10^{y}**' },
        { front: 'log(a × b) = ?', back: 'log a + log b' },
      ],
    },
  ],
  checkpoint: [
    {
      id: 'c0-cp1',
      type: 'mcq',
      prompt: 'How many sig figs are in **1.200 × 10^{3}**?',
      choices: ['2', '3', '4', '5'],
      answer: 2,
      explain: 'In scientific notation, every digit in the 1.200 part is significant: 1, 2, 0, 0 = **4**.',
    },
    {
      id: 'c0-cp2',
      type: 'num',
      prompt: 'What is the molar mass of water, {{H2O}}, to two decimal places? (H = 1.008, O = 16.00)',
      answer: 18.02,
      unit: 'g/mol',
      explain: '2(1.008) + 16.00 = **18.02 g/mol**',
      compute: () => molarMass('H2O'),
    },
    {
      id: 'c0-cp3',
      type: 'mcq',
      prompt: 'What is the formula for **potassium dichromate**?',
      choices: ['{{KCr2O7}}', '{{K2Cr2O7}}', '{{K2CrO4}}', '{{K(Cr2O7)2}}'],
      answer: 1,
      explain: 'K⁺ (+1) and Cr₂O₇²⁻ (−2) → you need 2 K⁺: **K₂Cr₂O₇**.',
    },
  ],
}
