import type { Unit } from '../types'
import { CONST, molarMass } from '../../lib/chem'

const NA = CONST.NA

export const unit1: Unit = {
  id: 'chem-u1',
  number: 1,
  title: 'Atomic Structure and Properties',
  weight: '7–9%',
  blurb: 'Counting atoms with moles, what atoms are made of, how electrons are arranged, and why the periodic table has its patterns.',
  badge: { name: 'Atom Architect', emoji: '⚛️' },
  lessons: [
    // ---------------- FOUNDATION ----------------
    {
      id: 'chem-1.1',
      ced: ['1.1'],
      title: 'Moles and Molar Mass',
      level: 'foundation',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'You can\'t count atoms one by one. A single grain of salt has more than 10^{17} of them! So chemists count by **weighing**, the same way a bank weighs a bag of coins instead of counting each one.',
        },
        {
          kind: 'concept',
          title: 'The mole is a chemist\'s "dozen"',
          body: 'A dozen = 12 things. A **mole** = **6.022 × 10^{23}** things (Avogadro\'s number, N_{A}).\n\n1 mol of carbon atoms = 6.022 × 10^{23} carbon atoms\n1 mol of water molecules = 6.022 × 10^{23} H₂O molecules\n\n**Why this number?** It makes the mass in grams match the mass in amu. One water molecule has a mass of about 18.02 amu, so **1 mole of water has a mass of 18.02 g**. That is the **molar mass**, M (g/mol).',
        },
        {
          kind: 'concept',
          title: 'The one equation',
          body: '**n = m / M**\n\n- n = moles\n- m = mass in grams\n- M = molar mass in g/mol (add up the atomic masses from the periodic table)\n\nExample: M of {{CO2}} = 12.01 + 2(16.00) = **44.01 g/mol**.',
        },
        {
          kind: 'hack',
          title: 'The mole is the hub 🚉',
          body: 'Picture a train station with the mole in the middle:\n\n**grams** ⇄ **moles** ⇄ **particles**\n\n- grams → moles: **÷ M**\n- moles → grams: **× M**\n- moles → particles: **× 6.022 × 10^{23}**\n- particles → moles: **÷ 6.022 × 10^{23}**\n\nYou can never jump straight from grams to particles. Always pass through moles!',
        },
        {
          kind: 'example',
          title: 'Grams → moles → molecules',
          problem: 'How many molecules are in **36.0 g of water**?',
          steps: [
            'Molar mass of H₂O = 2(1.008) + 16.00 = **18.02 g/mol**',
            'Moles: n = 36.0 g ÷ 18.02 g/mol = **2.00 mol**',
            'Molecules: 2.00 mol × 6.022 × 10^{23} /mol = **1.20 × 10^{24} molecules**',
          ],
          answer: '1.20 × 10^{24} water molecules',
          verify: [
            { stated: 18.02, compute: () => molarMass('H2O') },
            { stated: 2.0, compute: () => 36.0 / molarMass('H2O') },
            { stated: 1.2e24, compute: () => (36.0 / molarMass('H2O')) * NA },
          ],
        },
        {
          kind: 'try',
          question: {
            id: 'c1.1-t1',
            type: 'num',
            prompt: 'How many moles are in **10.0 g of NaOH**? (Na = 22.99, O = 16.00, H = 1.008)',
            answer: 0.25,
            unit: 'mol',
            hint: 'First add up the molar mass of NaOH, then divide the grams by it.',
            explain: 'M = 22.99 + 16.00 + 1.008 = 40.00 g/mol. n = 10.0 ÷ 40.00 = **0.250 mol**.',
            compute: () => 10.0 / molarMass('NaOH'),
          },
        },
        {
          kind: 'trap',
          body: '**Count atoms vs. molecules carefully.** 1 mol of H₂O contains 1 mol of molecules but **3 mol of atoms** (2 H + 1 O). And oxygen gas is **O₂**, so its molar mass is 32.00 g/mol, not 16.00.',
        },
        {
          kind: 'summary',
          points: [
            '1 mol = 6.022 × 10^{23} particles (on your equation sheet).',
            'n = m/M. The molar mass in g/mol has the same number as the particle\'s mass in amu.',
            'Always go through moles: grams ⇄ moles ⇄ particles.',
          ],
        },
      ],
      check: [
        {
          id: 'c1.1-q1',
          type: 'num',
          prompt: 'What is the mass of **0.500 mol of CO₂**? (C = 12.01, O = 16.00)',
          answer: 22.0,
          unit: 'g',
          hint: 'moles → grams: multiply by the molar mass.',
          explain: 'M(CO₂) = 44.01 g/mol. m = 0.500 mol × 44.01 g/mol = **22.0 g**.',
          compute: () => 0.5 * molarMass('CO2'),
        },
        {
          id: 'c1.1-q2',
          type: 'mcq',
          prompt: 'Which sample contains the **most atoms**?',
          choices: ['1.0 mol of He', '1.0 mol of O₂', '1.0 mol of H₂O', '1.0 mol of CH₄'],
          answer: 3,
          hint: 'Each sample has the same number of molecules. Which molecule has the most atoms?',
          explain: 'All samples have 6.022 × 10^{23} units, but each CH₄ molecule has **5 atoms**, more than He (1), O₂ (2) or H₂O (3).',
        },
        {
          id: 'c1.1-q3',
          type: 'num',
          prompt: 'How many **atoms of hydrogen** are in 0.25 mol of H₂O?',
          answer: 3.011e23,
          unit: 'H atoms',
          hint: 'Each H₂O has 2 H atoms, so 0.25 mol H₂O contains 0.50 mol of H atoms.',
          explain: '0.25 mol H₂O × 2 mol H/mol H₂O = 0.50 mol H. Then 0.50 × 6.022 × 10^{23} = **3.0 × 10^{23}** H atoms.',
          compute: () => 0.25 * 2 * NA,
        },
        {
          id: 'c1.1-q4',
          type: 'mcq',
          prompt: 'One atom of an element has an average mass of 40.08 amu. What is the mass of 1 mole of these atoms?',
          choices: ['40.08 g', '40.08 × 6.022 × 10^{23} g', '40.08 ÷ 6.022 × 10^{23} g', '6.022 × 10^{23} g'],
          answer: 0,
          explain: 'The average mass of one particle in amu has the same number as the molar mass in grams, so 1 mol has a mass of **40.08 g** (that\'s calcium).',
        },
      ],
      flashcards: [
        { front: 'Avogadro\'s number', back: '6.022 × 10^{23} per mole' },
        { front: 'Equation linking mass, moles and molar mass', back: '**n = m/M**' },
        { front: 'Path from grams to particles?', back: 'grams **÷ M** → moles **× N_{A}** → particles' },
      ],
    },
    {
      id: 'chem-1.5',
      ced: ['1.5'],
      title: 'Atomic Structure & Electron Configuration',
      level: 'foundation',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'Why is sodium wildly reactive while neon does nothing at all? They differ by just **one electron**. Where electrons sit, and how tightly they are held, explains almost all of chemistry.',
        },
        {
          kind: 'concept',
          title: 'Coulomb\'s law: the force behind everything',
          body: 'The atom is a positive nucleus (protons + neutrons) with negative electrons around it. Opposite charges attract.\n\n**F ∝ q₁q₂ / r²**\n\n- **Bigger charges** → stronger attraction.\n- **Bigger distance (r)** → much weaker attraction. Doubling r cuts the force to 1/4.\n\nYou will use this idea to *explain* trends all year: "more protons → stronger pull" or "electron farther away → weaker pull."',
        },
        {
          kind: 'concept',
          title: 'Shells and subshells',
          body: 'Electrons are arranged in **shells** (n = 1, 2, 3 …) that contain **subshells**:\n\n| Subshell | Max electrons |\n| s | 2 |\n| p | 6 |\n| d | 10 |\n| f | 14 |\n\n**Aufbau principle:** fill the lowest-energy subshells first:\n1s → 2s → 2p → 3s → 3p → **4s → 3d** → 4p → 5s → 4d → 5p …\n\n**Core electrons** are in inner shells. **Valence electrons** are in the outermost shell and do the chemistry.',
        },
        {
          kind: 'hack',
          title: 'The periodic table IS the filling order',
          body: 'Read the table left to right, top to bottom:\n\n- Groups 1–2 = **s block**\n- Groups 13–18 = **p block**\n- Transition metals = **d block**, and the shell number is one less than the row: row 4 fills **3d**.\n\nSo to write a configuration, walk across the table to your element, writing each block as you pass it.',
        },
        {
          kind: 'example',
          title: 'Sulfur (16 electrons)',
          problem: 'Write the ground-state electron configuration of **S**.',
          steps: [
            'Fill in order: 1s² (2) → 2s² (4) → 2p⁶ (10) → 3s² (12) → 3p⁴ (16 ✓)',
            'Full form: **1s² 2s² 2p⁶ 3s² 3p⁴**',
            'Noble-gas shorthand: neon covers the first 10 electrons → **[Ne] 3s² 3p⁴**',
          ],
          answer: '1s² 2s² 2p⁶ 3s² 3p⁴, or [Ne] 3s² 3p⁴. That\'s 6 valence electrons (3s² 3p⁴).',
        },
        {
          kind: 'concept',
          title: 'Configurations of ions',
          body: '- **Anions:** add electrons to the next open spot. Cl⁻ = [Ne] 3s² 3p⁶, the same as argon.\n- **Cations:** remove electrons from the **highest shell (n) first**.\n\n⚠️ Transition metals lose their **4s** electrons **before** 3d, even though 4s filled first:\nFe = [Ar] 4s² 3d⁶ → **Fe²⁺ = [Ar] 3d⁶** (not [Ar] 4s² 3d⁴)',
        },
        {
          kind: 'try',
          question: {
            id: 'c1.5-t1',
            type: 'mcq',
            prompt: 'What is the electron configuration of **Ca²⁺**?',
            choices: ['[Ar] 4s²', '[Ar]', '[Ar] 4s² 3d²', '[Ne] 3s²'],
            answer: 1,
            hint: 'Ca = [Ar] 4s². Remove 2 electrons from the highest shell.',
            explain: 'Ca = [Ar] 4s². Losing the two 4s electrons leaves **[Ar]**, which is 1s² 2s² 2p⁶ 3s² 3p⁶.',
          },
        },
        {
          kind: 'concept',
          title: 'Ionization energy and Coulomb\'s law',
          body: '**Ionization energy** = the energy needed to remove an electron.\n\nIt is larger when the electron is:\n- **closer** to the nucleus (smaller r), and/or\n- attracted by a larger **effective nuclear charge**: the nuclear charge minus the shielding from inner (core) electrons.\n\nSo core electrons need far more energy to remove than valence electrons.',
        },
        {
          kind: 'trap',
          body: 'Good news: the AP exam **does not** test quantum numbers (n, l, m_{l}, m_{s}). It also does not ask you to write configurations for the "exception" elements like Cr and Cu. Focus on Aufbau, noble-gas shorthand and ions.',
        },
        {
          kind: 'summary',
          points: [
            'Coulomb\'s law: F ∝ q₁q₂/r². More charge = stronger pull. More distance = weaker pull.',
            'Fill subshells in order (s 2, p 6, d 10). Use the periodic table as your map.',
            'Cations lose electrons from the highest n first (4s before 3d).',
          ],
        },
      ],
      check: [
        {
          id: 'c1.5-q1',
          type: 'mcq',
          prompt: 'What is the ground-state electron configuration of **phosphorus (P)**?',
          choices: ['1s² 2s² 2p⁶ 3s² 3p³', '1s² 2s² 2p⁶ 3s² 3p⁵', '1s² 2s² 2p⁶ 3p⁵', '[Ar] 3s² 3p³'],
          answer: 0,
          hint: 'P has 15 electrons. It\'s the 3rd element in the 3p row.',
          explain: '15 electrons: 2 + 2 + 6 + 2 + 3 = 15 → **1s² 2s² 2p⁶ 3s² 3p³** (that is, [Ne] 3s² 3p³).',
        },
        {
          id: 'c1.5-q2',
          type: 'mcq',
          prompt: 'What is the configuration of **Fe³⁺**? (Fe = [Ar] 4s² 3d⁶)',
          choices: ['[Ar] 4s² 3d³', '[Ar] 3d⁵', '[Ar] 4s¹ 3d⁴', '[Ar] 3d⁶'],
          answer: 1,
          hint: 'Remove the 4s electrons first, then from 3d.',
          explain: 'Remove the two 4s electrons, then one 3d electron: **[Ar] 3d⁵**.',
        },
        {
          id: 'c1.5-q3',
          type: 'mcq',
          prompt: 'If the distance between two charged particles **doubles**, the attractive force becomes…',
          choices: ['2 times larger', '1/2 as large', '1/4 as large', '4 times larger'],
          answer: 2,
          hint: 'F ∝ 1/r². Plug in 2r.',
          explain: 'F ∝ 1/r². With 2r: 1/(2r)² = 1/(4r²), so the force is **1/4** as large.',
        },
        {
          id: 'c1.5-q4',
          type: 'mcq',
          prompt: 'How many **valence electrons** does a selenium (Se) atom have? Se = [Ar] 4s² 3d¹⁰ 4p⁴',
          choices: ['4', '6', '16', '34'],
          answer: 1,
          hint: 'Valence electrons are in the outermost shell (n = 4).',
          explain: 'The outermost shell is n = 4: 4s² 4p⁴ → **6** valence electrons. (The filled 3d electrons count as core.)',
        },
      ],
      flashcards: [
        { front: 'Coulomb\'s law (proportionality)', back: 'F ∝ q₁q₂ / r²' },
        { front: 'Max electrons in s, p, d, f?', back: 's = 2, p = 6, d = 10, f = 14' },
        { front: 'Transition-metal cations lose which electrons first?', back: 'The **4s** (highest n) electrons, before 3d.' },
        { front: 'Effective nuclear charge', back: 'The net positive pull a valence electron feels: nuclear charge minus shielding by core electrons.' },
      ],
    },
    // ---------------- CORE ----------------
    {
      id: 'chem-1.2',
      ced: ['1.2'],
      title: 'Mass Spectra of Elements',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'The periodic table lists chlorine as **35.45 amu**, but no chlorine atom actually weighs 35.45 amu! Chlorine atoms weigh about 35 or about 37. The 35.45 is an **average**, and a mass spectrometer shows us the mix.',
        },
        {
          kind: 'concept',
          title: 'Reading a mass spectrum',
          body: 'A mass spectrometer sorts atoms by mass.\n\n- Each **peak** = one **isotope**, and its position = that isotope\'s mass.\n- Peak **height** = how **abundant** that isotope is.',
          diagram: 'mass-spec-cl',
        },
        {
          kind: 'concept',
          title: 'Average atomic mass = weighted average',
          body: '**Average mass = Σ (isotope mass × fractional abundance)**\n\nIt works just like a class grade where tests count more than homework: each isotope "counts" according to its abundance.',
        },
        {
          kind: 'example',
          title: 'Chlorine',
          problem: 'Chlorine is 75.76% ^{35}Cl (34.969 amu) and 24.24% ^{37}Cl (36.966 amu). Find the average atomic mass.',
          steps: [
            'Convert percents to decimals: 0.7576 and 0.2424.',
            '34.969 × 0.7576 = 26.49 and 36.966 × 0.2424 = 8.961',
            'Add them: 26.49 + 8.961 = **35.45 amu** ✓ (matches the periodic table!)',
          ],
          answer: '35.45 amu',
          verify: [{ stated: 35.45, compute: () => 34.969 * 0.7576 + 36.966 * 0.2424 }],
        },
        {
          kind: 'hack',
          title: 'Estimate first, calculate second',
          body: 'The average always lands **closer to the most abundant isotope**. Chlorine\'s 35.45 is much closer to 35 than to 37 because ^{35}Cl is about 3/4 of all Cl atoms.\n\nOn multiple choice, this estimate alone often picks the right answer in seconds.',
        },
        {
          kind: 'try',
          question: {
            id: 'c1.2-t1',
            type: 'num',
            prompt: 'Boron is 19.9% ^{10}B (10.013 amu) and 80.1% ^{11}B (11.009 amu). What is its average atomic mass?',
            answer: 10.81,
            unit: 'amu',
            tolerance: 0.002,
            hint: '(10.013 × 0.199) + (11.009 × 0.801)',
            explain: '10.013(0.199) + 11.009(0.801) = 1.993 + 8.818 = **10.81 amu**. It\'s close to 11 because ^{11}B is the most common isotope.',
            compute: () => 10.013 * 0.199 + 11.009 * 0.801,
          },
        },
        {
          kind: 'trap',
          body: 'The AP exam only uses mass spectra of **a single element**. It won\'t ask you to read spectra of mixtures or of molecules that break into fragments.',
        },
        {
          kind: 'summary',
          points: [
            'Peaks = isotopes. Position = mass. Height = relative abundance.',
            'Average atomic mass = Σ(mass × fraction).',
            'The average is pulled toward the most abundant isotope.',
          ],
        },
      ],
      check: [
        {
          id: 'c1.2-q1',
          type: 'mcq',
          prompt: 'A mass spectrum of an element shows peaks at 24 amu (79%), 25 amu (10%) and 26 amu (11%). Which element is it most likely?',
          choices: ['Na (22.99)', 'Mg (24.31)', 'Al (26.98)', 'Cr (52.00)'],
          answer: 1,
          hint: 'Estimate: the average will be a little above 24.',
          explain: '24(0.79) + 25(0.10) + 26(0.11) ≈ 24.3 amu → **magnesium**.',
        },
        {
          id: 'c1.2-q2',
          type: 'mcq',
          prompt: 'An element has two isotopes, ^{63}X and ^{65}X. Its average atomic mass is 63.55. Which statement is true?',
          choices: ['^{65}X is more abundant', '^{63}X is more abundant', 'They are equally abundant', 'You can\'t tell from this information'],
          answer: 1,
          hint: 'Is 63.55 closer to 63 or to 65?',
          explain: '63.55 is much closer to 63, so **^{63}X is more abundant** (this element is copper: about 69% ^{63}Cu).',
        },
        {
          id: 'c1.2-q3',
          type: 'mcq',
          prompt: 'In a mass spectrum of a pure element, what does the **height** of each peak represent?',
          choices: ['The isotope\'s mass', 'The relative abundance of that isotope', 'The number of protons', 'The charge of the ion'],
          answer: 1,
          explain: 'The x-axis position gives the mass. The **height gives relative abundance**, meaning how common that isotope is.',
        },
      ],
      flashcards: [
        { front: 'Average atomic mass formula', back: 'Σ (isotope mass × fractional abundance)' },
        { front: 'Mass spectrum: peak position vs. height?', back: 'Position = **isotope mass**. Height = **relative abundance**.' },
      ],
    },
    {
      id: 'chem-1.3',
      ced: ['1.3'],
      title: 'Composition of Pure Substances',
      level: 'core',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'Water from a glacier, from your tap or from Mars is always **11.2% hydrogen and 88.8% oxygen** by mass. That fixed recipe is a law of nature.',
        },
        {
          kind: 'concept',
          title: 'Law of definite proportions',
          body: 'A pure compound always has the **same ratio of masses** of its elements, because its atoms are always combined in the same fixed ratio (its formula).\n\n**Mass percent** of an element = (mass of that element in 1 mol) ÷ (molar mass) × 100\n\nWater: %O = 16.00 ÷ 18.02 × 100 = **88.8%**',
        },
        {
          kind: 'concept',
          title: 'Empirical vs. molecular formula',
          body: '- **Empirical formula** = the **lowest whole-number ratio** of atoms.\n- **Molecular formula** = the actual number of atoms in one molecule.\n\nGlucose: molecular **C₆H₁₂O₆**, empirical **CH₂O** (divide everything by 6).\nIonic formulas like NaCl or CaCl₂ are usually written as the lowest whole-number ratio of ions.',
        },
        {
          kind: 'hack',
          title: 'The empirical formula chant',
          body: '🎵 **"Percent to mass, mass to mole, divide by small, multiply \'til whole."**\n\n1. Assume a 100 g sample, so percents become grams.\n2. Convert grams to moles (÷ M).\n3. Divide every mole number by the smallest.\n4. If you get x.5, multiply all by 2. If x.33 or x.67, multiply all by 3.',
        },
        {
          kind: 'example',
          title: 'Find the empirical formula',
          problem: 'A compound is **40.0% C, 6.7% H and 53.3% O** by mass. Its molar mass is 180 g/mol. Find the empirical and molecular formulas.',
          steps: [
            'Assume 100 g: 40.0 g C, 6.7 g H, 53.3 g O.',
            'Moles: C = 40.0/12.01 = 3.33. H = 6.7/1.008 = 6.6. O = 53.3/16.00 = 3.33.',
            'Divide by the smallest (3.33): C = 1, H ≈ 2, O = 1 → empirical formula **CH₂O** (mass 30.03 g/mol).',
            'Molar mass ÷ empirical mass = 180 / 30.03 ≈ **6**, so multiply everything by 6.',
          ],
          answer: 'Empirical CH₂O, molecular **C₆H₁₂O₆** (glucose)',
          verify: [
            { stated: 3.33, compute: () => 40.0 / 12.011, tol: 0.01 },
            { stated: 6.6, compute: () => 6.7 / 1.008, tol: 0.01 },
            { stated: 30.03, compute: () => molarMass('CH2O') },
            { stated: 6, compute: () => 180 / molarMass('CH2O'), tol: 0.01 },
          ],
        },
        {
          kind: 'try',
          question: {
            id: 'c1.3-t1',
            type: 'num',
            prompt: 'What is the mass percent of **carbon** in CO₂? (C = 12.01, O = 16.00)',
            answer: 27.29,
            unit: '%',
            tolerance: 0.005,
            hint: 'Mass of C in 1 mol ÷ molar mass of CO₂ × 100.',
            explain: '12.01 ÷ 44.01 × 100 = **27.3%** C',
            compute: () => (12.011 / molarMass('CO2')) * 100,
          },
        },
        {
          kind: 'frq',
          body: 'If an FRQ asks you to **justify** a formula from data, show the mole ratio explicitly, for example: "The mole ratio of C : H is 3.33 : 6.6, which is 1 : 2." Graders award points for showing the ratio, not just the final formula.',
        },
        {
          kind: 'summary',
          points: [
            'A pure compound always has the same mass ratio of its elements.',
            'Mass % = (element mass in formula ÷ molar mass) × 100.',
            'Empirical formula: % → g → mol → divide by smallest → whole numbers.',
          ],
        },
      ],
      check: [
        {
          id: 'c1.3-q1',
          type: 'mcq',
          prompt: 'What is the empirical formula of a compound that is **75% C and 25% H** by mass?',
          choices: ['CH', 'CH₂', 'CH₃', 'CH₄'],
          answer: 3,
          hint: '75 g C ÷ 12.01 and 25 g H ÷ 1.008, then divide by the smaller.',
          explain: 'C: 75/12.01 = 6.2 mol. H: 25/1.008 = 24.8 mol. Ratio 24.8/6.2 ≈ 4 → **CH₄** (methane).',
        },
        {
          id: 'c1.3-q2',
          type: 'mcq',
          prompt: 'Which pair has the **same empirical formula**?',
          choices: ['C₂H₂ and C₆H₆', 'CO and CO₂', 'C₂H₄ and C₂H₆', 'H₂O and H₂O₂'],
          answer: 0,
          explain: 'C₂H₂ (÷2) and C₆H₆ (÷6) both reduce to **CH**. The other pairs have different atom ratios.',
        },
        {
          id: 'c1.3-q3',
          type: 'num',
          prompt: 'A compound has the empirical formula **NO₂** and a molar mass of 92.0 g/mol. How many NO₂ units are in its molecular formula?',
          answer: 2,
          hint: 'Molar mass ÷ empirical formula mass.',
          explain: 'NO₂ = 14.01 + 2(16.00) = 46.01 g/mol. 92.0 ÷ 46.01 = **2** → molecular formula N₂O₄.',
          compute: () => Math.round(92.0 / molarMass('NO2')),
        },
      ],
      flashcards: [
        { front: 'Law of definite proportions', back: 'A pure compound always has the same mass ratio of its elements.' },
        { front: 'Empirical formula', back: 'The lowest whole-number ratio of atoms in a compound.' },
        { front: 'Steps to find an empirical formula', back: '% → grams (assume 100 g) → moles → ÷ smallest → whole numbers' },
      ],
    },
    {
      id: 'chem-1.4',
      ced: ['1.4'],
      title: 'Composition of Mixtures',
      level: 'core',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'A company claims its supplement is pure. How could you check without seeing the atoms? Measure **how much of one element** a sample contains and compare it to what the pure compound *should* contain.',
        },
        {
          kind: 'concept',
          title: 'Pure substance vs. mixture',
          body: '- **Pure substance**: only one type of atom, molecule or formula unit. Its composition is fixed.\n- **Mixture**: two or more types mixed together, in proportions that **can vary**.\n\nSalt water can be 1% salt or 20% salt. It\'s still salt water. But pure NaCl is *always* 60.7% chlorine by mass.',
        },
        {
          kind: 'concept',
          title: 'Elemental analysis checks purity',
          body: 'Compare the **measured** mass percent of an element with the **theoretical** value for the pure compound:\n\n- They match → the sample is consistent with being pure.\n- They don\'t match → there is something else in the sample.\n\nAnd *which way* it is off tells you what kind of impurity is present!',
        },
        {
          kind: 'example',
          title: 'How pure is the salt?',
          problem: 'A 2.00 g sample contains NaCl plus an impurity that has no chlorine. Analysis finds **0.900 g of Cl**. What percent of the sample is NaCl?',
          steps: [
            'Pure NaCl is 35.45/58.44 = 60.66% Cl by mass.',
            'Mass of NaCl that would contain 0.900 g Cl: 0.900 g × (58.44 g NaCl / 35.45 g Cl) = **1.48 g NaCl**',
            'Percent NaCl = 1.48 ÷ 2.00 × 100 = **74.2%**',
          ],
          answer: 'The sample is about 74.2% NaCl.',
          verify: [
            { stated: 60.66, compute: () => (35.45 / molarMass('NaCl')) * 100 },
            { stated: 1.48, compute: () => (0.9 * molarMass('NaCl')) / 35.45 },
            { stated: 74.2, compute: () => ((0.9 * molarMass('NaCl')) / 35.45 / 2.0) * 100 },
          ],
        },
        {
          kind: 'hack',
          title: 'Too high or too low?',
          body: 'If the measured % of an element is…\n\n- **Higher** than in the pure compound → the impurity contains **more** of that element (by mass %).\n- **Lower** → the impurity contains **less** of it (or none).\n\nThis comparison alone answers a lot of AP multiple-choice questions.',
        },
        {
          kind: 'try',
          question: {
            id: 'c1.4-t1',
            type: 'mcq',
            prompt: 'Pure KCl is 47.6% Cl by mass. A "pure KCl" sample tests at **52.0% Cl**. Which impurity could explain this?',
            choices: ['NaCl (60.7% Cl)', 'KBr (0% Cl)', 'KI (0% Cl)', 'Sand, SiO₂ (0% Cl)'],
            answer: 0,
            hint: 'The measured % is higher than for pure KCl. What impurity would raise it?',
            explain: 'Raising the Cl% above 47.6% needs an impurity with a **higher** Cl% than KCl. Only **NaCl (60.7%)** does that. The others contain no Cl and would *lower* the percentage.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Pure substances have fixed composition. Mixtures can vary.',
            'Compare measured vs. theoretical mass % to judge purity.',
            'Higher % → the impurity is richer in that element. Lower % → it is poorer.',
          ],
        },
      ],
      check: [
        {
          id: 'c1.4-q1',
          type: 'mcq',
          prompt: 'Which is a **mixture**?',
          choices: ['Distilled water', 'Sodium chloride', 'Air', 'Carbon dioxide'],
          answer: 2,
          explain: '**Air** contains N₂, O₂, Ar, CO₂ and more in varying proportions. The others are each a single pure substance.',
        },
        {
          id: 'c1.4-q2',
          type: 'num',
          prompt: 'A 5.00 g sample of impure CaCO₃ contains **1.60 g of calcium**. The impurity contains no Ca. What percent of the sample is CaCO₃? (Ca = 40.08, CaCO₃ = 100.09 g/mol)',
          answer: 79.9,
          unit: '%',
          hint: 'Find the mass of CaCO₃ that contains 1.60 g Ca: 1.60 × (100.09/40.08).',
          explain: '1.60 g Ca × (100.09 g CaCO₃ / 40.08 g Ca) = 4.00 g CaCO₃. Then 4.00/5.00 × 100 = **79.9%**.',
          compute: () => ((1.6 * molarMass('CaCO3')) / 40.078 / 5.0) * 100,
        },
        {
          id: 'c1.4-q3',
          type: 'mcq',
          prompt: 'A sample of pure water and a sample of salt water are analyzed. Which statement is true?',
          choices: [
            'Both always have the same % hydrogen by mass',
            'The % hydrogen in pure water is fixed, but in salt water it depends on how much salt is dissolved',
            'Salt water has a fixed % sodium',
            'Pure water\'s % oxygen depends on where it came from',
          ],
          answer: 1,
          explain: 'Pure water always has fixed composition (definite proportions). Salt water is a mixture, so its composition **varies** with how much salt is dissolved.',
        },
      ],
      flashcards: [
        { front: 'Pure substance vs. mixture?', back: 'Pure: one kind of particle, fixed composition. Mixture: 2+ kinds, variable composition.' },
        { front: 'Measured % of an element is higher than in the pure compound. What does that mean?', back: 'The impurity has a **higher** mass % of that element.' },
      ],
    },
    {
      id: 'chem-1.7',
      ced: ['1.7'],
      title: 'Periodic Trends',
      level: 'core',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'Why is fluorine the greediest element for electrons, and cesium the most generous? Every periodic trend comes down to one tug-of-war between the **nucleus** and the **electrons**.',
        },
        {
          kind: 'concept',
          title: 'Two moves explain every trend',
          body: '**Across a period (→):** protons increase, but the new electrons go into the **same shell**, so the core shielding stays about the same. **Effective nuclear charge rises**, so valence electrons are pulled in tighter.\n\n**Down a group (↓):** each row adds a **new shell**. Valence electrons are **farther away** and **more shielded**, so they are held more loosely.',
          diagram: 'periodic-trends',
        },
        {
          kind: 'concept',
          title: 'The four trends',
          body: '| Property | Across → | Down ↓ |\n| Atomic radius | decreases | increases |\n| Ionization energy | increases | decreases |\n| Electronegativity | increases | decreases |\n| Electron affinity (energy released on gaining an e⁻) | generally more released | generally less released |\n\n**Electronegativity** = how strongly an atom in a **bond** pulls shared electrons. Fluorine is the highest.',
        },
        {
          kind: 'concept',
          title: 'Ion sizes',
          body: '- **Cations are smaller** than their atoms. Losing electrons often removes a whole shell, and the remaining electrons feel more pull. Na⁺ < Na.\n- **Anions are larger** than their atoms. Extra electrons increase repulsion while the nuclear charge stays the same. Cl⁻ > Cl.\n- **Isoelectronic** ions (same number of electrons): **more protons = smaller**. O²⁻ > F⁻ > Na⁺ > Mg²⁺',
        },
        {
          kind: 'hack',
          title: 'Successive ionization energies reveal the group',
          body: 'Removing electrons one by one, the energy climbs gradually until you hit a **core** electron. Then it **jumps hugely**.\n\nThe number of electrons removed **before the big jump** = the number of valence electrons.\nExample: IE₁ = 738, IE₂ = 1451, **IE₃ = 7733** kJ/mol → the jump comes after 2 electrons → a **Group 2** element (this is Mg).',
        },
        {
          kind: 'frq',
          title: 'How to write a trend explanation that earns the point',
          body: 'Use the **"Coulomb sentence"**. Name the particles, the cause and the effect:\n\n❌ "Mg has a higher IE because it\'s farther right."\n✅ "Mg has **more protons** (12 vs. 11) than Na, while its valence electrons are in the **same shell (n = 3)** with similar shielding. The **greater Coulombic attraction** between the nucleus and the valence electrons in Mg means more energy is needed to remove one."\n\nTrends are *where*. Coulomb\'s law is *why*. AP points come from the *why*.',
        },
        {
          kind: 'try',
          question: {
            id: 'c1.7-t1',
            type: 'mcq',
            prompt: 'Which has the **largest radius**: O²⁻, F⁻, Na⁺ or Mg²⁺? (All have 10 electrons.)',
            choices: ['O²⁻', 'F⁻', 'Na⁺', 'Mg²⁺'],
            answer: 0,
            hint: 'Same electrons, so compare protons. Fewer protons = weaker pull = bigger ion.',
            explain: 'All four have 10 electrons. O²⁻ has the fewest protons (8), so its electrons feel the weakest pull and spread out the most. **O²⁻ is largest.**',
          },
        },
        {
          kind: 'trap',
          body: 'Don\'t explain trends with "atoms want a full octet." That isn\'t accepted as a reason on AP free response. Always use **protons/nuclear charge, distance (shells) and shielding**.',
        },
        {
          kind: 'summary',
          points: [
            'Across: more protons, same shell → stronger pull → smaller radius, higher IE and EN.',
            'Down: more shells, more shielding → weaker pull → bigger radius, lower IE and EN.',
            'A big jump in successive IEs means you have reached the core electrons.',
          ],
        },
      ],
      check: [
        {
          id: 'c1.7-q1',
          type: 'mcq',
          prompt: 'Which element has the **highest first ionization energy**?',
          choices: ['Na', 'Al', 'P', 'Cl'],
          answer: 3,
          hint: 'They\'re all in period 3. IE increases across a period.',
          explain: 'Moving right across period 3, nuclear charge increases with the same shell, so **Cl** holds its valence electrons most tightly.',
        },
        {
          id: 'c1.7-q2',
          type: 'mcq',
          prompt: 'Why is the atomic radius of K **larger** than that of Na?',
          choices: [
            'K has more protons, which pushes electrons away',
            'K\'s valence electron is in a higher shell (n = 4), farther from the nucleus and more shielded',
            'K has fewer neutrons',
            'K has a full octet',
          ],
          answer: 1,
          explain: 'K\'s valence electron is in the **n = 4** shell (Na\'s is in n = 3). It is farther from the nucleus and shielded by more core electrons, so the atom is larger.',
        },
        {
          id: 'c1.7-q3',
          type: 'mcq',
          prompt: 'An element\'s successive ionization energies (kJ/mol) are 578, 1817, 2745, **11,577**. Which group is it in?',
          choices: ['Group 1', 'Group 2', 'Group 13', 'Group 15'],
          answer: 2,
          hint: 'How many electrons come off before the huge jump?',
          explain: 'The big jump comes after the 3rd electron, so it has **3 valence electrons → Group 13** (these values are for aluminum).',
        },
        {
          id: 'c1.7-q4',
          type: 'mcq',
          prompt: 'Which atom has the **greatest electronegativity**?',
          choices: ['O', 'N', 'S', 'F'],
          answer: 3,
          explain: '**Fluorine** is the most electronegative element. It\'s at the top right of the table (ignoring noble gases).',
        },
      ],
      flashcards: [
        { front: 'Atomic radius trend', back: 'Decreases across a period, increases down a group.' },
        { front: 'Ionization energy trend', back: 'Increases across a period, decreases down a group.' },
        { front: 'Isoelectronic ions: which is smallest?', back: 'The one with the **most protons**.' },
        { front: 'Why does IE increase across a period?', back: 'More protons, same shell (similar shielding) → greater effective nuclear charge → stronger Coulombic attraction.' },
        { front: 'Electronegativity', back: 'How strongly an atom in a bond attracts the shared electrons. F is highest.' },
      ],
    },
    {
      id: 'chem-1.8',
      ced: ['1.8'],
      title: 'Valence Electrons & Ionic Compounds',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'If you know the formula of table salt (NaCl), you can predict the formula of a compound you\'ve never seen, like rubidium iodide. The periodic table is a pattern machine!',
        },
        {
          kind: 'concept',
          title: 'Valence electrons decide bonding',
          body: 'Whether two elements form a bond depends on how their **valence electrons** interact with each other\'s **nuclei**.\n\n- Metals on the left have few valence electrons and low ionization energy. They lose electrons easily → **cations**.\n- Nonmetals on the right have high electronegativity. They gain electrons → **anions**.\n- Metal + nonmetal → usually an **ionic compound**.',
        },
        {
          kind: 'concept',
          title: 'Same column → same kind of compound',
          body: 'Elements in the same group have the same number of valence electrons, so they form **analogous compounds**:\n\n- NaCl, KCl, NaBr, KI (Group 1 + Group 17 → 1 : 1)\n- MgO, CaO, CaS (Group 2 + Group 16 → 1 : 1)\n- H₂O and H₂S (Group 16 + H)\n\n**Typical charges:** Group 1 → +1, Group 2 → +2, Group 13 → +3 (Al³⁺), Group 15 → −3, Group 16 → −2, Group 17 → −1.',
        },
        {
          kind: 'example',
          title: 'Predict the formula',
          problem: 'Aluminum and oxygen form **Al₂O₃**. Predict the formula of the compound formed by **gallium and sulfur**.',
          steps: ['Ga is directly below Al (Group 13), and S is directly below O (Group 16).', 'Analogous elements form analogous compounds, so the answer is **Ga₂S₃**.'],
          answer: 'Ga₂S₃',
        },
        {
          kind: 'try',
          question: {
            id: 'c1.8-t1',
            type: 'mcq',
            prompt: 'Which is the most likely formula for a compound of **lithium and selenium**?',
            choices: ['LiSe', 'Li₂Se', 'LiSe₂', 'Li₃Se₂'],
            answer: 1,
            hint: 'Li is Group 1 (+1). Se is Group 16 (−2).',
            explain: 'Li⁺ and Se²⁻: two Li⁺ balance one Se²⁻ → **Li₂Se** (just like Na₂O).',
          },
        },
        {
          kind: 'summary',
          points: [
            'Valence electron–nucleus interactions decide whether atoms bond.',
            'Same group → analogous compounds (NaCl ↔ KBr).',
            'Predict charges from position: +1, +2, +3 … −3, −2, −1.',
          ],
        },
      ],
      check: [
        {
          id: 'c1.8-q1',
          type: 'mcq',
          prompt: 'Calcium forms CaCl₂. What is the most likely formula of **strontium bromide**?',
          choices: ['SrBr', 'SrBr₂', 'Sr₂Br', 'SrBr₃'],
          answer: 1,
          explain: 'Sr is in the same group as Ca, and Br is in the same group as Cl. Analogous compound: **SrBr₂**.',
        },
        {
          id: 'c1.8-q2',
          type: 'mcq',
          prompt: 'Which pair would most likely form an **ionic** compound?',
          choices: ['C and O', 'K and F', 'N and H', 'S and O'],
          answer: 1,
          hint: 'Look for a metal + nonmetal pair with very different electronegativities.',
          explain: '**K** (a metal with low IE) + **F** (the most electronegative nonmetal) → ionic KF. The other pairs are nonmetal + nonmetal, so they are covalent.',
        },
        {
          id: 'c1.8-q3',
          type: 'mcq',
          prompt: 'What charge does nitrogen typically have in ionic compounds such as Li₃N?',
          choices: ['+3', '+5', '−3', '−5'],
          answer: 2,
          explain: 'N is in Group 15 with 5 valence electrons. It gains 3 to reach a noble-gas configuration → **N³⁻**. Check: 3 Li⁺ balance one N³⁻.',
        },
      ],
      flashcards: [
        { front: 'Why do elements in the same group form similar compounds?', back: 'They have the same number of **valence electrons**.' },
        { front: 'Typical ion charges by group', back: '1: +1 · 2: +2 · 13: +3 · 15: −3 · 16: −2 · 17: −1' },
      ],
    },
    // ---------------- ADVANCED ----------------
    {
      id: 'chem-1.6',
      ced: ['1.6'],
      title: 'Photoelectron Spectroscopy (PES)',
      level: 'advanced',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'How do we *know* electrons sit in subshells like 1s, 2s and 2p? We shine high-energy light on atoms, knock electrons out, and measure how hard each one was to remove. That technique is **PES**, and it gives a fingerprint of the electron configuration.',
        },
        {
          kind: 'concept',
          title: 'Reading a PES spectrum',
          body: '- Each **peak** = one **subshell**.\n- Peak **position** = **binding energy**, the energy needed to remove an electron from that subshell. Higher = held more tightly = closer to the nucleus.\n- Peak **height** ∝ the **number of electrons** in that subshell.\n\nBy convention, binding energy usually **increases to the left**. So the core 1s peak is far left and valence electrons are on the right.',
          diagram: 'pes-na',
        },
        {
          kind: 'hack',
          title: 'Decode any PES in 3 steps',
          body: '1. Count peaks from **high energy to low**: 1s, 2s, 2p, 3s, 3p, 4s, 3d…\n2. Read the relative heights as electron counts. s peaks = 2 max, p = 6 max, d = 10 max.\n3. Add them up to get the total electrons, which (for a neutral atom) equals the atomic number.\n\nExample: heights 2 : 2 : 6 : 1 → 1s² 2s² 2p⁶ 3s¹ = 11 e⁻ = **sodium**.',
        },
        {
          kind: 'concept',
          title: 'Comparing two elements',
          body: 'The **same subshell** in a different element sits at a different energy:\n\nThe 1s peak of **F** is at a higher binding energy than the 1s peak of **O**, because F has **more protons** (9 vs. 8). The greater nuclear charge pulls those 1s electrons more strongly (Coulomb\'s law).\n\nSo bigger Z → every peak shifts to **higher binding energy**.',
        },
        {
          kind: 'try',
          question: {
            id: 'c1.6-t1',
            type: 'mcq',
            prompt: 'A PES spectrum has three peaks with relative heights **2 : 2 : 3**. Which element is it?',
            choices: ['Lithium', 'Boron', 'Nitrogen', 'Neon'],
            answer: 2,
            hint: 'Three peaks = 1s, 2s, 2p. Add up the electrons.',
            explain: '1s² 2s² 2p³ = 7 electrons → **nitrogen**.',
          },
        },
        {
          kind: 'frq',
          body: 'To explain why one peak is at higher energy, use Coulomb\'s law with specifics: "The 1s electrons are **closer to the nucleus** than the 2s electrons, so they experience a **stronger attraction** and require **more energy** to remove." Name the subshells and connect distance or charge to attraction to energy.',
        },
        {
          kind: 'trap',
          body: 'A taller peak does **not** mean higher energy. Height = how many electrons are there. Position = how tightly they\'re held. Those are two different questions!',
        },
        {
          kind: 'summary',
          points: [
            'Peak position = binding energy (how tightly held). Peak height = number of electrons.',
            'Read the peaks in order (1s, 2s, 2p…) to rebuild the electron configuration.',
            'More protons → the same subshell has a higher binding energy.',
          ],
        },
      ],
      check: [
        {
          id: 'c1.6-q1',
          type: 'mcq',
          prompt: 'In the PES of sodium, which peak has the **lowest binding energy**?',
          choices: ['1s', '2s', '2p', '3s'],
          answer: 3,
          hint: 'Which electron is farthest from the nucleus?',
          explain: 'The single **3s** electron is the farthest from the nucleus and the most shielded, so it\'s easiest to remove (about 0.50 MJ/mol).',
        },
        {
          id: 'c1.6-q2',
          type: 'mcq',
          prompt: 'In the PES of sodium, the 2p peak is about **three times taller** than the 2s peak because…',
          choices: [
            '2p electrons are held three times more tightly',
            '2p contains 6 electrons and 2s contains 2',
            '2p electrons are farther from the nucleus',
            '2p has three times more energy',
          ],
          answer: 1,
          explain: 'Peak height ∝ number of electrons: **2p⁶ has 6 electrons vs. 2s² with 2**, a 3 : 1 ratio.',
        },
        {
          id: 'c1.6-q3',
          type: 'mcq',
          prompt: 'The 1s peak of **Mg** appears at a higher binding energy than the 1s peak of **Na**. Why?',
          choices: [
            'Mg has more electrons in its 1s subshell',
            'Mg has more protons, so its 1s electrons feel a stronger Coulombic attraction',
            'Mg\'s 1s electrons are farther from the nucleus',
            'Mg is a metal and Na is not',
          ],
          answer: 1,
          explain: 'Both have 1s², but Mg has **12 protons vs. 11**. The greater nuclear charge attracts the 1s electrons more strongly, so more energy is needed to remove them.',
        },
      ],
      flashcards: [
        { front: 'PES: what does peak height tell you?', back: 'The relative **number of electrons** in that subshell.' },
        { front: 'PES: what does peak position tell you?', back: '**Binding energy**: how much energy is needed to remove an electron from that subshell.' },
        { front: 'Why is an element\'s 1s binding energy higher than the previous element\'s?', back: 'More protons → stronger attraction to the 1s electrons.' },
      ],
    },
  ],
  checkpoint: [
    {
      id: 'c1-cp1',
      type: 'num',
      prompt: 'How many moles of atoms are in **4.00 g of helium**? (He = 4.00)',
      answer: 1.0,
      unit: 'mol',
      explain: 'n = m/M = 4.00 ÷ 4.00 = **1.00 mol**',
      compute: () => 4.0 / 4.0026,
    },
    {
      id: 'c1-cp2',
      type: 'mcq',
      prompt: 'Which ion has the electron configuration **[Ar] 3d¹⁰**?',
      choices: ['Zn²⁺', 'Cu²⁺', 'Ga⁺', 'Ni²⁺'],
      answer: 0,
      explain: 'Zn = [Ar] 4s² 3d¹⁰. Removing the two 4s electrons gives **Zn²⁺ = [Ar] 3d¹⁰**. (Cu²⁺ is [Ar] 3d⁹, and Ni²⁺ is [Ar] 3d⁸.)',
    },
    {
      id: 'c1-cp3',
      type: 'mcq',
      prompt: 'Which statement best explains why the first ionization energy of **Cl is greater than that of S**?',
      choices: [
        'Cl has a full octet',
        'Cl has one more proton while adding its electron to the same shell, so its valence electrons feel a greater effective nuclear charge',
        'Cl has more neutrons',
        'Cl is a gas and S is a solid',
      ],
      answer: 1,
      explain: 'Same shell (n = 3), similar shielding, but Cl has **more protons** (17 vs. 16) → stronger Coulombic attraction → higher IE.',
    },
    {
      id: 'c1-cp4',
      type: 'num',
      prompt: 'What is the mass percent of **N** in NH₄NO₃? (N = 14.01, H = 1.008, O = 16.00)',
      answer: 35.0,
      unit: '%',
      tolerance: 0.01,
      explain: 'M = 2(14.01) + 4(1.008) + 3(16.00) = 80.05 g/mol. %N = 28.02/80.05 × 100 = **35.0%**',
      compute: () => ((2 * 14.007) / molarMass('NH4NO3')) * 100,
    },
    {
      id: 'c1-cp5',
      type: 'mcq',
      prompt: 'Which correctly ranks the radii from smallest to largest?',
      choices: ['Na < Mg < Al', 'Na < Al < Mg', 'Mg²⁺ < Na⁺ < F⁻', 'F⁻ < Na⁺ < Mg²⁺'],
      answer: 2,
      explain: 'Mg²⁺, Na⁺ and F⁻ are isoelectronic (10 e⁻). More protons = smaller, so **Mg²⁺ (12 p) < Na⁺ (11 p) < F⁻ (9 p)**. For the atoms, radius decreases across period 3, so the correct order would be Al < Mg < Na, and neither atom choice matches it.',
    },
  ],
}
