import type { Unit } from '../types'

export const unit2: Unit = {
  id: 'chem-u2',
  number: 2,
  title: 'Compound Structure and Properties',
  weight: '7–9%',
  blurb: 'How atoms hold together: ionic, covalent and metallic bonds, Lewis diagrams, and the 3-D shapes of molecules.',
  badge: { name: 'Bond Builder', emoji: '🔗' },
  lessons: [
    // ---------------- FOUNDATION ----------------
    {
      id: 'chem-2.1',
      ced: ['2.1'],
      title: 'Types of Chemical Bonds',
      level: 'foundation',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'Salt shatters, copper bends, and wax melts in your hand. All three are made of atoms stuck together, so why are they so different? The answer is **how** the atoms share or trade their electrons.',
        },
        {
          kind: 'concept',
          title: 'A tug-of-war for electrons',
          body: 'Every bond is a tug-of-war between two atoms over the shared valence electrons. **Electronegativity (EN)** measures how hard an atom pulls.\n\n| Bond type | Who\'s pulling? | Example |\n| **Nonpolar covalent** | Similar EN, so electrons are shared equally | Cl–Cl, C–H |\n| **Polar covalent** | Unequal EN, so electrons are shared unequally | H–Cl, O–H |\n| **Ionic** | Very unequal (usually metal + nonmetal), so electrons are essentially transferred | Na⁺Cl⁻ |\n\nC–H bonds count as **effectively nonpolar**, even though C is slightly more electronegative than H.',
        },
        {
          kind: 'concept',
          title: 'Partial charges (δ+ and δ−)',
          body: 'In a polar bond, the **more electronegative** atom gets a **partial negative** charge (δ−) and the other atom gets δ+.\n\n**H**^{δ+}–**Cl**^{δ−}\n\nThe bigger the EN difference in a single bond, the bigger the **bond dipole**. There\'s no sharp line between "polar covalent" and "ionic". It\'s a **continuum**, and every polar bond has some ionic character.',
        },
        {
          kind: 'concept',
          title: 'Metallic bonding',
          body: 'In a metal, the valence electrons aren\'t owned by any single atom. They are **delocalized** and roam freely among positive metal ions: a **"sea of electrons."**\n\nThat\'s why metals conduct electricity and can be bent or hammered into shape.',
        },
        {
          kind: 'hack',
          title: 'Quick bond-type sorter',
          body: '- **Metal + nonmetal** → usually **ionic**\n- **Nonmetal + nonmetal** → **covalent** (polar if the ENs differ)\n- **Metal + metal** → **metallic**\n\nAP fine print: EN difference isn\'t the *only* factor. The best evidence of bond type is the compound\'s **properties**. For example, ionic solids conduct electricity when melted or dissolved, and molecular substances don\'t.',
        },
        {
          kind: 'try',
          question: {
            id: 'c2.1-t1',
            type: 'mcq',
            prompt: 'In an **O–H** bond, which atom carries the partial negative charge?',
            choices: ['H, because it\'s smaller', 'O, because it\'s more electronegative', 'Neither: the bond is nonpolar', 'Both share it equally'],
            answer: 1,
            hint: 'The atom that pulls the shared electrons harder ends up with more of them.',
            explain: 'O is much more electronegative than H, so the shared electrons spend more time near O: **O^{δ−}–H^{δ+}**.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Nonpolar covalent = equal sharing. Polar covalent = unequal sharing. Ionic = essentially a transfer.',
            'The more electronegative atom is δ−. A bigger EN difference means a bigger dipole.',
            'Metallic bonding = cations in a sea of delocalized electrons.',
          ],
        },
      ],
      check: [
        {
          id: 'c2.1-q1',
          type: 'mcq',
          prompt: 'Which bond is the **most polar**?',
          choices: ['C–H', 'N–H', 'O–H', 'F–H'],
          answer: 3,
          hint: 'Look for the biggest electronegativity difference from H.',
          explain: 'F is the most electronegative element, so **F–H** has the largest EN difference and the biggest bond dipole.',
        },
        {
          id: 'c2.1-q2',
          type: 'mcq',
          prompt: 'A solid melts at 801 °C and conducts electricity **only when melted or dissolved in water**. What kind of bonding does it most likely have?',
          choices: ['Nonpolar covalent', 'Metallic', 'Ionic', 'Hydrogen bonding'],
          answer: 2,
          explain: 'Ionic solids have high melting points. Their ions can\'t move in the solid, but they **can** move (and conduct) when melted or dissolved. Those are classic **ionic** properties (the data are for NaCl).',
        },
        {
          id: 'c2.1-q3',
          type: 'mcq',
          prompt: 'Which best describes the bonding in solid copper?',
          choices: [
            'Cu⁺ and Cu⁻ ions in a lattice',
            'Covalent bonds between pairs of Cu atoms',
            'Cu cations surrounded by delocalized valence electrons',
            'Hydrogen bonds between Cu atoms',
          ],
          answer: 2,
          explain: 'Metallic bonding = positive metal ions in a **sea of delocalized electrons**. That\'s why copper conducts electricity so well.',
        },
      ],
      flashcards: [
        { front: 'Polar covalent bond', back: 'Electrons are shared **unequally** between atoms with different electronegativities. The more EN atom is δ−.' },
        { front: 'Metallic bonding model', back: 'Metal cations in a "sea" of **delocalized** valence electrons.' },
        { front: 'Is the line between ionic and polar covalent sharp?', back: 'No. It\'s a **continuum**. All polar bonds have some ionic character.' },
      ],
    },
    {
      id: 'chem-2.5',
      ced: ['2.5'],
      title: 'Lewis Diagrams',
      level: 'foundation',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'A Lewis diagram is a **map of a molecule\'s valence electrons**. Once you can draw one, you can predict its shape, polarity, and even its boiling point. It\'s the most-used drawing in the whole course!',
        },
        {
          kind: 'concept',
          title: 'The 5-step recipe',
          body: '1. **Count** the total valence electrons. Add one for each negative charge and subtract one for each positive charge.\n2. **Skeleton:** put the least electronegative atom in the center (never H, since H only forms one bond). Connect the atoms with single bonds (2 e⁻ each).\n3. **Outer atoms first:** give each outer atom a full octet (H gets just 2).\n4. **Leftovers** go on the central atom as lone pairs.\n5. **Central atom short of an octet?** Turn lone pairs from the outer atoms into double or triple bonds.',
        },
        {
          kind: 'example',
          title: 'Carbon dioxide, CO₂',
          problem: 'Draw the Lewis diagram for **CO₂**.',
          steps: [
            'Valence electrons: C = 4, O = 6 × 2 = 12 → **16 e⁻**.',
            'Skeleton O–C–O uses 4 e⁻, leaving 12. Give each O three lone pairs (6 e⁻ each) → all 12 used.',
            'C has only 4 electrons around it, so move one lone pair from each O into a bond → **O=C=O**.',
            'Check: each atom has 8 electrons, and the total is still 16 ✓',
          ],
          answer: 'O=C=O, with two lone pairs on each O and none on C.',
        },
        {
          kind: 'concept',
          title: 'Bending the octet rule',
          body: 'The octet rule is a **model**, and it has exceptions:\n\n- **Fewer than 8:** B in BF₃ has 6 electrons. (H always has 2.)\n- **More than 8:** atoms in **period 3 or below** can have expanded octets: S in SF₆ (12 e⁻), P in PCl₅ (10 e⁻), Xe in XeF₄.\n- **Odd number of electrons:** NO has 11 valence electrons, so someone can\'t have an octet. The Lewis model has **limitations** with odd-electron species.',
        },
        {
          kind: 'hack',
          title: 'Count bonds: the "HONC 1234" rule',
          body: 'In neutral organic-style molecules, atoms usually make this many bonds:\n\n**H = 1, O = 2, N = 3, C = 4**\n\nIf your drawing gives carbon 5 bonds or oxygen 3, recheck it, or expect a formal charge (next lessons).',
        },
        {
          kind: 'try',
          question: {
            id: 'c2.5-t1',
            type: 'mcq',
            prompt: 'How many **total valence electrons** are in the nitrate ion, NO₃⁻?',
            choices: ['22', '23', '24', '25'],
            answer: 2,
            hint: 'N = 5, O = 6 each, and don\'t forget the charge.',
            explain: '5 + 3(6) = 23, plus 1 for the negative charge = **24** valence electrons.',
          },
        },
        {
          kind: 'trap',
          body: 'Forgetting the charge on ions is the #1 Lewis mistake. **Negative = add electrons, positive = subtract.** For example, NH₄⁺ has 5 + 4 − 1 = 8 e⁻.',
        },
        {
          kind: 'summary',
          points: [
            'Count the valence e⁻ (adjust for charge) → skeleton → outer octets → leftovers → make multiple bonds if needed.',
            'The least electronegative atom goes in the center (never H).',
            'Exceptions: BF₃ (6 e⁻ on B), expanded octets in period 3+, odd-electron molecules.',
          ],
        },
      ],
      check: [
        {
          id: 'c2.5-q1',
          type: 'mcq',
          prompt: 'In the Lewis diagram of **NH₃**, how many lone pairs are on N?',
          choices: ['0', '1', '2', '3'],
          answer: 1,
          hint: '8 valence e⁻ total. Three N–H bonds use 6.',
          explain: '5 + 3(1) = 8 e⁻. Three bonds use 6, leaving 2 → **1 lone pair** on N.',
        },
        {
          id: 'c2.5-q2',
          type: 'mcq',
          prompt: 'The best Lewis diagram of **N₂** has…',
          choices: ['a single bond', 'a double bond', 'a triple bond', 'no bond, just lone pairs'],
          answer: 2,
          hint: '10 valence e⁻ total. Each N needs an octet.',
          explain: '10 e⁻: :N≡N:. A **triple bond** (6 e⁻) plus one lone pair on each N gives both atoms an octet.',
        },
        {
          id: 'c2.5-q3',
          type: 'mcq',
          prompt: 'Which molecule has a central atom with an **expanded octet**?',
          choices: ['CH₄', 'NH₃', 'PCl₅', 'BF₃'],
          answer: 2,
          explain: 'P (period 3) forms 5 bonds in PCl₅ → **10 electrons** around P. BF₃ is the opposite case (only 6 e⁻ around B).',
        },
      ],
      flashcards: [
        { front: 'Lewis diagram first step', back: 'Count the total valence electrons (add e⁻ for − charge, subtract for + charge).' },
        { front: 'Which atoms can have expanded octets?', back: 'Atoms in **period 3 or below** (e.g., P, S, Cl, Xe).' },
        { front: 'HONC 1234', back: 'Usual bond counts: H 1, O 2, N 3, C 4.' },
      ],
    },
    // ---------------- CORE ----------------
    {
      id: 'chem-2.2',
      ced: ['2.2'],
      title: 'Bonds & Potential Energy',
      level: 'core',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'Myth buster: **breaking a bond never releases energy.** Breaking bonds always *costs* energy. Energy is released when bonds *form*. Graphs of potential energy make this crystal clear.',
        },
        {
          kind: 'concept',
          title: 'The potential energy curve',
          body: 'Bring two H atoms together and track the energy:\n\n- **Far apart:** no interaction, so energy = 0.\n- **Closer:** attraction (nucleus to the other atom\'s electron) lowers the energy.\n- **Too close:** the two nuclei repel, so the energy shoots up.\n\nThe **bottom of the well** is the most stable distance: that\'s the **bond length**. The **depth** of the well is the **bond energy**, the energy needed to pull the atoms apart.',
          diagram: 'pe-curve-h2',
        },
        {
          kind: 'concept',
          title: 'Bond order: single, double, triple',
          body: 'More shared electron pairs → atoms pulled **closer** and held **tighter**:\n\n| Bond | Length | Energy (approx.) |\n| C–C | 154 pm | 347 kJ/mol |\n| C=C | 134 pm | 614 kJ/mol |\n| C≡C | 120 pm | 839 kJ/mol |\n\n**Higher bond order → shorter and stronger.** Bond length also depends on atom size: bigger atoms (bigger cores) make longer bonds, so H–I is longer than H–F.',
        },
        {
          kind: 'concept',
          title: 'Coulomb\'s law for ionic bonds',
          body: 'The attraction between a cation and an anion grows with:\n\n1. **Bigger charges.** Mg²⁺O²⁻ is held far more strongly than Na⁺Cl⁻.\n2. **Smaller ions**, which let the nuclei get closer. NaF is held more strongly than NaI.\n\n**Charge usually matters most.** It\'s the first thing to compare, then size.',
        },
        {
          kind: 'hack',
          title: 'Which ionic compound melts higher?',
          body: 'Step 1: compare the **product of the charges**. Bigger wins.\nStep 2: if the charges tie, compare **ion sizes**. Smaller ions win.\n\nMgO (2 × 2 = 4) > NaCl (1 × 1 = 1). And NaF > NaCl > NaBr > NaI, because the anion gets bigger down the group.',
        },
        {
          kind: 'try',
          question: {
            id: 'c2.2-t1',
            type: 'mcq',
            prompt: 'Which has the **strongest** attraction between its ions?',
            choices: ['KCl', 'NaCl', 'CaO', 'KBr'],
            answer: 2,
            hint: 'Compare charges first.',
            explain: '**CaO** has 2+ and 2− ions. All the others are 1+/1−. Bigger charges → much stronger Coulombic attraction.',
          },
        },
        {
          kind: 'frq',
          body: 'For "explain using Coulomb\'s law" questions, name the **charges**, the **distance (ion size)** and the **result**: "Mg²⁺ has a greater charge than Na⁺ and a smaller radius, so the Coulombic attraction between Mg²⁺ and O²⁻ is greater, giving MgO a higher melting point."',
        },
        {
          kind: 'summary',
          points: [
            'On the potential energy curve: well bottom = bond length, well depth = bond energy.',
            'Breaking bonds costs energy. Forming bonds releases it.',
            'Higher bond order → shorter, stronger bonds. Ionic strength: bigger charges and smaller ions.',
          ],
        },
      ],
      check: [
        {
          id: 'c2.2-q1',
          type: 'mcq',
          prompt: 'On a potential energy vs. distance graph for a diatomic molecule, the **bond length** is located at…',
          choices: ['the largest distance shown', 'the point where energy = 0', 'the minimum of the curve', 'the point where the curve is steepest'],
          answer: 2,
          explain: 'The **minimum** (lowest energy) marks the most stable separation, which is the bond length.',
        },
        {
          id: 'c2.2-q2',
          type: 'mcq',
          prompt: 'Rank the bonds from **shortest to longest**: C=O, C–O, C≡O',
          choices: ['C–O < C=O < C≡O', 'C≡O < C=O < C–O', 'C=O < C≡O < C–O', 'They\'re all the same length'],
          answer: 1,
          explain: 'Higher bond order → shorter bond. Triple < double < single: **C≡O < C=O < C–O**.',
        },
        {
          id: 'c2.2-q3',
          type: 'mcq',
          prompt: 'Which compound has the **higher melting point**, and why?',
          choices: [
            'NaI, because I⁻ is larger',
            'NaF, because F⁻ is smaller so the ions are closer, giving stronger attraction',
            'They are equal because the charges are equal',
            'NaI, because it has more electrons',
          ],
          answer: 1,
          explain: 'Same charges (1+/1−), so compare size. F⁻ is much smaller than I⁻, so the ions are closer → stronger Coulombic attraction → **NaF** melts higher (993 °C vs. 661 °C).',
        },
      ],
      flashcards: [
        { front: 'Bond energy (from the PE curve)', back: 'The **depth** of the well: the energy needed to separate the atoms.' },
        { front: 'Effect of bond order on length and energy', back: 'Higher bond order → **shorter** and **stronger**.' },
        { front: 'Two factors in ionic bond strength', back: '1) Charge (bigger = stronger) 2) Ion size (smaller = stronger)' },
      ],
    },
    {
      id: 'chem-2.3',
      ced: ['2.3'],
      title: 'Structure of Ionic Solids',
      level: 'core',
      minutes: 5,
      cards: [
        {
          kind: 'hook',
          body: 'Look at salt under a magnifying glass and you\'ll see tiny **cubes**. That shape comes straight from how the ions stack, a pattern repeated trillions of times.',
        },
        {
          kind: 'concept',
          title: 'A 3-D checkerboard',
          body: 'In an ionic crystal, cations and anions are arranged in a **systematic, repeating 3-D pattern (a lattice)** that:\n\n- **maximizes attractions** (each ion is surrounded by ions of the *opposite* charge)\n- **minimizes repulsions** (ions with the *same* charge are kept apart)',
          diagram: 'ionic-lattice',
        },
        {
          kind: 'concept',
          title: 'Structure explains properties',
          body: '| Property | Why |\n| High melting point | Strong attractions throughout the whole lattice |\n| Hard but **brittle** | Shift one layer and like charges line up, so they repel and the crystal cracks |\n| Doesn\'t conduct as a solid | Ions are locked in place |\n| Conducts when melted or dissolved | Ions are free to move |',
        },
        {
          kind: 'hack',
          title: 'Drawing particle diagrams',
          body: 'When you draw an ionic solid on the AP exam:\n\n- **Alternate** + and − ions so no two like charges touch.\n- Draw ions in **reasonable relative sizes**. Usually anions are bigger than cations (Cl⁻ is bigger than Na⁺).\n- Keep the **ratio** right. For CaCl₂, draw twice as many Cl⁻ as Ca²⁺.\n\nYou don\'t need to memorize specific crystal structures. That\'s excluded from the exam.',
        },
        {
          kind: 'try',
          question: {
            id: 'c2.3-t1',
            type: 'mcq',
            prompt: 'Why are ionic crystals **brittle**?',
            choices: [
              'The electrons are delocalized',
              'Shifting a layer brings ions of the same charge next to each other, and they repel',
              'Ionic bonds are weaker than covalent bonds',
              'The ions are too small',
            ],
            answer: 1,
            explain: 'A sharp blow shifts the layers so **like charges line up**. The strong repulsion splits the crystal apart.',
          },
        },
        {
          kind: 'summary',
          points: [
            'An ionic lattice maximizes +/− attractions and minimizes like-charge repulsions.',
            'High melting point, brittle, conducts only when ions can move (melted or dissolved).',
          ],
        },
      ],
      check: [
        {
          id: 'c2.3-q1',
          type: 'mcq',
          prompt: 'In a particle diagram of solid NaCl, each Na⁺ should be surrounded mostly by…',
          choices: ['other Na⁺ ions', 'Cl⁻ ions', 'free electrons', 'water molecules'],
          answer: 1,
          explain: 'Each ion is surrounded by ions of the **opposite** charge (Cl⁻) to maximize attractions.',
        },
        {
          id: 'c2.3-q2',
          type: 'mcq',
          prompt: 'Solid KBr does not conduct electricity, but molten KBr does. Why?',
          choices: [
            'Melting creates free electrons',
            'In the liquid, the K⁺ and Br⁻ ions are free to move',
            'Melting turns KBr into a metal',
            'Molten KBr contains water',
          ],
          answer: 1,
          explain: 'Conduction needs **mobile charged particles**. In the solid the ions are locked in the lattice. In the liquid they can move.',
        },
      ],
      flashcards: [
        { front: 'How are ions arranged in an ionic solid?', back: 'A repeating 3-D lattice that maximizes attractions and minimizes repulsions.' },
        { front: 'When do ionic compounds conduct electricity?', back: 'When **melted or dissolved**, because the ions can move.' },
      ],
    },
    {
      id: 'chem-2.4',
      ced: ['2.4'],
      title: 'Metals & Alloys',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'Pure iron is fairly soft. Add a little carbon and you get **steel**, strong enough for skyscrapers. Add zinc to copper and you get **brass** for trumpets. Mixing metals at the atomic level changes everything.',
        },
        {
          kind: 'concept',
          title: 'The electron-sea model',
          body: 'A metal is an array of **positive metal ions** in a **sea of delocalized valence electrons**.\n\n- **Conducts electricity and heat:** the electrons are free to move.\n- **Malleable and ductile:** layers of cations can slide past each other, and the electron sea still holds them together. No like-charge clash, unlike ionic solids!',
          diagram: 'alloys',
        },
        {
          kind: 'concept',
          title: 'Two kinds of alloys',
          body: '**Substitutional alloy:** atoms of **similar size** *replace* host atoms in the lattice.\n→ Brass: zinc atoms substitute for some copper atoms.\n\n**Interstitial alloy:** **much smaller** atoms fit into the *gaps* (interstices) between host atoms.\n→ Steel: small carbon atoms sit between iron atoms.',
        },
        {
          kind: 'hack',
          title: 'Size decides the type',
          body: '**Similar radii → Substitutional** ("swap places")\n**Very different radii → Interstitial** ("in the gaps")\n\nInterstitial alloys are usually **harder and less malleable**, because the small atoms jam the layers so they can\'t slide as easily.',
        },
        {
          kind: 'try',
          question: {
            id: 'c2.4-t1',
            type: 'mcq',
            prompt: 'Boron atoms are much smaller than iron atoms. A boron–iron alloy is most likely…',
            choices: ['substitutional', 'interstitial', 'ionic', 'a molecular solid'],
            answer: 1,
            hint: 'Very different sizes: where can the small atom fit?',
            explain: 'The small boron atoms fit into the **gaps** between the larger Fe atoms → **interstitial** alloy.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Metal = cations + a sea of delocalized electrons → conductive and malleable.',
            'Substitutional alloy: similar sizes swap (brass). Interstitial: small atoms in the gaps (steel).',
            'Interstitial alloys are typically harder and less malleable.',
          ],
        },
      ],
      check: [
        {
          id: 'c2.4-q1',
          type: 'mcq',
          prompt: 'Why can metals be hammered into sheets without shattering?',
          choices: [
            'Their ions have no charge',
            'Layers of cations can slide while the delocalized electrons keep holding them together',
            'Metals have very weak bonds',
            'They contain covalent bonds that stretch',
          ],
          answer: 1,
          explain: 'In the electron-sea model, shifting layers doesn\'t bring like charges into conflict. The **delocalized electrons** keep bonding the cations together.',
        },
        {
          id: 'c2.4-q2',
          type: 'mcq',
          prompt: 'Brass is made of copper and zinc atoms, which have similar radii. Brass is a(n)…',
          choices: ['interstitial alloy', 'substitutional alloy', 'ionic compound', 'network covalent solid'],
          answer: 1,
          explain: 'Similar-sized atoms **replace** each other in the lattice → **substitutional** alloy.',
        },
        {
          id: 'c2.4-q3',
          type: 'mcq',
          prompt: 'Compared with pure iron, steel (an interstitial alloy with carbon) is…',
          choices: ['softer and more malleable', 'harder and less malleable', 'a better electrical insulator', 'liquid at room temperature'],
          answer: 1,
          explain: 'The carbon atoms in the gaps make it harder for layers of Fe to slide, so steel is **harder and less malleable**.',
        },
      ],
      flashcards: [
        { front: 'Substitutional alloy', back: 'Atoms of **similar size** replace host atoms (e.g., brass: Zn in Cu).' },
        { front: 'Interstitial alloy', back: '**Smaller** atoms fill gaps between host atoms (e.g., steel: C in Fe). Harder, less malleable.' },
      ],
    },
    {
      id: 'chem-2.7a',
      ced: ['2.7'],
      title: 'VSEPR: Shapes of Molecules',
      level: 'core',
      minutes: 10,
      cards: [
        {
          kind: 'hook',
          body: 'Why is water bent instead of straight? If it were straight, it would be nonpolar, and water wouldn\'t dissolve salt, form oceans, or keep you alive. **Shape is destiny** in chemistry.',
        },
        {
          kind: 'concept',
          title: 'VSEPR in one sentence',
          body: '**Electron domains around the central atom spread out as far apart as possible**, because electron pairs repel each other.\n\nAn **electron domain** = a lone pair, a single bond, a double bond, or a triple bond. **A multiple bond counts as ONE domain.**\n\nFirst count the domains to get the electron geometry. Then look at **atoms only** to name the molecular shape.',
        },
        {
          kind: 'concept',
          title: 'The shape table',
          body: '| Domains | Lone pairs | Shape | Angle | Example |\n| 2 | 0 | linear | 180° | CO₂ |\n| 3 | 0 | trigonal planar | 120° | BF₃ |\n| 3 | 1 | bent | <120° | SO₂ |\n| 4 | 0 | tetrahedral | 109.5° | CH₄ |\n| 4 | 1 | trigonal pyramidal | <109.5° (~107°) | NH₃ |\n| 4 | 2 | bent | <109.5° (~104.5°) | H₂O |\n| 5 | 0 | trigonal bipyramidal | 90°, 120°, 180° | PCl₅ |\n| 5 | 1 | seesaw | — | SF₄ |\n| 5 | 2 | T-shaped | — | ClF₃ |\n| 5 | 3 | linear | 180° | XeF₂ |\n| 6 | 0 | octahedral | 90° | SF₆ |\n| 6 | 1 | square pyramidal | — | BrF₅ |\n| 6 | 2 | square planar | 90° | XeF₄ |',
        },
        {
          kind: 'hack',
          title: 'Lone pairs are "fat"',
          body: 'Lone pairs take up **more space** than bonding pairs, so they squeeze the bond angles smaller:\n\nCH₄ 109.5° → NH₃ ~107° → H₂O ~104.5°\n\nEach extra lone pair on a tetrahedral arrangement squeezes the angle a bit more.',
        },
        {
          kind: 'example',
          title: 'Shape of NH₃',
          problem: 'Predict the molecular shape and approximate bond angle of **NH₃**.',
          steps: [
            'Lewis diagram: N has 3 bonds to H and 1 lone pair.',
            'Domains = 3 bonds + 1 lone pair = **4** → tetrahedral electron geometry.',
            'Name the shape by atoms only: 3 atoms around N in a pyramid → **trigonal pyramidal**.',
            'The lone pair squeezes the angles → **about 107°** (a bit less than 109.5°).',
          ],
          answer: 'Trigonal pyramidal, ≈107°',
        },
        {
          kind: 'try',
          question: {
            id: 'c2.7a-t1',
            type: 'mcq',
            prompt: 'What is the molecular shape of **SO₂**? (The S has one lone pair and is bonded to two O atoms.)',
            choices: ['linear', 'bent', 'trigonal planar', 'tetrahedral'],
            answer: 1,
            hint: 'Count domains: 2 bonding domains + 1 lone pair = 3.',
            explain: '3 domains (2 bonds + 1 lone pair) → trigonal planar electron geometry. With atoms only, it\'s **bent**, with an angle a little under 120°.',
          },
        },
        {
          kind: 'trap',
          body: 'Students often call CO₂ and H₂O "the same shape" because both are AX₂. But H₂O has **2 lone pairs** on O (4 domains → bent), while CO₂ has **none** on C (2 domains → linear). Always draw the Lewis diagram first!',
        },
        {
          kind: 'summary',
          points: [
            'Count electron domains (a multiple bond = 1 domain). Domains spread out.',
            'Name the shape using atoms only. Lone pairs are "invisible" but take up space.',
            'Lone pairs shrink bond angles: 109.5° → 107° → 104.5°.',
          ],
        },
      ],
      check: [
        {
          id: 'c2.7a-q1',
          type: 'mcq',
          prompt: 'What is the bond angle in **BF₃**?',
          choices: ['90°', '109.5°', '120°', '180°'],
          answer: 2,
          explain: 'B has 3 bonding domains and no lone pairs → trigonal planar → **120°**.',
        },
        {
          id: 'c2.7a-q2',
          type: 'mcq',
          prompt: 'XeF₄ has 4 bonding domains and 2 lone pairs on Xe. Its molecular shape is…',
          choices: ['tetrahedral', 'seesaw', 'square planar', 'octahedral'],
          answer: 2,
          hint: '6 domains total. The two lone pairs go opposite each other.',
          explain: '6 domains → octahedral electron geometry. The 2 lone pairs sit opposite each other, leaving the 4 F atoms in a flat square → **square planar**.',
        },
        {
          id: 'c2.7a-q3',
          type: 'mcq',
          prompt: 'Which molecule has the **smallest** H–X–H bond angle?',
          choices: ['CH₄', 'NH₃', 'H₂O', 'All are 109.5°'],
          answer: 2,
          explain: 'H₂O has **2 lone pairs** squeezing its bonds → ~104.5°, smaller than NH₃ (~107°, 1 lone pair) and CH₄ (109.5°, none).',
        },
        {
          id: 'c2.7a-q4',
          type: 'mcq',
          prompt: 'How many electron domains surround C in **HCN** (H–C≡N)?',
          choices: ['2', '3', '4', '5'],
          answer: 0,
          hint: 'A triple bond counts as one domain.',
          explain: 'C has a single bond to H and a triple bond to N = **2 domains** → linear, 180°.',
        },
      ],
      flashcards: [
        { front: '4 domains, 2 lone pairs → shape?', back: '**Bent**, ~104.5° (like H₂O)' },
        { front: '4 domains, 1 lone pair → shape?', back: '**Trigonal pyramidal**, ~107° (like NH₃)' },
        { front: '6 domains, 2 lone pairs → shape?', back: '**Square planar** (like XeF₄)' },
        { front: '5 domains, 1 lone pair → shape?', back: '**Seesaw** (like SF₄)' },
        { front: 'Does a double bond count as 1 or 2 electron domains?', back: '**1 domain**' },
      ],
    },
    {
      id: 'chem-2.7b',
      ced: ['2.7'],
      title: 'Hybridization, Sigma/Pi Bonds & Polarity',
      level: 'core',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'Two molecules can have the same polar bonds, yet one is polar and the other isn\'t. It\'s all about **symmetry**, like a tug-of-war where equal teams pull in opposite directions.',
        },
        {
          kind: 'concept',
          title: 'Hybridization: just match the domains',
          body: 'On the AP exam, hybridization is a **naming code** for the number of electron domains:\n\n| Domains | Hybridization | Ideal angle |\n| 2 | sp | 180° |\n| 3 | sp² | 120° |\n| 4 | sp³ | 109.5° |\n\nYou don\'t need to draw hybrid orbitals, and hybridization involving d orbitals (5–6 domains) isn\'t tested. For those, just know the shape.',
        },
        {
          kind: 'concept',
          title: 'Sigma (σ) and pi (π) bonds',
          body: '- Single bond = **1 σ**\n- Double bond = **1 σ + 1 π**\n- Triple bond = **1 σ + 2 π**\n\nσ bonds come from **head-on overlap**, which is stronger. π bonds come from **side-by-side overlap**, which is weaker. So a σ bond has greater bond energy than a π bond.\n\nA π bond **locks rotation** around the bond, which makes **cis/trans (geometric) isomers** possible around C=C.',
        },
        {
          kind: 'concept',
          title: 'Is the molecule polar?',
          body: 'A molecule has a **dipole moment** (it\'s polar) if:\n\n1. it has **polar bonds**, AND\n2. its shape is **not symmetric**, so the bond dipoles don\'t cancel.\n\n| Molecule | Polar bonds? | Symmetric? | Polar? |\n| CO₂ | yes | yes (linear) | **no** |\n| H₂O | yes | no (bent) | **yes** |\n| CCl₄ | yes | yes (tetrahedral) | **no** |\n| CHCl₃ | yes | no | **yes** |\n| NH₃ | yes | no (pyramidal) | **yes** |\n| BF₃ | yes | yes (trigonal planar) | **no** |',
        },
        {
          kind: 'hack',
          title: 'The quick polarity test',
          body: 'If the central atom has **no lone pairs** AND **all the outer atoms are identical**, the molecule is **nonpolar**. Otherwise, check it carefully. It\'s usually polar.\n\nCH₄ → nonpolar. CH₃Cl (one outer atom different) → polar. NH₃ (lone pair) → polar.',
        },
        {
          kind: 'example',
          title: 'Count σ and π bonds',
          problem: 'How many σ and π bonds are in **ethene, H₂C=CH₂**?',
          steps: [
            'Bonds: 4 C–H single bonds + 1 C=C double bond.',
            'σ: 4 (from the C–H bonds) + 1 (from C=C) = **5 σ**',
            'π: the C=C has **1 π**.',
            'Each C has 3 domains → **sp²**, 120°.',
          ],
          answer: '5 σ bonds and 1 π bond. Both carbons are sp².',
        },
        {
          kind: 'try',
          question: {
            id: 'c2.7b-t1',
            type: 'mcq',
            prompt: 'What is the hybridization of **C in CO₂**?',
            choices: ['sp', 'sp²', 'sp³', 'none'],
            answer: 0,
            hint: 'O=C=O: how many electron domains on C?',
            explain: 'C has 2 domains (two double bonds) → **sp**, linear, 180°.',
          },
        },
        {
          kind: 'summary',
          points: [
            '2 domains = sp, 3 = sp², 4 = sp³.',
            'Single = σ. Double = σ + π. Triple = σ + 2π. σ is stronger than π, and π prevents rotation.',
            'Polar molecule = polar bonds + an asymmetric shape.',
          ],
        },
      ],
      check: [
        {
          id: 'c2.7b-q1',
          type: 'mcq',
          prompt: 'Which molecule is **nonpolar**?',
          choices: ['H₂O', 'NH₃', 'CCl₄', 'CH₂Cl₂'],
          answer: 2,
          explain: '**CCl₄** is a symmetric tetrahedron with identical outer atoms and no lone pair on C, so the C–Cl dipoles cancel.',
        },
        {
          id: 'c2.7b-q2',
          type: 'mcq',
          prompt: 'How many π bonds are in **N≡N**?',
          choices: ['0', '1', '2', '3'],
          answer: 2,
          explain: 'A triple bond = 1 σ + **2 π**.',
        },
        {
          id: 'c2.7b-q3',
          type: 'mcq',
          prompt: 'The O atom in H₂O has 4 electron domains. Its hybridization is…',
          choices: ['sp', 'sp²', 'sp³', 'sp³d'],
          answer: 2,
          explain: '4 domains (2 bonds + 2 lone pairs) → **sp³**.',
        },
        {
          id: 'c2.7b-q4',
          type: 'mcq',
          prompt: 'Why can cis and trans versions of 1,2-dichloroethene (ClHC=CHCl) exist as separate compounds?',
          choices: [
            'The C–Cl bond is polar',
            'The π bond prevents rotation around the C=C bond',
            'Carbon is sp³ hybridized',
            'Chlorine has lone pairs',
          ],
          answer: 1,
          explain: 'The **π bond** in C=C blocks rotation, so the two arrangements (Cl atoms on the same side or opposite sides) can\'t interconvert. They are **geometric isomers**.',
        },
      ],
      flashcards: [
        { front: 'Hybridization for 2, 3, 4 domains', back: 'sp (180°), sp² (120°), sp³ (109.5°)' },
        { front: 'Double bond = ? σ + ? π', back: '1 σ + 1 π' },
        { front: 'Which is stronger: a σ or a π bond?', back: '**σ** (head-on overlap is stronger)' },
        { front: 'When is a molecule polar?', back: 'It has polar bonds AND an asymmetric shape, so the dipoles don\'t cancel.' },
      ],
    },
    // ---------------- ADVANCED ----------------
    {
      id: 'chem-2.6',
      ced: ['2.6'],
      title: 'Resonance & Formal Charge',
      level: 'advanced',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'Draw NO₃⁻ and you\'ll find the double bond could go to **any** of the three oxygens. Which one is right? Trick question: **none of them alone**. The real ion is a blend of all three.',
        },
        {
          kind: 'concept',
          title: 'Resonance',
          body: 'When more than one valid Lewis diagram can be drawn **without moving any atoms**, only electrons, the real structure is a **resonance hybrid**: an average of them all.\n\nNO₃⁻ has 3 resonance structures. In reality, all three N–O bonds are **identical**: each is about **1⅓** bonds (4 bonds shared over 3 positions), so each is longer than a double bond and shorter than a single bond.\n\nResonance is a **refinement** of the Lewis model, needed to predict bond lengths and properties correctly.',
        },
        {
          kind: 'concept',
          title: 'Formal charge: a bookkeeping tool',
          body: '**FC = (valence e⁻) − (lone pair e⁻) − ½(bonding e⁻)**\n\nA quicker way: **FC = valence e⁻ − (dots + lines)** around that atom.\n\nThe best Lewis diagram:\n1. gives atoms formal charges **as close to zero** as possible, and\n2. puts any **negative** formal charge on the **most electronegative** atom.\n\nThe formal charges always add up to the overall charge of the species.',
        },
        {
          kind: 'example',
          title: 'Which CO₂ is best?',
          problem: 'Compare **O=C=O** with **O≡C–O** (each O has enough lone pairs for an octet).',
          steps: [
            'O=C=O: each O has 2 lone pairs + 2 bonds → FC = 6 − (4 + 2) = **0**. C: 4 − (0 + 4) = **0**.',
            'O≡C–O: the triple-bonded O has 1 lone pair + 3 bonds → FC = 6 − (2 + 3) = **+1**. The single-bonded O has 3 lone pairs + 1 bond → 6 − (6 + 1) = **−1**. C = 0.',
            'All zeros beat +1/−1 → **O=C=O** is the better structure.',
          ],
          answer: 'O=C=O. All formal charges are zero.',
        },
        {
          kind: 'hack',
          title: '"Dots plus sticks" shortcut',
          body: 'For each atom: **FC = group number − (dots + sticks)**\n\n- Count each lone-pair **dot** individually (a lone pair = 2 dots).\n- Count each **bond line** once.\n\nOxygen with 2 lone pairs and 2 bonds: 6 − (4 + 2) = 0 ✓',
        },
        {
          kind: 'try',
          question: {
            id: 'c2.6-t1',
            type: 'mcq',
            prompt: 'The carbonate ion, CO₃²⁻, has three resonance structures. What is the average C–O bond order?',
            choices: ['1', '1⅓', '1½', '2'],
            answer: 1,
            hint: 'Each structure has 1 double bond + 2 single bonds = 4 bonds shared over 3 positions.',
            explain: '4 bonds ÷ 3 C–O positions = **1⅓**. All three C–O bonds are identical in reality.',
          },
        },
        {
          kind: 'trap',
          body: 'Resonance structures are **not** flipping back and forth like a light switch. The molecule is **one** blended structure all the time. Also, formal charge is not the same as a real charge or an oxidation number. It\'s a tool for comparing Lewis diagrams.',
        },
        {
          kind: 'summary',
          points: [
            'Resonance: several valid diagrams (only electrons move) → the real structure is a blend with averaged bonds.',
            'FC = valence e⁻ − (dots + sticks).',
            'Best structure: FCs closest to 0, with any negative FC on the most electronegative atom.',
          ],
        },
      ],
      check: [
        {
          id: 'c2.6-q1',
          type: 'mcq',
          prompt: 'Ozone, O₃, is drawn with resonance structures. How do its two O–O bond lengths compare?',
          choices: [
            'One is a single bond and one is a double bond',
            'They are identical, in between a single and a double bond',
            'Both are double bonds',
            'Both are single bonds',
          ],
          answer: 1,
          explain: 'The resonance hybrid averages the two structures, so both bonds have bond order **1½**. They are identical, longer than O=O and shorter than O–O.',
        },
        {
          id: 'c2.6-q2',
          type: 'mcq',
          prompt: 'What is the formal charge on N in **NH₄⁺**?',
          choices: ['−1', '0', '+1', '+2'],
          answer: 2,
          hint: 'N has 5 valence electrons, 4 bonds and no lone pairs.',
          explain: 'FC = 5 − (0 dots + 4 sticks) = **+1**. That matches the ion\'s overall +1 charge (each H is 0).',
        },
        {
          id: 'c2.6-q3',
          type: 'mcq',
          prompt: 'For the thiocyanate ion, SCN⁻, which structure is **preferred**?',
          choices: [
            '[S=C=N]⁻ with FC: S = 0, C = 0, N = −1',
            '[S≡C–N]⁻ with FC: S = +1, C = 0, N = −2',
            '[S–C≡N]⁻ with FC: S = −1, C = 0, N = 0',
            'They are all equally good',
          ],
          answer: 0,
          hint: 'Prefer the smallest formal charges, with a negative FC on the most electronegative atom.',
          explain: 'The [S≡C–N]⁻ structure has large charges (+1, −2), so it is the worst. [S=C=N]⁻ and [S–C≡N]⁻ each have just one −1. N is more electronegative than S, so the −1 belongs on **N**: **[S=C=N]⁻** is preferred.',
        },
      ],
      flashcards: [
        { front: 'Formal charge formula', back: 'FC = valence e⁻ − nonbonding e⁻ − ½ bonding e⁻ (= group # − dots − sticks)' },
        { front: 'What makes a Lewis structure "best" by formal charge?', back: 'FCs closest to zero, and any negative FC on the most electronegative atom.' },
        { front: 'Resonance hybrid', back: 'The real structure: an average of all the valid resonance diagrams (only electrons move).' },
      ],
    },
  ],
  checkpoint: [
    {
      id: 'c2-cp1',
      type: 'mcq',
      prompt: 'Which species is **trigonal pyramidal**?',
      choices: ['BF₃', 'NH₃', 'SO₃', 'CH₄'],
      answer: 1,
      explain: 'NH₃ has 3 bonds + 1 lone pair on N → **trigonal pyramidal**. BF₃ and SO₃ are trigonal planar, and CH₄ is tetrahedral.',
    },
    {
      id: 'c2-cp2',
      type: 'mcq',
      prompt: 'Which compound would have the **largest** lattice energy (strongest ionic attraction)?',
      choices: ['NaCl', 'KBr', 'MgO', 'CsI'],
      answer: 2,
      explain: '**MgO** has 2+/2− charges and small ions, giving by far the strongest Coulombic attraction.',
    },
    {
      id: 'c2-cp3',
      type: 'mcq',
      prompt: 'How many σ and π bonds are in **HC≡CH** (acetylene)?',
      choices: ['3 σ, 2 π', '2 σ, 3 π', '5 σ, 0 π', '3 σ, 1 π'],
      answer: 0,
      explain: 'Two C–H bonds (2 σ) + C≡C (1 σ + 2 π) = **3 σ, 2 π**.',
    },
    {
      id: 'c2-cp4',
      type: 'mcq',
      prompt: 'SF₆ is nonpolar even though S–F bonds are polar because…',
      choices: [
        'S and F have the same electronegativity',
        'its octahedral shape is symmetric, so the bond dipoles cancel',
        'it has lone pairs on S',
        'it is an ionic compound',
      ],
      answer: 1,
      explain: 'Six identical S–F dipoles arranged **symmetrically** (octahedral) cancel out → no net dipole.',
    },
  ],
}
