import type { Unit } from '../types'
import { CONST, molarMass } from '../../lib/chem'

const R = CONST.R_Latm

export const unit3: Unit = {
  id: 'chem-u3',
  number: 3,
  title: 'Properties of Substances and Mixtures',
  weight: '18–22%',
  blurb:
    'The biggest unit on the exam. Intermolecular forces explain boiling points, solubility and the states of matter. Plus gases, solutions, and how light interacts with matter.',
  badge: { name: 'Force Master', emoji: '🧲' },
  lessons: [
    // ---------------- FOUNDATION ----------------
    {
      id: 'chem-3.3',
      ced: ['3.3'],
      title: 'Solids, Liquids & Gases',
      level: 'foundation',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'Ice, water and steam are all H₂O molecules. They\'re identical! The only differences are **how close together** the molecules are and **how much they move**.',
        },
        {
          kind: 'concept',
          title: 'Three phases, particle by particle',
          body: '| | Solid | Liquid | Gas |\n| Spacing | touching | touching | far apart |\n| Motion | vibrate in place | slide past each other | fast, random, constant |\n| Shape | definite | takes the container\'s shape | fills the container |\n| Volume | definite | definite | fills the container |',
          diagram: 'phases',
        },
        {
          kind: 'concept',
          title: 'Key details the AP exam likes',
          body: '- Solids can be **crystalline** (regular, repeating arrangement, like salt) or **amorphous** (no orderly arrangement, like glass). In both, particles can\'t move past each other.\n- Solids and liquids have **similar molar volumes**, because the particles touch in both phases.\n- In a gas, spacing and collision frequency depend on **temperature, pressure and volume**. With little attraction between particles, a gas has no definite shape or volume.',
        },
        {
          kind: 'hack',
          title: 'Drawing particle diagrams',
          body: 'On FRQs, phase drawings are graded on the details:\n\n- **Solid:** particles touching, in neat rows (if crystalline).\n- **Liquid:** particles still **touching**, but jumbled. Don\'t space them out!\n- **Gas:** few particles, far apart, randomly placed.\n\nThe most common mistake is drawing liquids with gaps like a gas.',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.3-t1',
            type: 'mcq',
            prompt: 'Why do a solid and its liquid typically have **similar molar volumes**?',
            choices: [
              'The particles are the same size',
              'In both phases the particles are in close contact',
              'Both have definite shapes',
              'Neither phase has intermolecular forces',
            ],
            answer: 1,
            explain: 'Molar volume depends on spacing. In both solids and liquids, particles are **touching**, so the volume per mole is similar. A gas takes up far more space.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Solid: fixed, vibrating. Liquid: touching, flowing. Gas: far apart, fast, random.',
            'Crystalline = ordered. Amorphous = disordered.',
            'Solids and liquids have similar molar volumes. Gases are mostly empty space.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.3-q1',
          type: 'mcq',
          prompt: 'Which correctly describes particles in a **liquid**?',
          choices: [
            'Far apart and moving randomly',
            'In contact, but able to move past one another',
            'Locked in fixed positions',
            'Not moving at all',
          ],
          answer: 1,
          explain: 'Liquid particles are **in close contact** but continually moving and colliding, which lets the liquid flow.',
        },
        {
          id: 'c3.3-q2',
          type: 'mcq',
          prompt: 'Glass has no regular, repeating arrangement of particles. Glass is…',
          choices: ['a crystalline solid', 'an amorphous solid', 'a liquid', 'a gas'],
          answer: 1,
          explain: 'A solid with no orderly arrangement is **amorphous**.',
        },
      ],
      flashcards: [
        { front: 'Crystalline vs. amorphous solid', back: 'Crystalline: regular 3-D pattern. Amorphous: no orderly arrangement.' },
        { front: 'Why does a gas have no definite volume?', back: 'Its particles are in constant motion with minimal attractions, so they spread out to fill the container.' },
      ],
    },
    {
      id: 'chem-3.1a',
      ced: ['3.1'],
      title: 'Intermolecular Forces: The Four Types',
      level: 'foundation',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'Geckos can walk on ceilings using the same weak "sticky" forces that hold molecules together in liquids. These forces **between** molecules (intermolecular forces, IMFs) decide whether something is a gas, a liquid or a solid at room temperature.',
        },
        {
          kind: 'concept',
          title: 'Inside vs. between',
          body: '**Intra**molecular = bonds **inside** a molecule (covalent bonds). Strong.\n**Inter**molecular = attractions **between** molecules. Much weaker.\n\nWhen water boils, the O–H bonds don\'t break! The molecules just separate from each other. Boiling overcomes **inter**molecular forces only.',
        },
        {
          kind: 'concept',
          title: 'The four IMFs (weakest → strongest, generally)',
          body: '1. **London dispersion forces (LDFs):** *every* molecule has them. Electrons shift around and create temporary (fluctuating) dipoles, which induce dipoles in neighbors. **More electrons → more polarizable → stronger LDFs.**\n2. **Dipole–dipole:** between **polar** molecules. The δ+ end of one attracts the δ− end of another.\n3. **Hydrogen bonding:** a strong special case of dipole–dipole. It forms when **H is bonded directly to N, O or F**, and that H is attracted to a lone pair on an N, O or F in another molecule (or another part of the same molecule).\n4. **Ion–dipole:** between an **ion** and a **polar** molecule (like Na⁺ surrounded by water). Generally stronger than dipole–dipole.',
        },
        {
          kind: 'hack',
          title: 'The IMF flowchart',
          body: 'Ask in order:\n\n1. Ion + polar molecule? → **ion–dipole**\n2. H bonded directly to **N, O or F**? → **H-bonding** (plus dipole–dipole and LDFs)\n3. Polar molecule? → **dipole–dipole** (plus LDFs)\n4. Otherwise → **LDFs only**\n\nRemember: "H-bonding is **FON**!" (F, O, N)',
        },
        {
          kind: 'trap',
          body: '**CH₃F** has H atoms and an F atom, but the H is bonded to **C**, not F. So there is **no** hydrogen bonding between CH₃F molecules. The H must be **directly** attached to N, O or F.\n\nAlso, the College Board course description says not to use "van der Waals forces" as a synonym for London dispersion forces. Use the specific name.',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.1a-t1',
            type: 'mcq',
            prompt: 'Which substance can form **hydrogen bonds** with itself?',
            choices: ['CH₄', 'CH₃OCH₃', 'CH₃OH', 'HCl'],
            answer: 2,
            hint: 'Look for an H attached directly to N, O or F.',
            explain: 'Only **CH₃OH** has an O–H bond. CH₃OCH₃ has O, but all its H atoms are on C. HCl: Cl isn\'t N, O or F.',
          },
        },
        {
          kind: 'concept',
          title: 'Big molecules, big forces',
          body: 'LDFs are present in everything, and for **large molecules they\'re often the strongest IMF overall**, even beating the dipole–dipole forces in smaller polar molecules.\n\nIn huge biomolecules like proteins and DNA, these noncovalent attractions also act **between different parts of the same molecule**, holding its shape.',
        },
        {
          kind: 'summary',
          points: [
            'IMFs are between molecules. Boiling and melting break IMFs, not covalent bonds.',
            'LDFs (everyone) < dipole–dipole (polar) < H-bonding (H on N/O/F) < ion–dipole (generally).',
            'More electrons = more polarizable = stronger LDFs.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.1a-q1',
          type: 'mcq',
          prompt: 'What is the **only** type of IMF between molecules of **CO₂**?',
          choices: ['Hydrogen bonding', 'Dipole–dipole', 'London dispersion', 'Ion–dipole'],
          answer: 2,
          hint: 'Is CO₂ polar overall?',
          explain: 'CO₂ is linear and symmetric, so it\'s **nonpolar**. Nonpolar molecules have only **London dispersion forces**.',
        },
        {
          id: 'c3.1a-q2',
          type: 'mcq',
          prompt: 'When NaCl dissolves in water, the main attraction between Na⁺ and H₂O is…',
          choices: ['ionic bonding', 'ion–dipole', 'hydrogen bonding', 'London dispersion'],
          answer: 1,
          explain: 'An **ion** (Na⁺) attracted to the δ− oxygen of a **polar** water molecule = **ion–dipole**.',
        },
        {
          id: 'c3.1a-q3',
          type: 'mcq',
          prompt: 'London dispersion forces arise from…',
          choices: [
            'permanent dipoles in polar molecules',
            'temporary, fluctuating dipoles caused by shifting electrons',
            'H atoms bonded to N, O or F',
            'the attraction between ions',
          ],
          answer: 1,
          explain: 'LDFs come from **temporary (fluctuating) dipoles**: momentary uneven electron distributions that induce dipoles in neighbors.',
        },
      ],
      flashcards: [
        { front: 'Requirement for hydrogen bonding', back: 'H covalently bonded **directly** to N, O or F, attracted to a lone pair on N, O or F nearby.' },
        { front: 'What makes LDFs stronger?', back: 'More electrons / larger, more **polarizable** electron cloud (and more surface contact).' },
        { front: 'Which IMF does every molecule have?', back: '**London dispersion forces**' },
        { front: 'Intramolecular vs. intermolecular', back: 'Intra = bonds inside a molecule. Inter = attractions between molecules (much weaker).' },
      ],
    },
    {
      id: 'chem-3.7',
      ced: ['3.7'],
      title: 'Solutions & Molarity',
      level: 'foundation',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'A sports drink, the air you breathe and a brass trumpet are all **solutions**. A solution doesn\'t have to be a liquid. It just has to be **uniform** throughout.',
        },
        {
          kind: 'concept',
          title: 'Solution vs. heterogeneous mixture',
          body: '- **Solution (homogeneous mixture):** properties are the **same throughout** the sample. It can be solid (alloy), liquid (salt water) or gas (air).\n- **Heterogeneous mixture:** properties **depend on where** you look (sand in water, salad dressing).',
        },
        {
          kind: 'concept',
          title: 'Molarity',
          body: '**M = moles of solute ÷ liters of solution**\n\nUnits: mol/L, written "M". A 2.0 M NaCl solution has 2.0 mol NaCl in every liter of **solution** (not every liter of water added!).\n\nRearrange as needed:\n- moles = M × L\n- L = moles ÷ M',
        },
        {
          kind: 'example',
          title: 'Make a solution',
          problem: '**5.85 g of NaCl** is dissolved to make **250.0 mL** of solution. What is the molarity?',
          steps: [
            'Moles NaCl = 5.85 g ÷ 58.44 g/mol = **0.100 mol**',
            'Volume = 250.0 mL = **0.2500 L**',
            'M = 0.100 mol ÷ 0.2500 L = **0.400 M**',
          ],
          answer: '0.400 M NaCl',
          verify: [
            { stated: 0.1, compute: () => 5.85 / molarMass('NaCl') },
            { stated: 0.4, compute: () => 5.85 / molarMass('NaCl') / 0.25 },
          ],
        },
        {
          kind: 'hack',
          title: 'Count the ions!',
          body: 'Ionic solutes split into ions. A **0.10 M CaCl₂** solution contains:\n\n- [Ca²⁺] = 0.10 M\n- [Cl⁻] = **0.20 M** (2 Cl⁻ per formula unit)\n\nAP loves asking "which solution has the highest concentration of ions?" Multiply the molarity by the number of ions per formula unit.',
        },
        {
          kind: 'concept',
          title: 'Dilution',
          body: 'Adding water doesn\'t change the **moles** of solute, so:\n\n**M₁V₁ = M₂V₂**\n\nExample: diluting 50.0 mL of 2.00 M HCl to 200.0 mL gives (2.00)(50.0) = M₂(200.0), so M₂ = **0.500 M**.',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.7-t1',
            type: 'num',
            prompt: 'How many **moles** of KNO₃ are in **75.0 mL** of a 0.200 M KNO₃ solution?',
            answer: 0.015,
            unit: 'mol',
            hint: 'moles = M × L. Convert mL to L first.',
            explain: '0.200 mol/L × 0.0750 L = **0.0150 mol**',
            compute: () => 0.2 * 0.075,
          },
        },
        {
          kind: 'summary',
          points: [
            'Solution = homogeneous (uniform). Heterogeneous mixture = varies by location.',
            'M = mol solute / L solution.',
            'Ion concentration = M × ions per formula unit. Dilution: M₁V₁ = M₂V₂.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.7-q1',
          type: 'num',
          prompt: 'What is the molarity of a solution made by dissolving **0.500 mol of glucose** in enough water to make **2.00 L** of solution?',
          answer: 0.25,
          unit: 'M',
          explain: 'M = 0.500 mol ÷ 2.00 L = **0.250 M**',
          compute: () => 0.5 / 2.0,
        },
        {
          id: 'c3.7-q2',
          type: 'mcq',
          prompt: 'Which solution has the **highest total concentration of ions**?',
          choices: ['0.10 M NaCl', '0.10 M MgCl₂', '0.10 M Al(NO₃)₃', '0.20 M glucose'],
          answer: 2,
          hint: 'Count the ions per formula unit. Glucose doesn\'t ionize.',
          explain: 'Al(NO₃)₃ → Al³⁺ + 3 NO₃⁻ = 4 ions → **0.40 M** of ions. MgCl₂: 0.30 M. NaCl: 0.20 M. Glucose makes no ions.',
        },
        {
          id: 'c3.7-q3',
          type: 'num',
          prompt: '25.0 mL of 6.00 M HCl is diluted to **150.0 mL**. What is the new concentration?',
          answer: 1.0,
          unit: 'M',
          hint: 'M₁V₁ = M₂V₂',
          explain: '(6.00)(25.0) = M₂(150.0) → M₂ = **1.00 M**',
          compute: () => (6.0 * 25.0) / 150.0,
        },
      ],
      flashcards: [
        { front: 'Molarity formula', back: 'M = moles of solute ÷ liters of **solution**' },
        { front: 'Dilution equation', back: 'M₁V₁ = M₂V₂' },
        { front: '[Cl⁻] in 0.10 M CaCl₂?', back: '**0.20 M** (2 Cl⁻ per CaCl₂)' },
      ],
    },
    // ---------------- CORE ----------------
    {
      id: 'chem-3.1b',
      ced: ['3.1', '3.2'],
      title: 'Comparing IMFs: Boiling Points & Vapor Pressure',
      level: 'core',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'Water (18 g/mol) boils at 100 °C. Methane (16 g/mol) boils at −162 °C. Almost the same size, yet a 262-degree difference! IMFs explain it, and **"which has the higher boiling point?"** is one of the most common AP questions of all.',
        },
        {
          kind: 'concept',
          title: 'Stronger IMFs → higher boiling point, lower vapor pressure',
          body: 'Boiling and vaporizing **completely overcome** the IMFs. So:\n\n- **Stronger IMFs → higher boiling point**\n- **Stronger IMFs → lower vapor pressure** (fewer molecules escape into the gas)\n\nMelting points also tend to follow IMF strength, but less neatly, because melting only **rearranges** the interactions (packing matters too).',
        },
        {
          kind: 'hack',
          title: 'The 2-step comparison',
          body: '**Step 1: same size (similar electron count)?** Compare the IMF *types*: H-bonding > dipole–dipole > LDF only.\n→ H₂O (H-bonds) ≫ CH₄ (LDF only)\n\n**Step 2: very different sizes?** LDFs can win! Compare **electron count / polarizability**.\n→ I₂ (solid at room temperature) > Br₂ (liquid) > Cl₂ (gas) > F₂ (gas), all LDF only\n\n**Shape tiebreaker:** long, straight molecules have **more surface contact** → stronger LDFs. n-pentane (36 °C) boils higher than the ball-shaped neopentane (9.5 °C), even though both are C₅H₁₂.',
        },
        {
          kind: 'example',
          title: 'HF vs. HCl',
          problem: 'Explain why **HF** (bp 20 °C) has a higher boiling point than **HCl** (bp −85 °C), even though HCl has more electrons.',
          steps: [
            'Identify the IMFs: HF has **H bonded to F** → hydrogen bonding (plus dipole–dipole and LDFs). HCl has dipole–dipole and LDFs, but no H-bonding.',
            'HCl\'s LDFs are a bit stronger (more electrons), but the **hydrogen bonds** between HF molecules are much stronger overall.',
            'Stronger IMFs need more energy to overcome → higher boiling point for HF.',
          ],
          answer: 'HF\'s hydrogen bonding outweighs HCl\'s slightly stronger LDFs.',
        },
        {
          kind: 'frq',
          title: 'Earn the point: compare BOTH substances',
          body: 'A full-credit answer:\n1. Names the IMFs in **both** substances.\n2. Says which is **stronger** and why (structure: H on F/O/N, polarity, electron count).\n3. Links it to the property: "**more energy is required** to overcome the stronger IMFs, so…"\n\n❌ "HF has hydrogen bonds." (that\'s only half the story)\n✅ "HF molecules form hydrogen bonds, which are stronger than the dipole–dipole and dispersion forces between HCl molecules, so more energy is needed to separate HF molecules."',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.1b-t1',
            type: 'mcq',
            prompt: 'Which has the **highest vapor pressure** at 25 °C?',
            choices: ['H₂O', 'CH₃OH', 'CH₃CH₂OH', 'CH₃OCH₃ (dimethyl ether)'],
            answer: 3,
            hint: 'Highest vapor pressure = weakest IMFs. Which one cannot H-bond?',
            explain: '**CH₃OCH₃** has no O–H bond, so no H-bonding between its molecules. With the weakest IMFs, its molecules escape most easily → highest vapor pressure (it\'s a gas at room temperature).',
          },
        },
        {
          kind: 'trap',
          body: 'Never say a molecule boils "because its bonds break". Boiling separates **molecules**. The covalent bonds inside stay intact. Graders take points off for this!',
        },
        {
          kind: 'summary',
          points: [
            'Stronger IMFs → higher boiling point, lower vapor pressure.',
            'Similar size: compare IMF types. Very different size: LDFs (electron count) can dominate.',
            'Explain both substances, and link "more energy needed to overcome" to the property.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.1b-q1',
          type: 'mcq',
          prompt: 'Which halogen has the **highest boiling point**?',
          choices: ['F₂', 'Cl₂', 'Br₂', 'I₂'],
          answer: 3,
          explain: 'All are nonpolar (LDFs only). **I₂** has the most electrons → the most polarizable electron cloud → the strongest LDFs → the highest boiling point.',
        },
        {
          id: 'c3.1b-q2',
          type: 'mcq',
          prompt: 'H₂O boils at 100 °C and H₂S at −60 °C. The best explanation is…',
          choices: [
            'H₂S has more electrons',
            'H₂O molecules form hydrogen bonds, and H₂S molecules do not',
            'The O–H bond is stronger than the S–H bond',
            'H₂O is heavier',
          ],
          answer: 1,
          explain: 'H₂O has H bonded to O → **hydrogen bonding**, which is much stronger than the dipole–dipole/LDFs in H₂S. (The "O–H bond is stronger" choice is a trap: boiling doesn\'t break O–H bonds.)',
        },
        {
          id: 'c3.1b-q3',
          type: 'mcq',
          prompt: 'Two liquids are at the same temperature. Liquid X has a **higher vapor pressure** than liquid Y. Which is true?',
          choices: [
            'X has stronger IMFs and a higher boiling point',
            'X has weaker IMFs and a lower boiling point',
            'X has weaker IMFs and a higher boiling point',
            'Vapor pressure doesn\'t relate to IMFs',
          ],
          answer: 1,
          explain: 'Higher vapor pressure means molecules escape more easily → **weaker IMFs** → **lower boiling point**.',
        },
      ],
      flashcards: [
        { front: 'Stronger IMFs → boiling point? vapor pressure?', back: 'Boiling point **higher**, vapor pressure **lower**.' },
        { front: 'Can LDFs ever beat H-bonding?', back: 'Yes, in **much larger** molecules with many electrons (e.g., I₂, with LDFs only, boils at 184 °C, higher than H₂O at 100 °C).' },
        { front: 'Why does n-pentane boil higher than neopentane?', back: 'Its long shape gives **more surface contact** → stronger LDFs.' },
      ],
    },
    {
      id: 'chem-3.2',
      ced: ['3.2'],
      title: 'Types of Solids & Their Properties',
      level: 'core',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'Diamond is the hardest natural material, yet graphite, which is also pure carbon, is soft enough to write with. Same atoms, different structure, totally different properties.',
        },
        {
          kind: 'concept',
          title: 'The four types of solids',
          body: '| Type | Particles & forces | Properties | Examples |\n| **Ionic** | ions; Coulombic attractions | high mp, brittle, low vapor pressure, conducts only when melted/dissolved | NaCl, MgO |\n| **Covalent network** | atoms in a network of covalent bonds | very high mp, very hard (3-D), non-conducting (except graphite) | diamond, SiO₂, SiC, graphite |\n| **Molecular** | molecules; IMFs | low mp, soft, non-conducting | ice, sugar, I₂, CO₂(s) |\n| **Metallic** | cations + electron sea | conducts heat and electricity, malleable, ductile | Cu, Fe, alloys |',
        },
        {
          kind: 'concept',
          title: 'The covalent network story',
          body: 'Covalent network solids form only from **nonmetals and metalloids**: elements like diamond or graphite, or binary compounds like SiO₂ and SiC.\n\n- **Diamond**: a 3-D network with fixed bond angles → rigid and super hard.\n- **Graphite**: **2-D layers**. Strong bonds within each layer, but the layers **slide** past each other easily → soft and slippery.\n\nBoth have high melting points, because melting would require breaking covalent bonds.',
        },
        {
          kind: 'hack',
          title: 'Identify the solid from its formula',
          body: '- Metal + nonmetal → **ionic**\n- Only metal atoms → **metallic**\n- C (diamond/graphite), Si, SiO₂, SiC → **covalent network** (memorize these!)\n- Other nonmetal compounds → **molecular**\n\nMolecular solids don\'t conduct because their electrons are tightly held in bonds and lone pairs.',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.2-t1',
            type: 'mcq',
            prompt: 'A solid is very hard, melts above 1600 °C, and does not conduct electricity as a solid **or** when melted. What type is it most likely?',
            choices: ['Ionic', 'Molecular', 'Covalent network', 'Metallic'],
            answer: 2,
            hint: 'Ionic solids conduct when melted. Which very hard solid never conducts?',
            explain: 'Very high mp + hard + never conducting → **covalent network** (like SiO₂, quartz). An ionic solid would conduct when molten.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Ionic: high mp, brittle, conducts only when ions move.',
            'Covalent network: very high mp, hard (graphite is soft because its layers slide).',
            'Molecular: low mp, non-conducting. Metallic: conducting and malleable.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.2-q1',
          type: 'mcq',
          prompt: 'Why is graphite soft while diamond is extremely hard?',
          choices: [
            'Graphite has weaker covalent bonds',
            'Graphite is made of 2-D layers that slide past each other; diamond is a rigid 3-D network',
            'Graphite is a metal',
            'Diamond has ionic bonds',
          ],
          answer: 1,
          explain: 'Graphite\'s **layers** are held together only weakly, so they slide. Diamond\'s **3-D covalent network** has fixed bond angles in every direction.',
        },
        {
          id: 'c3.2-q2',
          type: 'mcq',
          prompt: 'Solid iodine, I₂, melts at 114 °C and doesn\'t conduct. What type of solid is it?',
          choices: ['Ionic', 'Molecular', 'Covalent network', 'Metallic'],
          answer: 1,
          explain: 'I₂ is made of individual molecules held by LDFs → a **molecular** solid: relatively low mp, non-conducting.',
        },
        {
          id: 'c3.2-q3',
          type: 'mcq',
          prompt: 'Which property is **typical of metallic solids** but NOT of ionic solids?',
          choices: ['High melting point', 'Malleability', 'Crystalline structure', 'Conducts when melted'],
          answer: 1,
          explain: 'Metals are **malleable** (layers of cations slide within the electron sea). Ionic solids shatter when layers shift.',
        },
      ],
      flashcards: [
        { front: 'Four examples of covalent network solids', back: 'Diamond, graphite, SiO₂ (quartz), SiC' },
        { front: 'Why don\'t molecular solids conduct?', back: 'Their electrons are held tightly in covalent bonds and lone pairs, so there are no mobile charges.' },
      ],
    },
    {
      id: 'chem-3.4',
      ced: ['3.4'],
      title: 'The Ideal Gas Law',
      level: 'core',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'A car airbag inflates in about 30 milliseconds. Engineers calculate exactly how much gas-producing chemical is needed using one equation: **PV = nRT**.',
        },
        {
          kind: 'concept',
          title: 'PV = nRT',
          body: '- P = pressure (atm)\n- V = volume (L)\n- n = moles\n- T = temperature in **kelvin** (K = °C + 273.15)\n- R = 0.08206 L·atm/(mol·K)\n\nBoth R values (8.314 J/(mol·K) and 0.08206 L·atm/(mol·K)), STP and 22.4 L/mol are on your equation sheet. At **STP (273.15 K, 1.0 atm)**, one mole of an ideal gas occupies **22.4 L**.',
        },
        {
          kind: 'example',
          title: 'Find the pressure',
          problem: '**2.00 mol** of gas is in a **10.0 L** container at **25 °C**. What is the pressure?',
          steps: [
            'Convert the temperature: 25 + 273 = **298 K**',
            'Solve for P: P = nRT/V = (2.00)(0.08206)(298) / 10.0',
            'P = **4.89 atm**',
          ],
          answer: '4.89 atm',
          verify: [{ stated: 4.89, compute: () => (2.0 * R * 298) / 10.0 }],
        },
        {
          kind: 'concept',
          title: 'Relationships to know (and graph!)',
          body: 'Hold the other variables constant:\n\n- P and V: **inverse** (P↑ → V↓). The graph is a curve.\n- V and T(K): **direct**. The graph is a straight line through 0 K.\n- P and T(K): **direct**.\n- V and n: **direct**.\n\nThe combined gas law, P₁V₁/T₁ = P₂V₂/T₂, handles "before and after" problems.',
        },
        {
          kind: 'concept',
          title: 'Gas mixtures: Dalton\'s law',
          body: 'Each gas in a mixture acts as if it were alone:\n\n**P_{total} = P_{A} + P_{B} + P_{C} + …**\n**P_{A} = P_{total} × X_{A}**, where X_{A} = mole fraction = moles A ÷ total moles\n\nExample: a mixture is 3 mol N₂ and 1 mol O₂ at 2.0 atm total. X_{O₂} = 1/4, so P_{O₂} = 0.50 atm.',
        },
        {
          kind: 'hack',
          title: 'Kelvin, always',
          body: 'The #1 gas law mistake is using °C. If T is in the denominator and you plug in 0 °C, you divide by zero! **Convert to kelvin before doing anything.**\n\nBonus trick: molar mass from density, **M = dRT/P** (from PV = nRT with n = m/M).',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.4-t1',
            type: 'num',
            prompt: 'What volume does **0.500 mol** of an ideal gas occupy at **STP**?',
            answer: 11.2,
            unit: 'L',
            hint: 'At STP, 1 mol occupies 22.4 L.',
            explain: '0.500 mol × 22.4 L/mol = **11.2 L**',
            compute: () => (0.5 * R * 273.15) / 1.0,
          },
        },
        {
          kind: 'summary',
          points: [
            'PV = nRT with T in kelvin and R = 0.08206 L·atm/(mol·K).',
            'P_total = sum of the partial pressures. P_A = X_A × P_total.',
            'At STP, 1 mol of gas = 22.4 L.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.4-q1',
          type: 'num',
          prompt: 'How many moles of gas are in a **5.00 L** flask at **1.50 atm** and **300. K**?',
          answer: 0.3047,
          unit: 'mol',
          tolerance: 0.01,
          explain: 'n = PV/RT = (1.50)(5.00)/(0.08206 × 300.) = **0.305 mol**',
          compute: () => (1.5 * 5.0) / (R * 300),
        },
        {
          id: 'c3.4-q2',
          type: 'mcq',
          prompt: 'The kelvin temperature of a gas is doubled at constant volume and moles. The pressure…',
          choices: ['halves', 'stays the same', 'doubles', 'quadruples'],
          answer: 2,
          explain: 'At constant V and n, P ∝ T (kelvin), so doubling T **doubles** P.',
        },
        {
          id: 'c3.4-q3',
          type: 'num',
          prompt: 'A mixture contains **2.0 mol He** and **6.0 mol Ar** at a total pressure of **4.0 atm**. What is the partial pressure of He?',
          answer: 1.0,
          unit: 'atm',
          hint: 'X_He = 2.0 / 8.0',
          explain: 'X_He = 2.0/8.0 = 0.25. P_He = 0.25 × 4.0 atm = **1.0 atm**',
          compute: () => (2.0 / 8.0) * 4.0,
        },
        {
          id: 'c3.4-q4',
          type: 'mcq',
          prompt: 'Which graph shape shows P vs. V for a gas at constant n and T?',
          choices: ['A straight line going up', 'A straight line going down', 'A curve that decreases (inverse relationship)', 'A horizontal line'],
          answer: 2,
          explain: 'P and V are **inversely** related (PV = constant), which gives a decreasing curve, not a straight line.',
        },
      ],
      flashcards: [
        { front: 'Ideal gas law', back: 'PV = nRT (T in kelvin)' },
        { front: 'R in L·atm units', back: '0.08206 L·atm/(mol·K)' },
        { front: 'Partial pressure from mole fraction', back: 'P_A = X_A × P_total' },
        { front: 'Volume of 1 mol of ideal gas at STP', back: '22.4 L (STP = 273.15 K, 1.0 atm)' },
      ],
    },
    {
      id: 'chem-3.5',
      ced: ['3.5'],
      title: 'Kinetic Molecular Theory',
      level: 'core',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'The air molecules around you are zooming at about **500 m/s**, faster than a passenger jet, and each one smashes into something billions of times every second. KMT turns that chaos into simple predictions.',
        },
        {
          kind: 'concept',
          title: 'The core ideas of KMT',
          body: '- Gas particles are in **constant, random motion**, colliding with each other and the walls. Wall collisions create **pressure**.\n- **Kelvin temperature is proportional to the average kinetic energy** of the particles.\n- **KE = ½mv²**\n\nSo at the **same temperature**, all gases have the **same average KE**. But **lighter** particles must move **faster** to have the same KE.',
        },
        {
          kind: 'concept',
          title: 'The Maxwell–Boltzmann distribution',
          body: 'Not every particle moves at the same speed. The distribution shows how many particles have each speed.\n\n- **Higher temperature** → the curve shifts **right** and gets **flatter and wider**: more particles at high speeds.\n- **Lighter gas at the same T** → its *speed* curve is also shifted right and flatter. (The *energy* distribution depends only on T.)\n- The **area under the curve** = the total number of particles, so it stays the same.',
          diagram: 'maxwell-boltzmann',
        },
        {
          kind: 'hack',
          title: 'Light = fast, heavy = slow',
          body: 'At the same temperature, compare molar masses:\n\nH₂ (2 g/mol) > He (4) > N₂ (28) > O₂ (32) > CO₂ (44) in **average speed**.\n\nBut **average KE is equal** for all of them (same T). AP loves testing that difference!',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.5-t1',
            type: 'mcq',
            prompt: 'Samples of He and Ar are both at 300 K. Which statement is true?',
            choices: [
              'They have the same average kinetic energy, but He atoms move faster on average',
              'Ar atoms have higher average kinetic energy',
              'They have the same average speed',
              'He atoms have higher average kinetic energy',
            ],
            answer: 0,
            hint: 'Same T → same average KE. Then use KE = ½mv².',
            explain: 'Same T → **same average KE**. Since KE = ½mv², the lighter He atoms must have a **higher average speed**.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Kelvin T ∝ average KE. KE = ½mv².',
            'Same T: same average KE, and lighter particles are faster.',
            'Hotter (or lighter): the M–B curve shifts right and flattens. The area stays the same.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.5-q1',
          type: 'mcq',
          prompt: 'When a gas is heated, its Maxwell–Boltzmann curve…',
          choices: [
            'gets taller and narrower, shifting left',
            'gets flatter and broader, shifting right',
            'stays exactly the same',
            'shows fewer total particles',
          ],
          answer: 1,
          explain: 'Higher T → more particles at higher speeds → the curve **flattens, broadens and shifts right**. The total area (number of particles) is unchanged.',
        },
        {
          id: 'c3.5-q2',
          type: 'mcq',
          prompt: 'According to KMT, gas pressure results from…',
          choices: [
            'particles attracting the walls',
            'particles colliding with the container walls',
            'the weight of the gas',
            'particles stopping at the walls',
          ],
          answer: 1,
          explain: 'Pressure = force from countless **collisions with the walls**. More frequent or harder collisions → higher pressure.',
        },
        {
          id: 'c3.5-q3',
          type: 'mcq',
          prompt: 'At the same temperature, which gas has the **lowest** average molecular speed?',
          choices: ['H₂', 'N₂', 'O₂', 'Cl₂'],
          answer: 3,
          explain: 'Same T → same KE. The heaviest molecule (**Cl₂**, 70.9 g/mol) moves the slowest.',
        },
      ],
      flashcards: [
        { front: 'What does kelvin temperature measure (KMT)?', back: 'It is proportional to the **average kinetic energy** of the particles.' },
        { front: 'Kinetic energy equation', back: 'KE = ½mv²' },
        { front: 'Same T, different gases: same what? different what?', back: 'Same average **KE**. Different average **speed** (lighter = faster).' },
      ],
    },
    {
      id: 'chem-3.8',
      ced: ['3.8'],
      title: 'Drawing Solutions at the Particle Level',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'On the AP exam you might be asked to **draw** what a solution looks like up close. A few simple rules turn that into easy points.',
        },
        {
          kind: 'concept',
          title: 'What a good particle diagram shows',
          body: '1. **Correct ratios:** for 0.1 M MgCl₂, draw twice as many Cl⁻ as Mg²⁺. Ionic solutes are drawn as **separate ions**, not as "MgCl₂ molecules".\n2. **Relative concentration:** a more concentrated solution has more solute particles in the same space.\n3. **Correct orientation of water:**\n- Around **cations (+)**: water\'s **O end (δ−)** points toward the ion.\n- Around **anions (−)**: water\'s **H ends (δ+)** point toward the ion.',
        },
        {
          kind: 'hack',
          title: 'Opposites face each other',
          body: 'Picture water as a tiny "Mickey Mouse head": O is the face (δ−) and the two H atoms are the ears (δ+).\n\n**Cation? Show it the face. Anion? Show it the ears.**',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.8-t1',
            type: 'mcq',
            prompt: 'In a correct particle diagram of NaCl(aq), how should water molecules be oriented around **Cl⁻**?',
            choices: [
              'Oxygen atoms pointing toward Cl⁻',
              'Hydrogen atoms pointing toward Cl⁻',
              'Randomly',
              'Water should not be drawn near ions',
            ],
            answer: 1,
            explain: 'Cl⁻ is negative, so it attracts the **δ+ hydrogen** ends of water.',
          },
        },
        {
          kind: 'trap',
          body: 'Good news: the AP exam does **not** test colligative properties (like freezing point depression), and it does **not** ask you to calculate molality, mass percent or volume percent of solutions. Molarity is the star.',
        },
        {
          kind: 'summary',
          points: [
            'Show ions separated, in the correct ratio.',
            'More concentrated = more solute particles per volume.',
            'Water: the O end faces cations, the H ends face anions.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.8-q1',
          type: 'mcq',
          prompt: 'A particle diagram of K₂SO₄(aq) should show…',
          choices: [
            'K₂SO₄ units intact',
            '2 K⁺ for every 1 SO₄²⁻, separated in solution',
            '1 K⁺ for every 1 SO₄²⁻',
            'K, S and O atoms all separated',
          ],
          answer: 1,
          explain: 'Ionic compounds dissociate into their ions: K₂SO₄ → **2 K⁺ + SO₄²⁻**. The polyatomic sulfate ion stays together.',
        },
        {
          id: 'c3.8-q2',
          type: 'mcq',
          prompt: 'Beaker A shows 4 solute particles and beaker B shows 8 solute particles in the same volume. Compared to A, the concentration of B is…',
          choices: ['half', 'the same', 'double', 'impossible to compare'],
          answer: 2,
          explain: 'Twice as many solute particles in the same volume → **double** the concentration.',
        },
      ],
      flashcards: [
        { front: 'Water orientation around a cation', back: 'The **O end (δ−)** points toward the cation.' },
        { front: 'Water orientation around an anion', back: 'The **H ends (δ+)** point toward the anion.' },
      ],
    },
    {
      id: 'chem-3.10',
      ced: ['3.10'],
      title: 'Solubility: Like Dissolves Like',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'Why does oil float on water instead of mixing in? And why does nail polish remover (acetone) clean off paint when water can\'t? Solubility is all about **matching** intermolecular forces.',
        },
        {
          kind: 'concept',
          title: 'Like dissolves like',
          body: 'Substances with **similar intermolecular interactions** tend to be **soluble or miscible** (mix in all proportions) in each other.\n\n- **Polar/ionic solutes** dissolve in **polar solvents** like water: NaCl, sugar, ethanol.\n- **Nonpolar solutes** dissolve in **nonpolar solvents** like hexane: oils, fats, I₂.\n\nWhen the solute–solvent attractions are similar to (or stronger than) the attractions being broken, mixing happens.',
        },
        {
          kind: 'concept',
          title: 'Why oil and water don\'t mix',
          body: 'Water molecules are strongly hydrogen-bonded to each other. Nonpolar oil molecules can offer only weak LDFs. For oil to dissolve, water would have to give up its strong H-bonds in exchange for weak attractions.\n\nSo the water molecules "stick together" and the oil gets squeezed out into a separate layer.',
        },
        {
          kind: 'hack',
          title: 'Long tails lose',
          body: 'Alcohols have a polar O–H "head" and a nonpolar carbon "tail". The longer the tail, the less water-soluble:\n\nmethanol, ethanol: mix completely with water\n1-butanol: only partly soluble\n1-octanol: barely soluble\n\nThe nonpolar part takes over as the chain grows.',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.10-t1',
            type: 'mcq',
            prompt: 'Which substance is most soluble in **hexane, C₆H₁₄** (nonpolar)?',
            choices: ['NaCl', 'I₂', 'CH₃OH', 'KNO₃'],
            answer: 1,
            explain: '**I₂** is nonpolar (LDFs only), so it matches hexane. The ionic and highly polar choices prefer water.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Similar IMFs → soluble/miscible. "Like dissolves like."',
            'Polar/ionic ↔ polar solvents. Nonpolar ↔ nonpolar solvents.',
            'A longer nonpolar chain → lower water solubility.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.10-q1',
          type: 'mcq',
          prompt: 'Ethanol (CH₃CH₂OH) mixes completely with water because…',
          choices: [
            'it is ionic',
            'it can hydrogen bond with water',
            'it is nonpolar',
            'it reacts with water',
          ],
          answer: 1,
          explain: 'Ethanol\'s O–H group lets it **hydrogen bond with water**, so their attractions are similar. Like dissolves like.',
        },
        {
          id: 'c3.10-q2',
          type: 'mcq',
          prompt: 'Which is **least** soluble in water?',
          choices: ['CH₃OH', 'CH₃CH₂OH', 'CH₃(CH₂)₇OH', 'NH₃'],
          answer: 2,
          explain: '1-octanol, **CH₃(CH₂)₇OH**, has a long nonpolar carbon tail that dominates, so it\'s barely water-soluble.',
        },
      ],
      flashcards: [
        { front: '"Like dissolves like" means…', back: 'Substances with similar intermolecular interactions tend to be soluble/miscible in each other.' },
        { front: 'Miscible', back: 'Two liquids that mix in **all proportions**.' },
      ],
    },
    {
      id: 'chem-3.9',
      ced: ['3.9'],
      title: 'Separating Mixtures: Chromatography & Distillation',
      level: 'core',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'Forensic scientists can tell which pen wrote a ransom note by separating its ink into colors. That trick, **chromatography**, works because different molecules "stick" to paper with different strengths.',
        },
        {
          kind: 'concept',
          title: 'Filtration can\'t separate a solution',
          body: 'Dissolved particles are as small as molecules or ions. They pass right through filter paper. To separate the components of a solution, you need methods based on **differences in intermolecular interactions**.',
        },
        {
          kind: 'concept',
          title: 'Chromatography',
          body: 'Two phases compete for each component:\n- the **mobile phase** (the moving solvent)\n- the **stationary phase** (the paper, TLC plate or column packing)\n\nA component attracted **more strongly to the stationary phase** moves **less**. One attracted more strongly to the **mobile phase** travels **farther**.\n\n**R_{f} = distance traveled by the component ÷ distance traveled by the solvent front**\n\nThe chromatogram lets you infer **relative polarities**.',
          diagram: 'chromatogram',
        },
        {
          kind: 'example',
          title: 'Reading a chromatogram',
          problem: 'Paper (polar) is used with a **nonpolar** solvent. Spot A has R_{f} = 0.77 and spot B has R_{f} = 0.27. Which is more polar?',
          steps: [
            'The stationary phase (paper) is **polar**, so polar molecules are attracted to it and move slowly.',
            'B moved the least (lowest R_{f}) → it interacts most strongly with the polar paper.',
            'So **B is more polar** and A is less polar (it prefers the nonpolar solvent).',
          ],
          answer: 'B is more polar.',
        },
        {
          kind: 'concept',
          title: 'Distillation',
          body: 'Distillation separates liquids by boiling point, which is really a difference in **IMF strength and vapor pressure**. The component with **weaker IMFs** (higher vapor pressure, lower boiling point) vaporizes first and is collected first.',
        },
        {
          kind: 'trap',
          body: 'Don\'t assume "high R_{f} = polar." It **depends on the phases**. Always ask: which phase is polar, and which one does this component like more?',
        },
        {
          kind: 'summary',
          points: [
            'Filtration can\'t separate dissolved particles.',
            'Chromatography: a stronger attraction to the stationary phase → lower R_{f}.',
            'Distillation: the weaker-IMF (lower bp) liquid comes off first.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.9-q1',
          type: 'num',
          prompt: 'A dye spot travels **3.0 cm** while the solvent front travels **12.0 cm**. What is its R_{f}?',
          answer: 0.25,
          explain: 'R_{f} = 3.0 ÷ 12.0 = **0.25**',
          compute: () => 3.0 / 12.0,
        },
        {
          id: 'c3.9-q2',
          type: 'mcq',
          prompt: 'A mixture of ethanol (bp 78 °C) and water (bp 100 °C) is distilled. Which is collected first, and why?',
          choices: [
            'Water, because it has hydrogen bonds',
            'Ethanol, because its IMFs are weaker overall, giving it a higher vapor pressure',
            'Both at the same time',
            'Ethanol, because it is heavier',
          ],
          answer: 1,
          explain: 'Ethanol\'s overall IMFs are weaker than water\'s (water forms more H-bonds per molecule), so **ethanol** has the higher vapor pressure and boils off first.',
        },
        {
          id: 'c3.9-q3',
          type: 'mcq',
          prompt: 'Why can\'t filtration separate salt from salt water?',
          choices: [
            'Salt is too heavy',
            'Dissolved ions are small enough to pass through the filter',
            'Water reacts with the filter',
            'Salt dissolves the filter paper',
          ],
          answer: 1,
          explain: 'In solution, Na⁺ and Cl⁻ are individual **ions**, far too small to be trapped by filter paper.',
        },
      ],
      flashcards: [
        { front: 'R_{f} formula', back: 'distance traveled by the component ÷ distance traveled by the solvent front' },
        { front: 'In chromatography, which components travel the shortest distance?', back: 'Those most strongly attracted to the **stationary** phase.' },
        { front: 'In distillation, which liquid comes off first?', back: 'The one with **weaker IMFs** (higher vapor pressure, lower bp).' },
      ],
    },
    {
      id: 'chem-3.11',
      ced: ['3.11'],
      title: 'Spectroscopy & the EM Spectrum',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'A microwave oven heats food by making water molecules **spin**. Infrared lamps make molecules **vibrate**. Sunlight can **excite electrons** and give you a sunburn. Different light does different things to molecules!',
        },
        {
          kind: 'concept',
          title: 'Which light does what',
          body: '| Region | Effect on molecules |\n| **Microwave** | changes in **rotational** levels (molecules spin) |\n| **Infrared (IR)** | changes in **vibrational** levels (bonds stretch and bend) |\n| **Ultraviolet / visible (UV-vis)** | **electronic** transitions (electrons jump between energy levels) |\n\nMore energetic light → a "bigger" change: rotation < vibration < electronic.',
          diagram: 'em-spectrum',
        },
        {
          kind: 'hack',
          title: '"My Insides Vibrate, Electrons Ultra-jump"',
          body: '**M**icrowave → rotation (think: food **rotating** in the microwave 🍕)\n**I**nfrared → **V**ibration\n**U**V/visible → **E**lectrons\n\nOrder of energy: microwave < IR < visible < UV.',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.11-t1',
            type: 'mcq',
            prompt: 'Which type of radiation causes transitions between **vibrational** energy levels of a molecule?',
            choices: ['Microwave', 'Infrared', 'Ultraviolet', 'Radio'],
            answer: 1,
            explain: '**Infrared** radiation matches the energy of molecular **vibrations** (bond stretching and bending).',
          },
        },
        {
          kind: 'summary',
          points: [
            'Microwave → rotation. Infrared → vibration. UV/visible → electronic transitions.',
            'Energy order: microwave < IR < visible < UV.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.11-q1',
          type: 'mcq',
          prompt: 'A solution looks blue because its molecules absorb some visible light. This absorption involves…',
          choices: ['rotational transitions', 'vibrational transitions', 'electronic transitions', 'nuclear changes'],
          answer: 2,
          explain: 'Visible (and UV) light has enough energy to promote **electrons** to higher energy levels: **electronic transitions**.',
        },
        {
          id: 'c3.11-q2',
          type: 'mcq',
          prompt: 'Which correctly orders the radiation types from **lowest to highest** photon energy?',
          choices: ['UV < visible < IR < microwave', 'microwave < IR < visible < UV', 'IR < microwave < UV < visible', 'visible < UV < IR < microwave'],
          answer: 1,
          explain: 'Energy increases with frequency: **microwave < IR < visible < UV**.',
        },
      ],
      flashcards: [
        { front: 'Microwave radiation causes…', back: 'Transitions in **rotational** levels' },
        { front: 'Infrared radiation causes…', back: 'Transitions in **vibrational** levels' },
        { front: 'UV/visible radiation causes…', back: '**Electronic** transitions' },
      ],
    },
    {
      id: 'chem-3.12',
      ced: ['3.12'],
      title: 'Properties of Photons',
      level: 'core',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'Neon signs glow red, and sodium streetlights glow orange-yellow. Each color is a photon with an **exact** energy, released when an electron drops to a lower level. Light is how atoms "talk".',
        },
        {
          kind: 'concept',
          title: 'Energy in, energy out',
          body: 'When an atom or molecule **absorbs** a photon, its energy **increases** by exactly the photon\'s energy. When it **emits** a photon, its energy **decreases** by that amount.\n\n**ΔE (of the atom) = E (of the photon)**',
        },
        {
          kind: 'concept',
          title: 'The two photon equations',
          body: '**c = λν**: speed of light = wavelength × frequency\n**E = hν**: photon energy = Planck\'s constant × frequency\n\n- c = 2.998 × 10^{8} m/s\n- h = 6.626 × 10^{-34} J·s\n\nShorter λ ↔ higher ν ↔ **higher energy**.',
        },
        {
          kind: 'example',
          title: 'Green light',
          problem: 'Find the energy of one photon of **500. nm** light.',
          steps: [
            'Convert the wavelength: 500. nm = 500. × 10^{-9} m = 5.00 × 10^{-7} m',
            'Frequency: ν = c/λ = (2.998 × 10^{8}) / (5.00 × 10^{-7}) = **6.00 × 10^{14} s^{-1}**',
            'Energy: E = hν = (6.626 × 10^{-34})(6.00 × 10^{14}) = **3.97 × 10^{-19} J**',
          ],
          answer: '3.97 × 10^{-19} J per photon',
          verify: [
            { stated: 6.0e14, compute: () => 2.998e8 / 5.0e-7, tol: 0.005 },
            { stated: 3.97e-19, compute: () => (6.626e-34 * 2.998e8) / 5.0e-7 },
          ],
        },
        {
          kind: 'hack',
          title: 'One combined formula',
          body: 'Combine them: **E = hc/λ**. One step instead of two!\n\nAnd always convert **nm → m** (× 10^{-9}) first. A mismatched unit is the most common photon mistake.\n\nPer mole of photons? Multiply by Avogadro\'s number.',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.12-t1',
            type: 'num',
            prompt: 'What is the **frequency** of light with a wavelength of **600. nm**?',
            answer: 4.997e14,
            unit: 's^{-1}',
            hint: 'ν = c/λ. Convert nm to m.',
            explain: 'ν = (2.998 × 10^{8} m/s) / (6.00 × 10^{-7} m) = **5.00 × 10^{14} s^{-1}**',
            compute: () => 2.998e8 / 6.0e-7,
          },
        },
        {
          kind: 'summary',
          points: [
            'Absorb a photon → the atom\'s energy goes up by E_photon. Emit → it goes down.',
            'c = λν and E = hν (so E = hc/λ).',
            'Shorter wavelength = higher energy. Convert nm to m!',
          ],
        },
      ],
      check: [
        {
          id: 'c3.12-q1',
          type: 'num',
          prompt: 'A photon has a frequency of **1.0 × 10^{15} s^{-1}**. What is its energy?',
          answer: 6.626e-19,
          unit: 'J',
          explain: 'E = hν = (6.626 × 10^{-34})(1.0 × 10^{15}) = **6.6 × 10^{-19} J**',
          compute: () => 6.626e-34 * 1.0e15,
        },
        {
          id: 'c3.12-q2',
          type: 'mcq',
          prompt: 'Photon X has a **longer wavelength** than photon Y. Compared to Y, photon X has…',
          choices: ['higher frequency and higher energy', 'lower frequency and lower energy', 'higher frequency and lower energy', 'the same energy'],
          answer: 1,
          explain: 'Longer λ → lower ν (c = λν) → **lower E** (E = hν).',
        },
        {
          id: 'c3.12-q3',
          type: 'mcq',
          prompt: 'An electron in an atom drops from a higher energy level to a lower one. What happens?',
          choices: [
            'A photon is absorbed',
            'A photon is emitted, with energy equal to the energy difference between the levels',
            'The atom gains energy',
            'Nothing is released',
          ],
          answer: 1,
          explain: 'Dropping to a lower level **releases** energy as a photon whose energy **equals the difference** between the levels.',
        },
      ],
      flashcards: [
        { front: 'Speed of light equation', back: 'c = λν' },
        { front: 'Planck\'s equation', back: 'E = hν, with h = 6.626 × 10^{-34} J·s' },
        { front: 'Wavelength and energy relationship', back: 'Inverse: shorter λ → higher energy (E = hc/λ).' },
      ],
    },
    {
      id: 'chem-3.13',
      ced: ['3.13'],
      title: 'Beer–Lambert Law',
      level: 'core',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'The darker the tea, the stronger it is. A **spectrophotometer** turns that idea into precise numbers. Labs use it to measure concentrations without any chemical reaction at all.',
        },
        {
          kind: 'concept',
          title: 'A = εbc',
          body: '- **A** = absorbance (no units)\n- **ε** = molar absorptivity: how strongly that substance absorbs a particular wavelength (M^{-1}cm^{-1})\n- **b** = path length, the width of the cuvette (cm, usually 1.00 cm)\n- **c** = concentration (M)\n\nIn most experiments, b and the wavelength are held constant, so **absorbance is directly proportional to concentration**.',
        },
        {
          kind: 'concept',
          title: 'Calibration curves',
          body: 'Measure A for several solutions of known concentration → plot them → straight line. Then measure the unknown\'s A and read its concentration from the line.\n\nSet the instrument to the wavelength of **maximum absorbance (λ_{max})** for the best sensitivity.',
          diagram: 'beer-calibration',
        },
        {
          kind: 'example',
          title: 'Find the concentration',
          problem: 'A dye has ε = 1.50 × 10^{4} M^{-1}cm^{-1}. A solution in a 1.00 cm cuvette has **A = 0.450**. What is its concentration?',
          steps: ['Rearrange: c = A / (εb)', 'c = 0.450 / [(1.50 × 10^{4})(1.00)] = **3.00 × 10^{-5} M**'],
          answer: '3.00 × 10^{-5} M',
          verify: [{ stated: 3.0e-5, compute: () => 0.45 / (1.5e4 * 1.0) }],
        },
        {
          kind: 'frq',
          title: 'Lab error questions',
          body: 'AP often asks how an error affects a result. Think: **does the measured A go up or down?**\n\n- Fingerprints or scratches on the cuvette → **A too high** → calculated c **too high**.\n- Cuvette still wet with water (dilutes the sample) → **A too low** → c **too low**.\n- Wavelength set away from λ_{max} → lower sensitivity (smaller A values for every solution).\n\nState the direction AND the reason.',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.13-t1',
            type: 'mcq',
            prompt: 'At constant ε and b, if the concentration of a solution is **tripled**, its absorbance…',
            choices: ['is cut to one-third', 'stays the same', 'triples', 'increases 9 times'],
            answer: 2,
            explain: 'A = εbc, so A ∝ c. Triple c → **triple A**.',
          },
        },
        {
          kind: 'summary',
          points: [
            'A = εbc. With b and λ fixed, A ∝ concentration.',
            'Use a calibration line from standards to find unknown concentrations.',
            'Measure at λ_max for maximum sensitivity. For errors, ask: does A go up or down?',
          ],
        },
      ],
      check: [
        {
          id: 'c3.13-q1',
          type: 'num',
          prompt: 'A solution with c = 2.0 × 10^{-4} M has A = 0.300 in a 1.00 cm cuvette. What is ε?',
          answer: 1500,
          unit: 'M^{-1}cm^{-1}',
          explain: 'ε = A/(bc) = 0.300 / (1.00 × 2.0 × 10^{-4}) = **1.5 × 10^{3} M^{-1}cm^{-1}**',
          compute: () => 0.3 / (1.0 * 2.0e-4),
        },
        {
          id: 'c3.13-q2',
          type: 'mcq',
          prompt: 'A student forgets to wipe a fingerprint off the cuvette before measuring an unknown. The calculated concentration will be…',
          choices: ['too high', 'too low', 'unaffected', 'zero'],
          answer: 0,
          explain: 'The fingerprint blocks extra light → measured A is **higher** than it should be → calculated concentration is **too high**.',
        },
        {
          id: 'c3.13-q3',
          type: 'mcq',
          prompt: 'Why is a spectrophotometer usually set to the wavelength of maximum absorbance?',
          choices: [
            'It makes the solution more concentrated',
            'It gives the greatest sensitivity to changes in concentration',
            'It is the only wavelength where Beer\'s law works',
            'It reduces the path length',
          ],
          answer: 1,
          explain: 'At λ_max, a small change in concentration produces the **largest change in absorbance**: maximum sensitivity.',
        },
      ],
      flashcards: [
        { front: 'Beer–Lambert law', back: 'A = εbc' },
        { front: 'Why measure at λ_max?', back: 'Maximum **sensitivity** of absorbance to concentration.' },
      ],
    },
    // ---------------- ADVANCED ----------------
    {
      id: 'chem-3.6',
      ced: ['3.6'],
      title: 'Real Gases vs. Ideal Gases',
      level: 'advanced',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'PV = nRT pretends gas particles have **no volume** and **no attractions**. That\'s a great approximation… until you squeeze a gas really hard or cool it until it\'s about to turn into a liquid.',
        },
        {
          kind: 'concept',
          title: 'Two assumptions that break down',
          body: '**1. "Particles have no volume."**\nAt **very high pressure**, the particles are crammed together, and their own volume becomes a real fraction of the container. The actual volume is **larger** than PV = nRT predicts.\n\n**2. "Particles don\'t attract each other."**\nAt **low temperature** (near condensation), particles move slowly, so attractions matter. They pull on each other and hit the walls less hard → the actual pressure is **lower** than predicted.',
        },
        {
          kind: 'hack',
          title: 'Most ideal vs. least ideal',
          body: '**Most ideal:** high T, low P, small nonpolar particles (He is the champion).\n**Least ideal:** low T, high P, large or polar particles with strong IMFs (like H₂O vapor or NH₃).\n\nMemory trick: gases are most ideal when they\'re "**hot and lonely**" (high T, low P).',
        },
        {
          kind: 'try',
          question: {
            id: 'c3.6-t1',
            type: 'mcq',
            prompt: 'Which gas would deviate **most** from ideal behavior under the same conditions?',
            choices: ['He', 'Ne', 'CH₄', 'NH₃'],
            answer: 3,
            hint: 'Which particles attract each other the most?',
            explain: '**NH₃** is polar and forms hydrogen bonds, so its particles attract strongly → the biggest deviation from ideal behavior.',
          },
        },
        {
          kind: 'frq',
          body: 'To explain a deviation, connect the **condition** to the **assumption** to the **direction**:\n\n"At high pressure, the volume of the gas particles is no longer negligible compared with the container volume, so the measured volume is greater than the ideal gas law predicts."\n\n"At low temperature, attractions between particles reduce the force of collisions with the walls, so the measured pressure is lower than predicted."',
        },
        {
          kind: 'summary',
          points: [
            'High pressure → particle volume matters → actual V > ideal.',
            'Low temperature / strong IMFs → attractions matter → actual P < ideal.',
            'Most ideal: high T, low P, small nonpolar gases.',
          ],
        },
      ],
      check: [
        {
          id: 'c3.6-q1',
          type: 'mcq',
          prompt: 'Under which conditions does a real gas behave **most** like an ideal gas?',
          choices: ['Low T, high P', 'High T, low P', 'Low T, low P', 'High T, high P'],
          answer: 1,
          explain: '**High T** (attractions don\'t matter) and **low P** (particle volume is negligible) → nearly ideal.',
        },
        {
          id: 'c3.6-q2',
          type: 'mcq',
          prompt: 'A sample of CO₂ near its condensation point has a measured pressure **lower** than PV = nRT predicts. The main reason is…',
          choices: [
            'the volume of the CO₂ molecules',
            'attractions between CO₂ molecules reduce the force of their wall collisions',
            'CO₂ molecules move faster than expected',
            'the container leaks',
          ],
          answer: 1,
          explain: 'Near condensation, particles are slow and **intermolecular attractions** pull them back, weakening wall collisions → lower pressure.',
        },
      ],
      flashcards: [
        { front: 'Why does a real gas have V > ideal at very high P?', back: 'The particles\' own volume is no longer negligible.' },
        { front: 'Why does a real gas have P < ideal at low T?', back: 'Intermolecular attractions reduce the force and frequency of wall collisions.' },
        { front: 'Conditions for ideal behavior', back: 'High temperature, low pressure (small, nonpolar gas).' },
      ],
    },
  ],
  checkpoint: [
    {
      id: 'c3-cp1',
      type: 'mcq',
      prompt: 'Which has the **lowest** boiling point?',
      choices: ['CH₃CH₂OH', 'CH₃OCH₃', 'H₂O', 'HOCH₂CH₂OH'],
      answer: 1,
      explain: '**CH₃OCH₃** can\'t hydrogen bond with itself (no O–H). All the others can, so it has the weakest IMFs and the lowest bp.',
    },
    {
      id: 'c3-cp2',
      type: 'num',
      prompt: 'What is the density of **O₂ gas at STP**? (Use M = dRT/P, or 32.00 g ÷ 22.4 L.)',
      answer: 1.429,
      unit: 'g/L',
      tolerance: 0.01,
      explain: 'd = PM/RT = (1.0)(32.00) / (0.08206 × 273.15) = **1.43 g/L**',
      compute: () => (1.0 * 32.0) / (R * 273.15),
    },
    {
      id: 'c3-cp3',
      type: 'mcq',
      prompt: 'Which statement about 1 mol of H₂ and 1 mol of CO₂, both at 300 K, is correct?',
      choices: [
        'H₂ has greater average KE',
        'They have equal average KE, and H₂ has the greater average speed',
        'CO₂ has the greater average speed',
        'They have equal average speeds',
      ],
      answer: 1,
      explain: 'Same T → same average KE. Lighter H₂ → **faster**.',
    },
    {
      id: 'c3-cp4',
      type: 'num',
      prompt: 'What mass of KCl is needed to make **500.0 mL of 0.250 M KCl**? (KCl = 74.55 g/mol)',
      answer: 9.32,
      unit: 'g',
      explain: 'mol = 0.250 × 0.5000 = 0.125 mol. Mass = 0.125 × 74.55 = **9.32 g**',
      compute: () => 0.25 * 0.5 * molarMass('KCl'),
    },
    {
      id: 'c3-cp5',
      type: 'mcq',
      prompt: 'SiO₂ (quartz) melts at about 1700 °C, while CO₂ sublimes at −78 °C. The best explanation is…',
      choices: [
        'Si is heavier than C',
        'SiO₂ is a covalent network solid; solid CO₂ is a molecular solid held by weak LDFs',
        'CO₂ is ionic',
        'SiO₂ has hydrogen bonds',
      ],
      answer: 1,
      explain: 'Melting SiO₂ requires breaking **covalent bonds** in a network. Subliming CO₂ only overcomes **weak LDFs** between molecules.',
    },
  ],
}
