import type { Unit } from '../types'
import { CONST, molarMass } from '../../lib/chem'

const R = CONST.R_Latm

export const unit4: Unit = {
  id: 'chem-u4',
  number: 4,
  title: 'Chemical Reactions',
  weight: '7–9%',
  blurb:
    'Writing and balancing reactions, net ionic equations, stoichiometry, titrations, and the three big reaction types: precipitation, acid–base and redox.',
  badge: { name: 'Reaction Ranger', emoji: '💥' },
  lessons: [
    // ---------------- FOUNDATION ----------------
    {
      id: 'chem-4.1',
      ced: ['4.1', '4.4'],
      title: 'Physical vs. Chemical Changes',
      level: 'foundation',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'Melting ice and burning wood both change how something looks. But you can refreeze water, and you can\'t "unburn" ash. What\'s the real difference?',
        },
        {
          kind: 'concept',
          title: 'The definitions',
          body: '**Physical change:** no change in composition. The same substances, just in a different form.\n→ phase changes (melting, boiling), dissolving, mixing or separating mixtures\n\n**Chemical change:** **new substances** form, typically with a different composition.\n→ burning, rusting, cooking, neutralization',
        },
        {
          kind: 'concept',
          title: 'Evidence of a chemical change',
          body: 'Clues that a chemical reaction may have happened:\n\n- 🔥 production of **heat or light**\n- 🫧 **gas** formation (bubbles), when not just boiling\n- ☁️ a **precipitate** (a solid forming from solutions)\n- 🎨 a **color change**\n\nThese are *possible* evidence, not proof. Boiling water makes bubbles too!',
        },
        {
          kind: 'concept',
          title: 'The particle-level view',
          body: '- **Chemical** processes typically **break and/or form chemical bonds** (covalent, ionic or metallic).\n- **Physical** processes typically change only **intermolecular interactions**.\n\n**The gray zone:** dissolving NaCl in water **breaks ionic bonds** and forms **ion–dipole** attractions. You can argue it\'s physical (no new substances) or chemical (bonds break). AP accepts a well-supported argument either way.',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.1-t1',
            type: 'mcq',
            prompt: 'Which is a **chemical** change?',
            choices: ['Dry ice subliming', 'Sugar dissolving in tea', 'An iron nail rusting', 'Salt water being boiled dry'],
            answer: 2,
            explain: 'Rusting forms a **new substance** (iron oxide) as bonds break and form. The others are phase changes or dissolving/separating.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Physical: same substances, and typically only IMFs change.',
            'Chemical: new substances, and bonds break and form.',
            'Evidence: heat or light, gas, precipitate, color change.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.1-q1',
          type: 'mcq',
          prompt: 'Two clear solutions are mixed and a yellow solid appears. This is evidence of…',
          choices: ['a physical change, because nothing was heated', 'a chemical change, because a precipitate formed', 'dissolving', 'a phase change'],
          answer: 1,
          explain: 'A new solid (a **precipitate**) forming from solutions is evidence that a **chemical change** happened.',
        },
        {
          id: 'c4.1-q2',
          type: 'mcq',
          prompt: 'When liquid bromine evaporates, what is overcome at the particle level?',
          choices: ['Br–Br covalent bonds', 'London dispersion forces between Br₂ molecules', 'Ionic bonds', 'Nuclear forces'],
          answer: 1,
          explain: 'Evaporation is **physical**: only the **intermolecular forces** (LDFs) between Br₂ molecules are overcome. The Br–Br bonds stay intact.',
        },
      ],
      flashcards: [
        { front: 'Physical vs. chemical change (particle level)', back: 'Physical: only IMFs change. Chemical: bonds break/form and new substances appear.' },
        { front: 'Four kinds of evidence for a chemical change', back: 'Heat/light, gas, precipitate, color change' },
      ],
    },
    {
      id: 'chem-4.5a',
      ced: ['4.5'],
      title: 'Stoichiometry: The Mole Ratio',
      level: 'foundation',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'A recipe says 2 eggs for every 1 cup of flour. How many eggs for 3 cups? Easy: 6! **Stoichiometry is just following a chemical recipe**, and the balanced equation *is* the recipe.',
        },
        {
          kind: 'concept',
          title: 'Coefficients are mole ratios',
          body: '[[eq: N2(g) + 3H2(g) -> 2NH3(g)]]\n\nRead it as: **1 mol N₂** reacts with **3 mol H₂** to make **2 mol NH₃**.\n\nThe coefficients compare **moles** (or molecules), **not grams**. Atoms are conserved, so you can predict product amounts from reactants and the other way around.',
        },
        {
          kind: 'hack',
          title: 'The stoichiometry bridge 🌉',
          body: '**grams A → moles A → moles B → grams B**\n\n1. ÷ molar mass of A\n2. × **mole ratio** (coefficient B / coefficient A), the bridge between substances\n3. × molar mass of B\n\nYou can only cross from A to B on the **mole** level!',
        },
        {
          kind: 'example',
          title: 'Making ammonia',
          problem: 'How many grams of NH₃ can be made from **10.0 g of H₂** (with plenty of N₂)?',
          steps: [
            'grams → moles: 10.0 g H₂ ÷ 2.016 g/mol = **4.96 mol H₂**',
            'Mole ratio: 4.96 mol H₂ × (2 mol NH₃ / 3 mol H₂) = **3.31 mol NH₃**',
            'moles → grams: 3.31 mol × 17.03 g/mol = **56.3 g NH₃**',
          ],
          answer: '56.3 g NH₃',
          verify: [
            { stated: 4.96, compute: () => 10.0 / molarMass('H2') },
            { stated: 3.31, compute: () => ((10.0 / molarMass('H2')) * 2) / 3 },
            { stated: 56.3, compute: () => (((10.0 / molarMass('H2')) * 2) / 3) * molarMass('NH3') },
          ],
        },
        {
          kind: 'try',
          question: {
            id: 'c4.5a-t1',
            type: 'num',
            prompt: '[[eq: 2H2(g) + O2(g) -> 2H2O(l)]] How many moles of O₂ are needed to react with **6.0 mol H₂**?',
            answer: 3.0,
            unit: 'mol',
            hint: 'Mole ratio O₂ : H₂ = 1 : 2.',
            explain: '6.0 mol H₂ × (1 mol O₂ / 2 mol H₂) = **3.0 mol O₂**',
            compute: () => 6.0 / 2,
          },
        },
        {
          kind: 'trap',
          body: '**Never use the coefficients with grams.** "2 g of H₂ reacts with 1 g of O₂" is wrong. The 2 : 1 ratio is in **moles**. Convert to moles first, always.',
        },
        {
          kind: 'summary',
          points: [
            'Balanced coefficients = mole ratios.',
            'g A → mol A → (mole ratio) → mol B → g B.',
            'Never apply the coefficients directly to grams.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.5a-q1',
          type: 'num',
          prompt: '[[eq: CH4(g) + 2O2(g) -> CO2(g) + 2H2O(g)]] What mass of CO₂ forms when **8.00 g of CH₄** burns completely?',
          answer: 21.9,
          unit: 'g',
          hint: 'CH₄ = 16.04 g/mol, CO₂ = 44.01 g/mol, and the mole ratio is 1 : 1.',
          explain: '8.00 g ÷ 16.04 = 0.499 mol CH₄ → 0.499 mol CO₂ × 44.01 = **21.9 g CO₂**',
          compute: () => (8.0 / molarMass('CH4')) * molarMass('CO2'),
        },
        {
          id: 'c4.5a-q2',
          type: 'num',
          prompt: '[[eq: 4Fe(s) + 3O2(g) -> 2Fe2O3(s)]] How many moles of Fe₂O₃ form from **2.0 mol of Fe**?',
          answer: 1.0,
          unit: 'mol',
          explain: '2.0 mol Fe × (2 mol Fe₂O₃ / 4 mol Fe) = **1.0 mol Fe₂O₃**',
          compute: () => (2.0 * 2) / 4,
        },
        {
          id: 'c4.5a-q3',
          type: 'mcq',
          prompt: 'In [[eq: N2(g) + 3H2(g) -> 2NH3(g)]], the "3" in front of H₂ tells you…',
          choices: [
            '3 grams of H₂ react',
            '3 moles (or molecules) of H₂ react per 1 mole of N₂',
            'H₂ has 3 atoms',
            'the reaction takes 3 seconds',
          ],
          answer: 1,
          explain: 'Coefficients give the **mole (or molecule) ratio**: 3 H₂ for every 1 N₂.',
        },
      ],
      flashcards: [
        { front: 'What do coefficients in a balanced equation represent?', back: 'Mole (or particle) ratios, **not** mass ratios.' },
        { front: 'Stoichiometry path', back: 'g A → mol A → × (mole ratio) → mol B → g B' },
      ],
    },
    // ---------------- CORE ----------------
    {
      id: 'chem-4.7a',
      ced: ['4.7'],
      title: 'Types of Reactions & Precipitation',
      level: 'core',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'There are millions of chemical reactions, but AP sorts almost all of them into **three families**: things that swap **protons**, things that swap **electrons**, and ions that team up to form a **solid**.',
        },
        {
          kind: 'concept',
          title: 'The big three',
          body: '| Type | What\'s transferred or formed | Example |\n| **Acid–base** | **protons (H⁺)** move | HCl + NaOH |\n| **Redox** (oxidation–reduction) | **electrons** move (oxidation numbers change) | Zn + Cu²⁺ |\n| **Precipitation** | ions combine into an **insoluble solid** | Ag⁺ + Cl⁻ → AgCl(s) |\n\n**Combustion** is a special kind of redox: a substance reacts with **O₂**. Complete combustion of a hydrocarbon gives **CO₂ + H₂O**.',
        },
        {
          kind: 'concept',
          title: 'The ONE solubility rule you must know',
          body: '**All sodium (Na⁺), potassium (K⁺), ammonium (NH₄⁺) and nitrate (NO₃⁻) salts are soluble in water.**\n\nThat\'s the only rule the AP exam expects you to memorize. Any other solubility information will be given to you in the question.\n\nSo if you mix two solutions and look for a precipitate, the Na⁺/K⁺/NH₄⁺/NO₃⁻ ions **stay dissolved**.',
        },
        {
          kind: 'hack',
          title: '"SNAP" the soluble ions 🫰',
          body: '**S**odium, **N**itrate, **A**mmonium, **P**otassium: always soluble.\n\nWhen predicting a precipitate, cross out every SNAP ion. The **other** two ions are the ones that might form the solid.',
        },
        {
          kind: 'example',
          title: 'Predict the precipitate',
          problem: 'Solutions of **Pb(NO₃)₂** and **KI** are mixed. A yellow solid forms. What is it?',
          steps: [
            'The ions present are Pb²⁺, NO₃⁻, K⁺ and I⁻.',
            'Possible new pairs: KNO₃ and PbI₂.',
            'KNO₃ is a SNAP salt (both K⁺ and NO₃⁻) → soluble. So the solid must be **PbI₂**.',
          ],
          answer: '[[eq: Pb(NO3)2(aq) + 2KI(aq) -> PbI2(s) + 2KNO3(aq)]]',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.7a-t1',
            type: 'mcq',
            prompt: 'Which reaction type is [[eq: 2Mg(s) + O2(g) -> 2MgO(s)]]?',
            choices: ['Precipitation', 'Acid–base', 'Redox', 'No reaction'],
            answer: 2,
            hint: 'Do any oxidation numbers change? Mg goes from 0 to …',
            explain: 'Mg goes from 0 to +2 (it loses electrons) and O goes from 0 to −2 (it gains electrons). Electron transfer = **redox**.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Acid–base = H⁺ transfer. Redox = e⁻ transfer. Precipitation = an insoluble solid forms.',
            'Combustion (+ O₂) is redox. A hydrocarbon burns completely to CO₂ + H₂O.',
            'Na⁺, K⁺, NH₄⁺ and NO₃⁻ salts are ALWAYS soluble.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.7a-q1',
          type: 'mcq',
          prompt: 'Which compound is **definitely soluble** in water based on the AP solubility rule?',
          choices: ['AgCl', 'BaSO₄', '(NH₄)₂CO₃', 'CaCO₃'],
          answer: 2,
          explain: 'It contains **ammonium (NH₄⁺)**, a SNAP ion, so it is always soluble.',
        },
        {
          id: 'c4.7a-q2',
          type: 'mcq',
          prompt: '[[eq: HCl(aq) + NaOH(aq) -> NaCl(aq) + H2O(l)]] is best classified as…',
          choices: ['redox', 'acid–base', 'precipitation', 'combustion'],
          answer: 1,
          explain: 'HCl donates a **proton (H⁺)** to OH⁻, forming water → **acid–base** (neutralization).',
        },
        {
          id: 'c4.7a-q3',
          type: 'mcq',
          prompt: 'What are the products of the **complete combustion** of propane, C₃H₈?',
          choices: ['C and H₂', 'CO and H₂', 'CO₂ and H₂O', 'CH₄ and O₂'],
          answer: 2,
          explain: 'Complete combustion of a hydrocarbon → **CO₂ + H₂O**. [[eq: C3H8(g) + 5O2(g) -> 3CO2(g) + 4H2O(g)]]',
        },
      ],
      flashcards: [
        { front: 'The AP solubility rule', back: 'All **Na⁺, K⁺, NH₄⁺ and NO₃⁻** salts are soluble in water.' },
        { front: 'Acid–base vs. redox', back: 'Acid–base: **proton** transfer. Redox: **electron** transfer.' },
        { front: 'Products of complete hydrocarbon combustion', back: 'CO₂ and H₂O' },
      ],
    },
    {
      id: 'chem-4.2',
      ced: ['4.2'],
      title: 'Net Ionic Equations',
      level: 'core',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'When you mix silver nitrate and salt water, the Na⁺ and NO₃⁻ ions just float around doing nothing, like spectators at a game. A **net ionic equation** shows only the players.',
        },
        {
          kind: 'concept',
          title: 'Three ways to write one reaction',
          body: '**Molecular:**\n[[eq: AgNO3(aq) + NaCl(aq) -> AgCl(s) + NaNO3(aq)]]\n\n**Complete ionic** (split strong electrolytes into ions):\n[[eq: Ag^+(aq) + NO3^-(aq) + Na^+(aq) + Cl^-(aq) -> AgCl(s) + Na^+(aq) + NO3^-(aq)]]\n\n**Net ionic** (cancel the **spectator ions** that appear unchanged on both sides):\n[[eq: Ag^+(aq) + Cl^-(aq) -> AgCl(s)]]',
        },
        {
          kind: 'concept',
          title: 'What to split, what NOT to split',
          body: '**Split into ions:** soluble ionic compounds (aq), strong acids (HCl, HBr, HI, HNO₃, H₂SO₄, HClO₄) and strong bases (Group 1 hydroxides, plus Ca, Sr, Ba hydroxides).\n\n**Keep together:**\n- solids (s), liquids (l), gases (g)\n- **weak acids** like HC₂H₃O₂ or HF, and **weak bases** like NH₃\n- molecular compounds like sugar or H₂O',
        },
        {
          kind: 'hack',
          title: 'The NIE checklist ✅',
          body: '1. Write the balanced molecular equation with states.\n2. Split only the **strong electrolytes (aq)**.\n3. Cross out the ions that are **identical on both sides**.\n4. Check that **atoms AND charges** balance.\n\nCharge must balance in every correct equation. It\'s a free way to check your work!',
        },
        {
          kind: 'example',
          title: 'Weak acid + strong base',
          problem: 'Write the net ionic equation for acetic acid reacting with sodium hydroxide.',
          steps: [
            'Molecular: [[eq: HC2H3O2(aq) + NaOH(aq) -> NaC2H3O2(aq) + H2O(l)]]',
            'HC₂H₃O₂ is a **weak** acid, so keep it together. Split NaOH and NaC₂H₃O₂ (soluble, strong electrolytes).',
            'Na⁺ is a spectator, so cancel it.',
          ],
          answer: '[[eq: HC2H3O2(aq) + OH^-(aq) -> C2H3O2^-(aq) + H2O(l)]]',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.2-t1',
            type: 'mcq',
            prompt: 'What is the net ionic equation for **HNO₃(aq) + KOH(aq)**?',
            choices: [
              '[[eq: HNO3(aq) + KOH(aq) -> KNO3(aq) + H2O(l)]]',
              '[[eq: H^+(aq) + OH^-(aq) -> H2O(l)]]',
              '[[eq: K^+(aq) + NO3^-(aq) -> KNO3(aq)]]',
              'No reaction',
            ],
            answer: 1,
            hint: 'Strong acid + strong base. Which ions are spectators?',
            explain: 'Both are strong electrolytes. K⁺ and NO₃⁻ are spectators → **H⁺ + OH⁻ → H₂O**.',
          },
        },
        {
          kind: 'trap',
          body: 'Don\'t split a precipitate. "AgCl(s)" stays together, since it\'s a solid! And don\'t split weak acids just because they have an H. HF and HC₂H₃O₂ mostly stay as molecules in water.',
        },
        {
          kind: 'summary',
          points: [
            'Molecular → complete ionic → net ionic (cancel the spectators).',
            'Split only soluble strong electrolytes. Keep solids, liquids, gases and weak acids/bases together.',
            'Atoms AND charges must balance.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.2-q1',
          type: 'mcq',
          prompt: 'In the reaction of BaCl₂(aq) with Na₂SO₄(aq), which ions are **spectators**?',
          choices: ['Ba²⁺ and SO₄²⁻', 'Na⁺ and Cl⁻', 'Ba²⁺ and Cl⁻', 'All four ions'],
          answer: 1,
          hint: 'BaSO₄ precipitates. Which ions stay dissolved?',
          explain: 'BaSO₄(s) forms. **Na⁺ and Cl⁻** remain unchanged in solution → spectators. NIE: [[eq: Ba^2+(aq) + SO4^2-(aq) -> BaSO4(s)]]',
        },
        {
          id: 'c4.2-q2',
          type: 'mcq',
          prompt: 'Which is the correct NIE for solid CaCO₃ reacting with excess HCl(aq)?',
          choices: [
            '[[eq: CaCO3(s) + 2H^+(aq) -> Ca^2+(aq) + H2O(l) + CO2(g)]]',
            '[[eq: CO3^2-(aq) + 2H^+(aq) -> H2O(l) + CO2(g)]]',
            '[[eq: Ca^2+(aq) + 2Cl^-(aq) -> CaCl2(s)]]',
            '[[eq: CaCO3(s) + 2HCl(aq) -> CaCl2(aq) + H2O(l) + CO2(g)]]',
          ],
          answer: 0,
          hint: 'CaCO₃ is a solid, so don\'t split it. HCl is a strong acid, so split it.',
          explain: 'Keep **CaCO₃(s)** together, split HCl into H⁺ + Cl⁻, and cancel the spectator Cl⁻.',
        },
        {
          id: 'c4.2-q3',
          type: 'mcq',
          prompt: 'Which substance should be written as **ions** in a net ionic equation?',
          choices: ['HF(aq)', 'NH₃(aq)', 'KBr(aq)', 'H₂O(l)'],
          answer: 2,
          explain: '**KBr(aq)** is a soluble ionic compound (a strong electrolyte), so split it into K⁺ + Br⁻. HF and NH₃ are weak, and H₂O is molecular.',
        },
      ],
      flashcards: [
        { front: 'Spectator ion', back: 'An ion that is unchanged on both sides of the equation, so it is left out of the net ionic equation.' },
        { front: 'The six strong acids', back: 'HCl, HBr, HI, HNO₃, H₂SO₄, HClO₄' },
        { front: 'NIE for any strong acid + strong base', back: '[[eq: H^+(aq) + OH^-(aq) -> H2O(l)]]' },
      ],
    },
    {
      id: 'chem-4.3',
      ced: ['4.3'],
      title: 'Particle Diagrams of Reactions',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'AP questions sometimes show reactions as **pictures of molecules** instead of formulas. If you can translate between pictures and equations, those questions become free points.',
        },
        {
          kind: 'concept',
          title: 'Equations ↔ pictures',
          body: 'A balanced equation can be drawn as a particle diagram (and the other way around):\n\n[[eq: 2H2(g) + O2(g) -> 2H2O(g)]]\n\n**Before:** 2 H–H molecules + 1 O=O molecule\n**After:** 2 H₂O molecules\n\nRules for drawings:\n- **Conserve atoms**: count every atom of each element before and after.\n- Show any **leftover (excess)** reactant molecules in the "after" picture.\n- Ionic compounds dissolved in water → draw them as **separate ions**.',
        },
        {
          kind: 'example',
          title: 'Reading a "before and after" picture',
          problem: 'A "before" box shows **6 H₂** and **2 O₂** molecules. They react to form water. What does the "after" box show?',
          steps: [
            'Each O₂ needs 2 H₂. So 2 O₂ use **4 H₂** and make **4 H₂O**.',
            'H₂ left over: 6 − 4 = **2 H₂**.',
            'Check the atoms. Before: 12 H, 4 O. After: 4 H₂O (8 H, 4 O) + 2 H₂ (4 H) = 12 H, 4 O ✓',
          ],
          answer: '4 H₂O molecules + 2 leftover H₂ molecules. O₂ was the limiting reactant.',
        },
        {
          kind: 'hack',
          title: 'Count atoms, not molecules',
          body: 'The number of **molecules** can change during a reaction (3 molecules became 2 in the water example). The number of **atoms of each element** never does. Always check by counting atoms.',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.3-t1',
            type: 'mcq',
            prompt: 'A diagram shows **4 N₂** and **9 H₂** molecules reacting by [[eq: N2(g) + 3H2(g) -> 2NH3(g)]]. Which reactant is left over, and how much?',
            choices: ['1 N₂ left', '3 H₂ left', '1 H₂ left', 'Nothing is left over'],
            answer: 0,
            hint: '9 H₂ can react with how many N₂?',
            explain: '9 H₂ needs 9/3 = 3 N₂. With 4 N₂ available, **1 N₂ is left over**. 6 NH₃ form.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Translate equations to pictures using the coefficients as molecule counts.',
            'Atoms are conserved, though the number of molecules may change.',
            'Show excess reactant in the "after" picture.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.3-q1',
          type: 'mcq',
          prompt: 'A "before" diagram has 3 CH₄ and 4 O₂ molecules. The reaction is [[eq: CH4(g) + 2O2(g) -> CO2(g) + 2H2O(g)]]. What remains after the reaction?',
          choices: ['2 CO₂, 4 H₂O, 1 CH₄', '3 CO₂, 6 H₂O', '2 CO₂, 4 H₂O, 2 O₂', '1 CO₂, 2 H₂O, 2 CH₄'],
          answer: 0,
          hint: 'O₂ runs out first: 4 O₂ reacts with 2 CH₄.',
          explain: '4 O₂ reacts with 2 CH₄ → 2 CO₂ + 4 H₂O. 3 − 2 = **1 CH₄ left over**.',
        },
        {
          id: 'c4.3-q2',
          type: 'mcq',
          prompt: 'How should 3 formula units of MgCl₂ dissolved in water be drawn?',
          choices: ['3 MgCl₂ clusters', '3 Mg²⁺ and 6 Cl⁻ separate ions', '3 Mg and 3 Cl₂ molecules', '6 Mg²⁺ and 3 Cl⁻'],
          answer: 1,
          explain: 'Soluble ionic compounds dissociate: each MgCl₂ → 1 Mg²⁺ + 2 Cl⁻, so **3 Mg²⁺ and 6 Cl⁻**.',
        },
      ],
      flashcards: [
        { front: 'What is always conserved in a particle diagram of a reaction?', back: 'The number of **atoms** of each element (not necessarily the number of molecules).' },
        { front: 'How do you show a dissolved ionic compound in a particle diagram?', back: 'As **separate ions** in the correct ratio (e.g., MgCl₂ → 1 Mg²⁺ : 2 Cl⁻).' },
      ],
    },
    {
      id: 'chem-4.5b',
      ced: ['4.5'],
      title: 'Limiting Reactant',
      level: 'core',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'You have 10 hot dogs and 8 buns. How many complete hot dogs can you make? **8**. The buns run out first. In chemistry, the reactant that runs out first is the **limiting reactant**, and it decides how much product you get.',
        },
        {
          kind: 'concept',
          title: 'Limiting vs. excess',
          body: '- **Limiting reactant:** used up completely, so it determines the **maximum (theoretical) amount** of product.\n- **Excess reactant:** some is left over.\n\nThe limiting reactant is **not** necessarily the one with the smaller mass, or even the fewest moles. It depends on the **mole ratio**.',
        },
        {
          kind: 'hack',
          title: 'The "product test" method',
          body: 'Calculate how much product **each** reactant could make on its own.\n\n**The smaller answer wins.** That reactant is the limiting one, and that smaller amount is the theoretical yield.\n\nIt avoids comparing ratios directly and always works.',
        },
        {
          kind: 'example',
          title: 'Aluminum + chlorine',
          problem: '[[eq: 2Al(s) + 3Cl2(g) -> 2AlCl3(s)]] **10.0 g Al** reacts with **30.0 g Cl₂**. What mass of AlCl₃ forms?',
          steps: [
            'Moles: Al = 10.0/26.98 = **0.371 mol**. Cl₂ = 30.0/70.90 = **0.423 mol**.',
            'From Al: 0.371 × (2/2) = 0.371 mol AlCl₃. From Cl₂: 0.423 × (2/3) = **0.282 mol AlCl₃** ← smaller',
            '**Cl₂ is limiting.** Mass AlCl₃ = 0.282 mol × 133.33 g/mol = **37.6 g**',
          ],
          answer: '37.6 g AlCl₃ (Cl₂ is the limiting reactant)',
          verify: [
            { stated: 0.371, compute: () => 10.0 / molarMass('Al') },
            { stated: 0.423, compute: () => 30.0 / molarMass('Cl2') },
            { stated: 0.282, compute: () => ((30.0 / molarMass('Cl2')) * 2) / 3 },
            { stated: 37.6, compute: () => (((30.0 / molarMass('Cl2')) * 2) / 3) * molarMass('AlCl3') },
          ],
        },
        {
          kind: 'concept',
          title: 'Percent yield',
          body: 'Real experiments rarely make the full theoretical amount.\n\n**Percent yield = (actual yield ÷ theoretical yield) × 100**\n\nIf the lab above produced 30.1 g of AlCl₃: 30.1/37.6 × 100 = **80.1%**.',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.5b-t1',
            type: 'mcq',
            prompt: '[[eq: 2H2(g) + O2(g) -> 2H2O(l)]] **3.0 mol H₂** reacts with **2.0 mol O₂**. Which is limiting?',
            choices: ['H₂', 'O₂', 'Neither: they are exactly balanced', 'Can\'t tell without masses'],
            answer: 0,
            hint: '2.0 mol O₂ would need 4.0 mol H₂. Do we have that much?',
            explain: '2.0 mol O₂ needs 4.0 mol H₂, but there is only 3.0 → **H₂ runs out first**. (3.0 mol H₂ only needs 1.5 mol O₂.)',
          },
        },
        {
          kind: 'summary',
          points: [
            'The limiting reactant runs out first and sets the maximum product.',
            'Product test: compute the product from each reactant. The smaller result wins.',
            'Percent yield = actual ÷ theoretical × 100.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.5b-q1',
          type: 'num',
          prompt: '[[eq: N2(g) + 3H2(g) -> 2NH3(g)]] **2.0 mol N₂** reacts with **3.0 mol H₂**. How many moles of NH₃ form?',
          answer: 2.0,
          unit: 'mol',
          hint: 'Product test: from N₂ → 4.0 mol. From H₂ → ?',
          explain: 'From N₂: 2.0 × 2 = 4.0 mol. From H₂: 3.0 × 2/3 = **2.0 mol** ← smaller, so H₂ is limiting.',
          compute: () => Math.min(2.0 * 2, (3.0 * 2) / 3),
        },
        {
          id: 'c4.5b-q2',
          type: 'num',
          prompt: 'A reaction has a theoretical yield of **50.0 g**, but only **42.5 g** is collected. What is the percent yield?',
          answer: 85.0,
          unit: '%',
          explain: '42.5 ÷ 50.0 × 100 = **85.0%**',
          compute: () => (42.5 / 50.0) * 100,
        },
        {
          id: 'c4.5b-q3',
          type: 'mcq',
          prompt: 'Which statement about the limiting reactant is always true?',
          choices: [
            'It has the smallest mass',
            'It has the fewest moles',
            'It is completely consumed and determines the maximum amount of product',
            'It is the reactant with the largest coefficient',
          ],
          answer: 2,
          explain: 'The limiting reactant is defined by being **used up first**, which caps the product. Its mass or moles alone don\'t decide that. The ratio does.',
        },
      ],
      flashcards: [
        { front: 'Limiting reactant', back: 'The reactant that runs out first. It determines the theoretical yield.' },
        { front: 'Percent yield', back: '(actual ÷ theoretical) × 100' },
      ],
    },
    {
      id: 'chem-4.5c',
      ced: ['4.5'],
      title: 'Stoichiometry with Gases & Solutions',
      level: 'core',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'Real lab problems rarely hand you grams. They give **liters of gas** or **milliliters of solution**. Good news: moles are still the hub. You just have more ways to get to them.',
        },
        {
          kind: 'concept',
          title: 'Three doors into "moles"',
          body: '| You know… | Moles = |\n| mass (g) | m ÷ M |\n| gas (P, V, T) | PV ÷ RT |\n| solution (M, L) | molarity × liters |\n\nGet to moles, use the **mole ratio**, then leave through whichever door the question asks for.',
        },
        {
          kind: 'example',
          title: 'Solid → gas',
          problem: '[[eq: CaCO3(s) -> CaO(s) + CO2(g)]] What volume of CO₂ at **STP** comes from heating **25.0 g CaCO₃**?',
          steps: [
            'mol CaCO₃ = 25.0 ÷ 100.09 = **0.250 mol**',
            'Mole ratio 1 : 1 → **0.250 mol CO₂**',
            'V at STP = 0.250 mol × 22.4 L/mol = **5.60 L** (or use V = nRT/P)',
          ],
          answer: '5.60 L CO₂',
          verify: [
            { stated: 0.25, compute: () => 25.0 / molarMass('CaCO3') },
            { stated: 5.6, compute: () => ((25.0 / molarMass('CaCO3')) * R * 273.15) / 1.0 },
          ],
        },
        {
          kind: 'example',
          title: 'Solution → precipitate',
          problem: '**50.0 mL of 0.200 M AgNO₃** reacts with excess NaCl. What mass of AgCl precipitates? [[eq: Ag^+(aq) + Cl^-(aq) -> AgCl(s)]]',
          steps: [
            'mol Ag⁺ = 0.200 M × 0.0500 L = **0.0100 mol**',
            '1 : 1 ratio → 0.0100 mol AgCl',
            'mass = 0.0100 × 143.32 g/mol = **1.43 g AgCl**',
          ],
          answer: '1.43 g AgCl',
          verify: [{ stated: 1.43, compute: () => 0.2 * 0.05 * molarMass('AgCl') }],
        },
        {
          kind: 'try',
          question: {
            id: 'c4.5c-t1',
            type: 'num',
            prompt: '[[eq: Zn(s) + 2HCl(aq) -> ZnCl2(aq) + H2(g)]] How many moles of H₂ form from **100. mL of 1.00 M HCl** (with excess Zn)?',
            answer: 0.05,
            unit: 'mol',
            hint: 'mol HCl = M × L. Then the mole ratio is H₂ : HCl = 1 : 2.',
            explain: 'mol HCl = 1.00 × 0.100 = 0.100 mol → × (1/2) = **0.0500 mol H₂**',
            compute: () => (1.0 * 0.1) / 2,
          },
        },
        {
          kind: 'summary',
          points: [
            'Moles from: mass ÷ M, PV/RT, or M × L.',
            'Mole ratio in the middle, every time.',
            'At STP, 1 mol of gas = 22.4 L. Otherwise use PV = nRT.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.5c-q1',
          type: 'num',
          prompt: '[[eq: 2KClO3(s) -> 2KCl(s) + 3O2(g)]] How many grams of KClO₃ are needed to make **0.300 mol O₂**? (KClO₃ = 122.55 g/mol)',
          answer: 24.5,
          unit: 'g',
          explain: '0.300 mol O₂ × (2/3) = 0.200 mol KClO₃ × 122.55 = **24.5 g**',
          compute: () => ((0.3 * 2) / 3) * molarMass('KClO3'),
        },
        {
          id: 'c4.5c-q2',
          type: 'num',
          prompt: 'What volume of **0.500 M H₂SO₄** is needed to react with **0.0400 mol NaOH**? [[eq: H2SO4(aq) + 2NaOH(aq) -> Na2SO4(aq) + 2H2O(l)]]',
          answer: 0.04,
          unit: 'L',
          hint: 'mol H₂SO₄ = 0.0400 ÷ 2. Then L = mol ÷ M.',
          explain: '0.0400 mol NaOH × (1/2) = 0.0200 mol H₂SO₄. V = 0.0200 ÷ 0.500 = **0.0400 L** (40.0 mL)',
          compute: () => 0.04 / 2 / 0.5,
        },
      ],
      flashcards: [
        { front: 'Three ways to get moles', back: 'mass ÷ molar mass · PV/RT · molarity × liters' },
        { front: 'Volume of 1 mol of ideal gas at STP', back: '22.4 L' },
      ],
    },
    {
      id: 'chem-4.6',
      ced: ['4.6'],
      title: 'Introduction to Titration',
      level: 'core',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'How much acid is in your orange juice? A **titration** answers that precisely: add a solution of known concentration drop by drop until the reaction is exactly complete.',
        },
        {
          kind: 'concept',
          title: 'Titration vocabulary',
          body: '- **Analyte:** the solution you\'re investigating (unknown amount)\n- **Titrant:** the solution of **known** concentration, added from a buret. It reacts specifically and completely with the analyte.\n- **Equivalence point:** the moment the analyte is **completely consumed**, when the moles of titrant added exactly match the stoichiometry.\n- **Endpoint:** the **observable** change (like an indicator\'s color change) that signals the equivalence point. Ideally the two are very close.',
          diagram: 'titration-strong',
        },
        {
          kind: 'concept',
          title: 'The key equation at equivalence',
          body: 'At the equivalence point, moles of titrant and analyte are in the **stoichiometric ratio**.\n\nFor a 1 : 1 reaction like HCl + NaOH:\n**M_{acid} × V_{acid} = M_{base} × V_{base}**\n\nFor other ratios (like H₂SO₄ + 2NaOH), use the mole ratio. Don\'t blindly apply MV = MV!',
        },
        {
          kind: 'example',
          title: 'Find the unknown concentration',
          problem: '**25.00 mL** of HCl is titrated with **0.100 M NaOH**. The endpoint is reached after **18.50 mL** of NaOH. What is [HCl]?',
          steps: [
            'mol NaOH = 0.100 M × 0.01850 L = **1.85 × 10^{-3} mol**',
            '1 : 1 ratio → mol HCl = 1.85 × 10^{-3} mol',
            '[HCl] = 1.85 × 10^{-3} mol ÷ 0.02500 L = **0.0740 M**',
          ],
          answer: '[HCl] = 0.0740 M',
          verify: [
            { stated: 1.85e-3, compute: () => 0.1 * 0.0185 },
            { stated: 0.074, compute: () => (0.1 * 0.0185) / 0.025 },
          ],
        },
        {
          kind: 'frq',
          title: 'Lab error reasoning',
          body: 'AP loves asking how a mistake affects the calculated result:\n\n- **Air bubble in the buret tip** that escapes during the titration → the recorded volume of titrant is **too large** → calculated analyte concentration **too high**.\n- **Overshooting the endpoint** (adding too much titrant) → also **too high**.\n- **Rinsing the buret with water** instead of titrant → the titrant gets diluted, so **more volume** is needed → calculated value **too high**.\n\nFollow the chain: error → effect on the measured volume → effect on the result.',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.6-t1',
            type: 'num',
            prompt: '**20.0 mL** of NaOH is neutralized by **15.0 mL of 0.200 M HCl**. What is [NaOH]?',
            answer: 0.15,
            unit: 'M',
            explain: 'mol HCl = 0.200 × 0.0150 = 0.00300 mol = mol NaOH. [NaOH] = 0.00300 ÷ 0.0200 L = **0.150 M**',
            compute: () => (0.2 * 0.015) / 0.02,
          },
        },
        {
          kind: 'summary',
          points: [
            'Titrant (known) is added to analyte (unknown) until the equivalence point.',
            'Equivalence point = analyte completely consumed. Endpoint = the observed signal (color change).',
            'At equivalence, use the mole ratio: mol titrant ↔ mol analyte.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.6-q1',
          type: 'mcq',
          prompt: 'The **endpoint** of a titration is…',
          choices: [
            'the exact moment the analyte is fully consumed',
            'the observable change, such as an indicator\'s color change, that signals equivalence',
            'when the buret is empty',
            'always at pH 7',
          ],
          answer: 1,
          explain: 'The endpoint is what you **observe**. The equivalence point is the true stoichiometric point. A good indicator makes them nearly the same.',
        },
        {
          id: 'c4.6-q2',
          type: 'num',
          prompt: '**10.00 mL of H₂SO₄** requires **24.00 mL of 0.150 M NaOH** to reach equivalence. What is [H₂SO₄]? [[eq: H2SO4(aq) + 2NaOH(aq) -> Na2SO4(aq) + 2H2O(l)]]',
          answer: 0.18,
          unit: 'M',
          hint: 'Use the 1 : 2 mole ratio, not MV = MV.',
          explain: 'mol NaOH = 0.150 × 0.02400 = 0.00360 mol. mol H₂SO₄ = 0.00360 ÷ 2 = 0.00180. [H₂SO₄] = 0.00180 ÷ 0.01000 L = **0.180 M**',
          compute: () => (0.15 * 0.024) / 2 / 0.01,
        },
        {
          id: 'c4.6-q3',
          type: 'mcq',
          prompt: 'A student overshoots the endpoint, adding too much titrant. The calculated concentration of the analyte will be…',
          choices: ['too high', 'too low', 'unaffected', 'zero'],
          answer: 0,
          explain: 'The recorded titrant volume is too large → too many moles assigned to the analyte → **too high**.',
        },
      ],
      flashcards: [
        { front: 'Equivalence point vs. endpoint', back: 'Equivalence: the analyte is completely consumed (stoichiometric). Endpoint: the observed signal (e.g., a color change).' },
        { front: 'Titrant vs. analyte', back: 'Titrant: known concentration, added from the buret. Analyte: the unknown being measured.' },
      ],
    },
    {
      id: 'chem-4.8',
      ced: ['4.8'],
      title: 'Acids & Bases: Proton Transfer',
      level: 'core',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'An acid–base reaction is like a game of catch where the ball is a **proton (H⁺)**. One species throws it (the acid), another catches it (the base). Water can play both positions!',
        },
        {
          kind: 'concept',
          title: 'Brønsted–Lowry definitions',
          body: '- **Acid** = proton (**H⁺**) **donor**\n- **Base** = proton **acceptor**\n\n[[eq: HCl(aq) + H2O(l) -> H3O^+(aq) + Cl^-(aq)]]\nHCl donates H⁺ (acid), and H₂O accepts it (base), forming **hydronium, H₃O⁺**.\n\n[[eq: NH3(aq) + H2O(l) <=> NH4^+(aq) + OH^-(aq)]]\nHere H₂O donates H⁺ (acid), and NH₃ accepts it (base).',
        },
        {
          kind: 'concept',
          title: 'Conjugate acid–base pairs',
          body: 'After an acid gives away H⁺, what\'s left is its **conjugate base**. After a base gains H⁺, it becomes its **conjugate acid**.\n\n**A conjugate pair differs by exactly one H⁺.**\n\nIn NH₃ + H₂O ⇌ NH₄⁺ + OH⁻:\n- NH₃ / NH₄⁺ (base / conjugate acid)\n- H₂O / OH⁻ (acid / conjugate base)',
        },
        {
          kind: 'concept',
          title: 'Water is amphoteric',
          body: 'Water can **accept** protons (becoming H₃O⁺) **or donate** them (becoming OH⁻), depending on its partner. A species that can act as either an acid or a base is called **amphoteric** (or amphiprotic).\n\nOther examples: HCO₃⁻, HSO₄⁻, H₂PO₄⁻.',
        },
        {
          kind: 'hack',
          title: 'Follow the H',
          body: 'Find the species that **lost** an H and the one that **gained** an H:\n\n- Lost H → it was the **acid**, and what\'s left is its conjugate base.\n- Gained H → it was the **base**, and the result is its conjugate acid.\n\nCount charges too: losing H⁺ makes the charge one **more negative**.',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.8-t1',
            type: 'mcq',
            prompt: 'What is the **conjugate base** of H₂PO₄⁻?',
            choices: ['H₃PO₄', 'HPO₄²⁻', 'PO₄³⁻', 'H₂PO₄²⁻'],
            answer: 1,
            hint: 'Remove one H⁺ and lower the charge by 1.',
            explain: 'H₂PO₄⁻ − H⁺ = **HPO₄²⁻**. (H₃PO₄ is its conjugate *acid*.)',
          },
        },
        {
          kind: 'trap',
          body: 'The AP exam doesn\'t test **Lewis** acid–base ideas (electron-pair donors/acceptors). Stick with Brønsted–Lowry proton transfer in water.',
        },
        {
          kind: 'summary',
          points: [
            'Acid = H⁺ donor. Base = H⁺ acceptor.',
            'Conjugate pairs differ by exactly one H⁺.',
            'Water is amphoteric: it can act as an acid or a base.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.8-q1',
          type: 'mcq',
          prompt: 'In [[eq: HF(aq) + H2O(l) <=> F^-(aq) + H3O^+(aq)]], which is a conjugate acid–base pair?',
          choices: ['HF and H₂O', 'HF and F⁻', 'F⁻ and H₃O⁺', 'H₂O and F⁻'],
          answer: 1,
          explain: '**HF and F⁻** differ by exactly one H⁺. (The other pair is H₂O / H₃O⁺.)',
        },
        {
          id: 'c4.8-q2',
          type: 'mcq',
          prompt: 'In [[eq: CO3^2-(aq) + H2O(l) <=> HCO3^-(aq) + OH^-(aq)]], water acts as…',
          choices: ['a base', 'an acid', 'a spectator', 'a catalyst'],
          answer: 1,
          explain: 'H₂O **gives** an H⁺ to CO₃²⁻ (becoming OH⁻), so here water is the **acid**.',
        },
        {
          id: 'c4.8-q3',
          type: 'mcq',
          prompt: 'Which species is **amphoteric**?',
          choices: ['Cl⁻', 'HCO₃⁻', 'Na⁺', 'NH₄⁺'],
          answer: 1,
          explain: '**HCO₃⁻** can donate H⁺ (→ CO₃²⁻) or accept H⁺ (→ H₂CO₃).',
        },
      ],
      flashcards: [
        { front: 'Brønsted–Lowry acid / base', back: 'Acid = proton donor. Base = proton acceptor.' },
        { front: 'Conjugate acid–base pair', back: 'Two species that differ by exactly one H⁺ (e.g., NH₄⁺ / NH₃).' },
        { front: 'Amphoteric', back: 'Can act as either an acid or a base (e.g., H₂O, HCO₃⁻).' },
      ],
    },
    {
      id: 'chem-4.7b',
      ced: ['4.7'],
      title: 'Oxidation Numbers & Spotting Redox',
      level: 'core',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'Batteries, rusting, photosynthesis and even your own metabolism all run on **electron transfer**. Oxidation numbers are the bookkeeping system that tracks where the electrons go.',
        },
        {
          kind: 'concept',
          title: 'Oxidation number rules',
          body: 'Apply them in order of priority:\n\n1. A free element = **0** (Fe, O₂, Cl₂)\n2. A monatomic ion = its **charge** (Na⁺ = +1, S²⁻ = −2)\n3. **F** is always **−1** in compounds\n4. **O** is usually **−2** (in peroxides like H₂O₂ it\'s −1)\n5. **H** is **+1** with nonmetals (−1 with metals, as in NaH)\n6. The sum of the oxidation numbers = the overall charge (0 for a neutral compound)',
        },
        {
          kind: 'example',
          title: 'Solve for the unknown',
          problem: 'Find the oxidation number of **Mn in MnO₄⁻**.',
          steps: ['Each O = −2, so 4 O = −8.', 'The total must equal the ion\'s charge, −1: Mn + (−8) = −1', 'Mn = **+7**'],
          answer: 'Mn is +7',
        },
        {
          kind: 'concept',
          title: 'Oxidation vs. reduction',
          body: '- **Oxidation** = **loss** of electrons → oxidation number **goes up**\n- **Reduction** = **gain** of electrons → oxidation number **goes down** (it is "reduced")\n\nElectrons flow **from** the species oxidized **to** the species reduced. One can\'t happen without the other!',
        },
        {
          kind: 'hack',
          title: 'OIL RIG 🛢️',
          body: '**O**xidation **I**s **L**oss, **R**eduction **I**s **G**ain (of electrons).\n\nOr: **LEO** the lion says **GER** (Lose Electrons = Oxidation, Gain Electrons = Reduction).',
        },
        {
          kind: 'example',
          title: 'Who\'s oxidized?',
          problem: '[[eq: Zn(s) + Cu^2+(aq) -> Zn^2+(aq) + Cu(s)]]',
          steps: [
            'Zn: 0 → +2. The oxidation number went **up**, so Zn lost 2 e⁻ → **Zn is oxidized**.',
            'Cu: +2 → 0. The oxidation number went **down**, so Cu²⁺ gained 2 e⁻ → **Cu²⁺ is reduced**.',
            'Electrons are transferred **from Zn to Cu²⁺**.',
          ],
          answer: 'Zn is oxidized and Cu²⁺ is reduced.',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.7b-t1',
            type: 'mcq',
            prompt: 'What is the oxidation number of **S in SO₄²⁻**?',
            choices: ['−2', '+4', '+6', '+8'],
            answer: 2,
            hint: '4 O = −8, and the total must be −2.',
            explain: 'S + 4(−2) = −2 → S = **+6**',
          },
        },
        {
          kind: 'trap',
          body: 'The AP exam won\'t test the terms "oxidizing agent" and "reducing agent". Focus on which species is **oxidized**, which is **reduced**, and the **direction of electron flow**.',
        },
        {
          kind: 'summary',
          points: [
            'Elements = 0. O = −2, H = +1, F = −1. The sum = the charge.',
            'Oxidation = loss of e⁻ (ox. # ↑). Reduction = gain of e⁻ (ox. # ↓). OIL RIG.',
            'Electrons go from the oxidized species to the reduced species.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.7b-q1',
          type: 'mcq',
          prompt: 'What is the oxidation number of **Cr in Cr₂O₇²⁻**?',
          choices: ['+3', '+6', '+7', '+12'],
          answer: 1,
          explain: '2Cr + 7(−2) = −2 → 2Cr = +12 → Cr = **+6**',
        },
        {
          id: 'c4.7b-q2',
          type: 'mcq',
          prompt: 'In [[eq: 2Na(s) + Cl2(g) -> 2NaCl(s)]], which species is **reduced**?',
          choices: ['Na', 'Cl₂', 'NaCl', 'Neither'],
          answer: 1,
          explain: 'Cl goes from 0 to −1 (gains electrons) → **Cl₂ is reduced**. Na goes from 0 to +1 → oxidized.',
        },
        {
          id: 'c4.7b-q3',
          type: 'mcq',
          prompt: 'Which reaction is **NOT** a redox reaction?',
          choices: [
            '[[eq: 2H2(g) + O2(g) -> 2H2O(l)]]',
            '[[eq: Fe(s) + 2H^+(aq) -> Fe^2+(aq) + H2(g)]]',
            '[[eq: AgNO3(aq) + KCl(aq) -> AgCl(s) + KNO3(aq)]]',
            '[[eq: Cu(s) + 2Ag^+(aq) -> Cu^2+(aq) + 2Ag(s)]]',
          ],
          answer: 2,
          explain: 'In the precipitation reaction, **no oxidation numbers change** (Ag stays +1, Cl stays −1, and so on). All the others involve electron transfer.',
        },
        {
          id: 'c4.7b-q4',
          type: 'mcq',
          prompt: 'What is the oxidation number of **N in NH₄⁺**?',
          choices: ['−3', '+3', '+4', '+5'],
          answer: 0,
          explain: 'N + 4(+1) = +1 → N = **−3**',
        },
      ],
      flashcards: [
        { front: 'OIL RIG', back: 'Oxidation Is Loss, Reduction Is Gain (of electrons).' },
        { front: 'Usual oxidation numbers of O, H, F', back: 'O = −2 (−1 in peroxides), H = +1 (−1 with metals), F = −1' },
        { front: 'Oxidation number goes up means…', back: '**Oxidation** (loss of electrons)' },
      ],
    },
    // ---------------- ADVANCED ----------------
    {
      id: 'chem-4.9',
      ced: ['4.9'],
      title: 'Balancing Redox with Half-Reactions',
      level: 'advanced',
      minutes: 10,
      cards: [
        {
          kind: 'hook',
          body: 'Try balancing {{MnO4^- + Fe^2+ -> Mn^2+ + Fe^3+}} by trial and error and you\'ll be at it all day. Split it into two **half-reactions** and it becomes a clean, step-by-step recipe.',
        },
        {
          kind: 'concept',
          title: 'Half-reactions',
          body: 'Write oxidation and reduction **separately**, with electrons shown:\n\nOxidation: [[eq: Zn(s) -> Zn^2+(aq) + 2e^-]]\nReduction: [[eq: Cu^2+(aq) + 2e^- -> Cu(s)]]\n\nElectrons appear as **products** in oxidation and as **reactants** in reduction. Each half-reaction must balance in atoms **and** charge.',
        },
        {
          kind: 'hack',
          title: 'Acidic solution recipe: "O-H-E"',
          body: 'For each half-reaction:\n1. Balance atoms other than O and H.\n2. **O**: add **H₂O** to the side that needs O.\n3. **H**: add **H⁺** to the side that needs H.\n4. **E**: add **e⁻** to balance the charge.\n\nThen multiply the half-reactions so the **electrons are equal**, add them, and cancel anything that appears on both sides.',
        },
        {
          kind: 'example',
          title: 'Permanganate + iron(II) in acid',
          problem: 'Balance {{MnO4^- + Fe^2+ -> Mn^2+ + Fe^3+}} in acidic solution.',
          steps: [
            'Oxidation: [[eq: Fe^2+(aq) -> Fe^3+(aq) + e^-]]',
            'Reduction: Mn is balanced. Add 4 H₂O for O, then 8 H⁺ for H, then 5 e⁻ for charge: [[eq: MnO4^-(aq) + 8H^+(aq) + 5e^- -> Mn^2+(aq) + 4H2O(l)]]',
            'Make the electrons equal: multiply the Fe half-reaction by **5**.',
            'Add them up and cancel the 5 e⁻ on each side.',
          ],
          answer: '[[eq: MnO4^-(aq) + 5Fe^2+(aq) + 8H^+(aq) -> Mn^2+(aq) + 5Fe^3+(aq) + 4H2O(l)]] (charge check: +17 on each side ✓)',
        },
        {
          kind: 'try',
          question: {
            id: 'c4.9-t1',
            type: 'mcq',
            prompt: 'To combine [[eq: Al(s) -> Al^3+(aq) + 3e^-]] and [[eq: Cu^2+(aq) + 2e^- -> Cu(s)]], you should multiply them by…',
            choices: ['1 and 1', '2 and 3', '3 and 2', '6 and 6'],
            answer: 1,
            hint: 'Find the least common multiple of 3 e⁻ and 2 e⁻.',
            explain: 'LCM of 3 and 2 is 6: Al × **2** (6 e⁻) and Cu × **3** (6 e⁻) → [[eq: 2Al(s) + 3Cu^2+(aq) -> 2Al^3+(aq) + 3Cu(s)]]',
          },
        },
        {
          kind: 'trap',
          body: 'An equation can balance in atoms but **not in charge**. [[eq: Cu(s) + 2Ag^+(aq) -> Cu^2+(aq) + 2Ag(s)]] is right, but "Cu + Ag⁺ → Cu²⁺ + Ag" has balanced atoms and unbalanced charge (+1 vs. +2). Electrons lost must equal electrons gained!',
        },
        {
          kind: 'summary',
          points: [
            'Split the reaction into oxidation and reduction half-reactions.',
            'In acid: balance the other atoms → O with H₂O → H with H⁺ → charge with e⁻.',
            'Equalize the electrons, add the halves, cancel, and check the atoms AND charge.',
          ],
        },
      ],
      check: [
        {
          id: 'c4.9-q1',
          type: 'mcq',
          prompt: 'Which half-reaction is correctly balanced?',
          choices: [
            '[[eq: Cr2O7^2-(aq) + 14H^+(aq) + 6e^- -> 2Cr^3+(aq) + 7H2O(l)]]',
            '{{Cr2O7^2- + 7H^+ + 3e^- -> 2Cr^3+ + 7H2O}}',
            '{{Cr2O7^2- + 14H^+ -> 2Cr^3+ + 7H2O}}',
            '{{Cr2O7^2- + 14H^+ + 6e^- -> Cr^3+ + 7H2O}}',
          ],
          answer: 0,
          explain: 'Atoms: 2 Cr, 7 O, 14 H on both sides. Charge: −2 + 14 − 6 = +6 on the left, 2(+3) = +6 on the right ✓',
        },
        {
          id: 'c4.9-q2',
          type: 'mcq',
          prompt: 'In a balanced redox equation, the number of electrons lost in oxidation…',
          choices: [
            'is greater than the number gained in reduction',
            'equals the number gained in reduction',
            'is always 2',
            'doesn\'t matter',
          ],
          answer: 1,
          explain: 'Electrons are transferred, not created, so **e⁻ lost = e⁻ gained**.',
        },
        {
          id: 'c4.9-q3',
          type: 'mcq',
          prompt: 'In the half-reaction [[eq: Fe(s) -> Fe^2+(aq) + 2e^-]], iron is being…',
          choices: ['reduced', 'oxidized', 'neither', 'both'],
          answer: 1,
          explain: 'Electrons appear as products (they are lost) and the oxidation number rises from 0 to +2 → **oxidized**.',
        },
      ],
      flashcards: [
        { front: 'Balancing half-reactions in acid (order)', back: 'Other atoms → O with H₂O → H with H⁺ → charge with e⁻' },
        { front: 'Where do electrons appear in an oxidation half-reaction?', back: 'On the **product** side (electrons are lost).' },
      ],
    },
  ],
  checkpoint: [
    {
      id: 'c4-cp1',
      type: 'mcq',
      prompt: 'What is the net ionic equation when solutions of **Na₂CO₃** and **CaCl₂** are mixed? (CaCO₃ is insoluble.)',
      choices: [
        '[[eq: Ca^2+(aq) + CO3^2-(aq) -> CaCO3(s)]]',
        '[[eq: 2Na^+(aq) + 2Cl^-(aq) -> 2NaCl(s)]]',
        '[[eq: Na2CO3(aq) + CaCl2(aq) -> CaCO3(s) + 2NaCl(aq)]]',
        'No reaction occurs',
      ],
      answer: 0,
      explain: 'Na⁺ and Cl⁻ are spectators (SNAP rule: NaCl is soluble). Only Ca²⁺ + CO₃²⁻ → **CaCO₃(s)**.',
    },
    {
      id: 'c4-cp2',
      type: 'num',
      prompt: '[[eq: 2C2H6(g) + 7O2(g) -> 4CO2(g) + 6H2O(g)]] How many moles of O₂ react with **0.40 mol C₂H₆**?',
      answer: 1.4,
      unit: 'mol',
      explain: '0.40 × (7/2) = **1.4 mol O₂**',
      compute: () => (0.4 * 7) / 2,
    },
    {
      id: 'c4-cp3',
      type: 'mcq',
      prompt: 'What is the oxidation number of **C in CO₂**?',
      choices: ['−4', '0', '+2', '+4'],
      answer: 3,
      explain: 'C + 2(−2) = 0 → C = **+4**',
    },
    {
      id: 'c4-cp4',
      type: 'num',
      prompt: '**30.0 mL of 0.250 M NaOH** exactly neutralizes **25.0 mL** of HNO₃. What is [HNO₃]?',
      answer: 0.3,
      unit: 'M',
      explain: 'mol NaOH = 0.250 × 0.0300 = 0.00750 = mol HNO₃. [HNO₃] = 0.00750 ÷ 0.0250 = **0.300 M**',
      compute: () => (0.25 * 0.03) / 0.025,
    },
    {
      id: 'c4-cp5',
      type: 'mcq',
      prompt: 'What is the conjugate acid of **NH₃**?',
      choices: ['NH₂⁻', 'NH₄⁺', 'N³⁻', 'H₃O⁺'],
      answer: 1,
      explain: 'Add one H⁺ to NH₃ → **NH₄⁺**.',
    },
  ],
}
