import type { Unit } from '../types'

export const unit5: Unit = {
  id: 'chem-u5',
  number: 5,
  title: 'Kinetics',
  weight: '7–9%',
  blurb: 'How fast reactions go, and why: rate laws, half-life, collisions, energy profiles, mechanisms and catalysts.',
  badge: { name: 'Speed Scientist', emoji: '⏱️' },
  lessons: [
    // ---------------- FOUNDATION ----------------
    {
      id: 'chem-5.1',
      ced: ['5.1'],
      title: 'Reaction Rates',
      level: 'foundation',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'An explosion is over in a millisecond. Rusting takes years. Same idea, atoms rearranging, but at wildly different speeds. **Kinetics** is the study of *how fast*.',
        },
        {
          kind: 'concept',
          title: 'What is a rate?',
          body: 'Reaction rate = how fast reactants are converted to products **per unit of time**, usually as a change in concentration per second (M/s).\n\nRate = −Δ[reactant]/Δt = +Δ[product]/Δt\n\nThe minus sign keeps the rate positive, because reactant concentrations go **down**.',
        },
        {
          kind: 'concept',
          title: 'Stoichiometry links the rates',
          body: 'For [[eq: 2N2O5(g) -> 4NO2(g) + O2(g)]]:\n\nNO₂ forms **twice as fast** as N₂O₅ disappears, and O₂ forms **half as fast** as N₂O₅ disappears.\n\nGeneral rule: divide each rate by its coefficient to get one single "rate of reaction":\n\nrate = −(1/2) Δ[N₂O₅]/Δt = (1/4) Δ[NO₂]/Δt = Δ[O₂]/Δt',
        },
        {
          kind: 'concept',
          title: 'What speeds reactions up?',
          body: '- 📈 **Higher concentration** (or pressure for gases) → more collisions\n- 🔥 **Higher temperature** → more collisions, and more of them energetic enough to react\n- 🧩 **More surface area** (powder vs. chunk) → more particles exposed\n- ⚗️ **A catalyst** → a lower-energy pathway\n\nYou\'ll learn the particle-level "why" for each in the coming lessons.',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.1-t1',
            type: 'num',
            prompt: 'For [[eq: N2(g) + 3H2(g) -> 2NH3(g)]], H₂ is consumed at **0.060 M/s**. At what rate is NH₃ formed?',
            answer: 0.04,
            unit: 'M/s',
            hint: 'NH₃ : H₂ = 2 : 3.',
            explain: '0.060 M/s × (2/3) = **0.040 M/s**',
            compute: () => (0.06 * 2) / 3,
          },
        },
        {
          kind: 'summary',
          points: [
            'Rate = change in concentration ÷ time.',
            'Relative rates follow the coefficients.',
            'Concentration, temperature, surface area and catalysts all affect the rate.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.1-q1',
          type: 'mcq',
          prompt: 'Why does powdered zinc react with acid **faster** than a single lump of zinc of the same mass?',
          choices: ['The powder is hotter', 'The powder has more surface area, so more collisions occur', 'The powder is a catalyst', 'The lump has less mass'],
          answer: 1,
          explain: 'More **surface area** exposes more Zn atoms to the acid, so there are more collisions per second.',
        },
        {
          id: 'c5.1-q2',
          type: 'num',
          prompt: 'For [[eq: 2N2O5(g) -> 4NO2(g) + O2(g)]], N₂O₅ is consumed at **0.010 M/s**. At what rate is **O₂** formed?',
          answer: 0.005,
          unit: 'M/s',
          explain: 'O₂ : N₂O₅ = 1 : 2, so 0.010 × ½ = **0.0050 M/s**',
          compute: () => 0.01 / 2,
        },
      ],
      flashcards: [
        { front: 'Four factors that affect reaction rate', back: 'Concentration, temperature, surface area, catalyst' },
        { front: 'How are the rates of different species in a reaction related?', back: 'By the **coefficients** in the balanced equation.' },
      ],
    },
    {
      id: 'chem-5.5',
      ced: ['5.5'],
      title: 'The Collision Model',
      level: 'foundation',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'In a gas, each molecule collides billions of times per second. If every collision made a reaction, everything would react instantly! So why don\'t they?',
        },
        {
          kind: 'concept',
          title: 'Three requirements for a successful collision',
          body: 'For an elementary reaction to happen, the particles must:\n\n1. **Collide**, so more frequent collisions → faster\n2. With **enough energy** to overcome the **activation energy (Ea)** and start breaking bonds\n3. With the **correct orientation**, so the right atoms meet\n\nIn most reactions, only a **small fraction** of collisions meets both the energy and orientation requirements.',
        },
        {
          kind: 'concept',
          title: 'Why temperature matters so much',
          body: 'The Maxwell–Boltzmann distribution shows the spread of particle energies. Only the particles in the tail past **Ea** have enough energy to react.\n\nRaising the temperature shifts the curve so a **much larger fraction** of collisions has E ≥ Ea. That\'s why a modest temperature increase can speed a reaction up dramatically.',
          diagram: 'mb-activation',
        },
        {
          kind: 'hack',
          title: '"Hit it hard, hit it right"',
          body: 'A successful collision needs **energy** (hit it hard) AND **orientation** (hit it right). On FRQs, when you explain a rate change, name which requirement changes:\n\n- Concentration ↑ → **frequency** of collisions ↑\n- Temperature ↑ → frequency ↑ AND **fraction with E ≥ Ea** ↑ (the bigger effect)\n- Catalyst → a **lower Ea**, so a bigger fraction qualifies',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.5-t1',
            type: 'mcq',
            prompt: 'Increasing the temperature increases a reaction\'s rate mainly because…',
            choices: [
              'the activation energy decreases',
              'a greater fraction of collisions have energy ≥ Ea',
              'the particles become larger',
              'the orientation of every collision improves',
            ],
            answer: 1,
            explain: 'Higher T shifts the energy distribution, so a **greater fraction** of collisions has enough energy to reach the transition state. Ea itself doesn\'t change.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Successful collisions need enough energy (≥ Ea) AND the correct orientation.',
            'Only a small fraction of collisions succeed.',
            'Higher T → a much larger fraction of collisions has E ≥ Ea.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.5-q1',
          type: 'mcq',
          prompt: 'Two molecules collide with more than enough energy, but no reaction occurs. The most likely reason is…',
          choices: ['the temperature is too high', 'incorrect orientation', 'too many collisions', 'the activation energy is zero'],
          answer: 1,
          explain: 'Energy alone isn\'t enough. The atoms that need to bond must meet, so the **orientation** must be right.',
        },
        {
          id: 'c5.5-q2',
          type: 'mcq',
          prompt: 'Increasing the concentration of a reactant increases the rate because…',
          choices: [
            'it lowers the activation energy',
            'it increases the frequency of collisions',
            'it increases the energy of each collision',
            'it changes the orientation of the molecules',
          ],
          answer: 1,
          explain: 'More particles in the same volume → **more frequent collisions** → more successful ones per second.',
        },
      ],
      flashcards: [
        { front: 'Two requirements for a collision to be successful', back: 'Energy ≥ Ea AND the correct orientation' },
        { front: 'How does temperature increase the rate (collision model)?', back: 'A greater **fraction** of collisions has energy ≥ Ea (and collisions are more frequent).' },
      ],
    },
    // ---------------- CORE ----------------
    {
      id: 'chem-5.2',
      ced: ['5.2'],
      title: 'Rate Laws & the Method of Initial Rates',
      level: 'core',
      minutes: 10,
      cards: [
        {
          kind: 'hook',
          body: 'Double a reactant\'s concentration and the reaction might go 2× faster, 4× faster, or not change at all! The **rate law** tells you which, and you can only find it by **experiment**.',
        },
        {
          kind: 'concept',
          title: 'The rate law',
          body: '**rate = k[A]^{m}[B]^{n}**\n\n- **m, n** = the **orders** with respect to A and B (usually 0, 1 or 2)\n- **overall order** = m + n\n- **k** = the **rate constant**. It depends on **temperature** (not on concentration), and its units depend on the overall order.\n\n⚠️ The orders come from **experimental data**, not from the balanced equation\'s coefficients (unless the reaction is a single elementary step).',
        },
        {
          kind: 'concept',
          title: 'What the order means',
          body: '| Order in A | Double [A] → rate… |\n| 0 | no change (×1) |\n| 1 | doubles (×2) |\n| 2 | quadruples (×4) |\n\nIn general: if [A] is multiplied by x, the rate is multiplied by x^{order}.',
        },
        {
          kind: 'example',
          title: 'Method of initial rates',
          problem: '| Exp | [A] (M) | [B] (M) | Initial rate (M/s) |\n| 1 | 0.10 | 0.10 | 2.0 × 10^{-3} |\n| 2 | 0.20 | 0.10 | 8.0 × 10^{-3} |\n| 3 | 0.10 | 0.20 | 2.0 × 10^{-3} |\n\nFind the rate law and k.',
          steps: [
            'Exp 1 → 2: [A] doubles ([B] constant), and the rate goes ×4. Since 2^{m} = 4, **m = 2**.',
            'Exp 1 → 3: [B] doubles ([A] constant), and the rate doesn\'t change. Since 2^{n} = 1, **n = 0**.',
            'Rate law: **rate = k[A]^{2}** (second order overall).',
            'k = rate/[A]^{2} = (2.0 × 10^{-3}) / (0.10)^{2} = **0.20 M^{-1}s^{-1}**',
          ],
          answer: 'rate = k[A]², k = 0.20 M⁻¹s⁻¹',
          verify: [{ stated: 0.2, compute: () => 2.0e-3 / 0.1 ** 2 }],
        },
        {
          kind: 'hack',
          title: 'Units of k from the overall order',
          body: '| Overall order | Units of k |\n| 0 | M s^{-1} |\n| 1 | s^{-1} |\n| 2 | M^{-1} s^{-1} |\n| 3 | M^{-2} s^{-1} |\n\nPattern: **M^{(1 − order)} s^{-1}**. Rate is always in M/s, so k\'s units have to make that work out.',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.2-t1',
            type: 'mcq',
            prompt: 'rate = k[X][Y]². If [Y] is **tripled** and [X] is unchanged, the rate becomes…',
            choices: ['3×', '6×', '9×', '27×'],
            answer: 2,
            hint: 'Second order in Y: multiply by 3^{2}.',
            explain: 'Order 2 in Y: 3² = **9×** faster.',
          },
        },
        {
          kind: 'summary',
          points: [
            'rate = k[A]^m[B]^n. The orders come from experiment.',
            'Compare experiments where only one concentration changes: (factor)^{order} = rate factor.',
            'k depends on temperature. Its units depend on the overall order.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.2-q1',
          type: 'mcq',
          prompt: 'For rate = k[NO]²[O₂], what is the **overall order**?',
          choices: ['1', '2', '3', '4'],
          answer: 2,
          explain: '2 (for NO) + 1 (for O₂) = **3** (third order overall).',
        },
        {
          id: 'c5.2-q2',
          type: 'mcq',
          prompt: 'A reaction has k with units of **s⁻¹**. What is its overall order?',
          choices: ['zero', 'first', 'second', 'third'],
          answer: 1,
          explain: 's⁻¹ is the unit of k for a **first-order** reaction.',
        },
        {
          id: 'c5.2-q3',
          type: 'num',
          prompt: 'rate = k[A]. When [A] = 0.40 M, the rate is 0.020 M/s. What is k?',
          answer: 0.05,
          unit: 's^{-1}',
          explain: 'k = rate/[A] = 0.020 ÷ 0.40 = **0.050 s⁻¹**',
          compute: () => 0.02 / 0.4,
        },
        {
          id: 'c5.2-q4',
          type: 'mcq',
          prompt: 'Which change alters the **value of k** for a reaction?',
          choices: ['Increasing [A]', 'Increasing the temperature', 'Adding more of reactant B', 'Using a bigger flask'],
          answer: 1,
          explain: 'The rate constant depends on **temperature** (and on adding a catalyst), not on concentrations.',
        },
      ],
      flashcards: [
        { front: 'Order = 2: what happens to the rate if [A] doubles?', back: 'It quadruples (×4)' },
        { front: 'Order = 0: what happens to the rate if [A] doubles?', back: 'No change' },
        { front: 'Can you get a rate law from the balanced overall equation?', back: '**No.** The orders must come from experiment (except for an elementary step).' },
        { front: 'Units of k for a second-order reaction', back: 'M⁻¹ s⁻¹' },
      ],
    },
    {
      id: 'chem-5.3',
      ced: ['5.3'],
      title: 'Concentration vs. Time & Half-Life',
      level: 'core',
      minutes: 10,
      cards: [
        {
          kind: 'hook',
          body: 'Archaeologists date ancient bones by measuring how much carbon-14 is left. That works because radioactive decay is **first order**, with a constant **half-life**.',
        },
        {
          kind: 'concept',
          title: 'Integrated rate laws (on your equation sheet)',
          body: '| Order | Equation | Straight-line graph | Slope |\n| 0 | [A]_{t} − [A]_{0} = −kt | [A] vs t | −k |\n| 1 | ln[A]_{t} − ln[A]_{0} = −kt | **ln[A] vs t** | −k |\n| 2 | 1/[A]_{t} − 1/[A]_{0} = kt | **1/[A] vs t** | +k |\n\nTo find the order from data: make all three graphs. **Whichever one is a straight line tells you the order.**',
          diagram: 'integrated-plots',
        },
        {
          kind: 'hack',
          title: '"Zero, Log, Flip"',
          body: 'Order **0** → plot [A] as-is\nOrder **1** → take the **log** (ln[A])\nOrder **2** → **flip** it (1/[A])\n\nThe straight line wins. And remember: the second-order slope is **positive** (1/[A] grows as [A] shrinks).',
        },
        {
          kind: 'concept',
          title: 'Half-life (first order)',
          body: 'For a first-order reaction, the half-life is **constant**: it doesn\'t depend on how much you start with.\n\n**t_{1/2} = 0.693/k**\n\nAfter 1 half-life: ½ left. After 2: ¼. After 3: ⅛. After n half-lives: (½)^{n} remains.\n\nRadioactive decay is the classic example of first-order kinetics.',
        },
        {
          kind: 'example',
          title: 'First-order calculation',
          problem: 'A first-order reaction has **k = 0.0500 s⁻¹** and [A]₀ = **0.800 M**. Find [A] after **20.0 s**, and the half-life.',
          steps: [
            'ln[A] = ln(0.800) − (0.0500)(20.0) = −0.223 − 1.000 = **−1.223**',
            '[A] = e^{-1.223} = **0.294 M**',
            't_{1/2} = 0.693 ÷ 0.0500 = **13.9 s**',
          ],
          answer: '[A] = 0.294 M after 20.0 s. t½ = 13.9 s.',
          verify: [
            { stated: -1.223, compute: () => Math.log(0.8) - 0.05 * 20 },
            { stated: 0.294, compute: () => 0.8 * Math.exp(-0.05 * 20) },
            { stated: 13.9, compute: () => 0.693 / 0.05 },
          ],
        },
        {
          kind: 'try',
          question: {
            id: 'c5.3-t1',
            type: 'num',
            prompt: 'A first-order reaction has a half-life of **10.0 min**. What fraction of the reactant remains after **30.0 min**?',
            answer: 0.125,
            hint: 'How many half-lives is 30 minutes?',
            explain: '30 ÷ 10 = 3 half-lives → (½)³ = **0.125** (⅛) remains.',
            compute: () => 0.5 ** 3,
          },
        },
        {
          kind: 'summary',
          points: [
            'Straight line: [A] vs t → 0th order. ln[A] vs t → 1st order. 1/[A] vs t → 2nd order.',
            'Slopes: −k, −k, +k.',
            'First order: t½ = 0.693/k, and the half-life is constant.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.3-q1',
          type: 'mcq',
          prompt: 'A plot of **1/[A] vs. time** is a straight line with a positive slope. The reaction is…',
          choices: ['zero order', 'first order', 'second order', 'third order'],
          answer: 2,
          explain: 'A linear 1/[A] vs t plot means **second order**, with slope = k.',
        },
        {
          id: 'c5.3-q2',
          type: 'num',
          prompt: 'A first-order reaction has **k = 0.0231 min⁻¹**. What is its half-life?',
          answer: 30.0,
          unit: 'min',
          explain: 't½ = 0.693 ÷ 0.0231 = **30.0 min**',
          compute: () => 0.693 / 0.0231,
        },
        {
          id: 'c5.3-q3',
          type: 'mcq',
          prompt: 'Carbon-14 has a half-life of about 5,730 years. Roughly what fraction of the C-14 in a sample remains after **11,460 years**?',
          choices: ['1/2', '1/4', '1/8', '0'],
          answer: 1,
          explain: '11,460 ÷ 5,730 = 2 half-lives → (½)² = **¼**.',
        },
        {
          id: 'c5.3-q4',
          type: 'mcq',
          prompt: 'The slope of a straight-line plot of ln[A] vs. time for a first-order reaction equals…',
          choices: ['k', '−k', '1/k', 't½'],
          answer: 1,
          explain: 'ln[A]_t = −kt + ln[A]₀ has the form y = mx + b, so the slope is **−k**.',
        },
      ],
      flashcards: [
        { front: 'Which plot is linear for a first-order reaction?', back: '**ln[A] vs. time** (slope = −k)' },
        { front: 'Which plot is linear for a second-order reaction?', back: '**1/[A] vs. time** (slope = +k)' },
        { front: 'First-order half-life equation', back: 't½ = 0.693 / k' },
        { front: 'Fraction remaining after n half-lives', back: '(½)ⁿ' },
      ],
    },
    {
      id: 'chem-5.4',
      ced: ['5.4'],
      title: 'Elementary Reactions',
      level: 'core',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'Most reactions happen in several small steps, like a relay race. Each individual step, a single collision or breakup, is an **elementary reaction**, and it has a special property: you *can* read its rate law straight from the equation.',
        },
        {
          kind: 'concept',
          title: 'Molecularity → rate law',
          body: 'For an **elementary step only**, the rate law comes from the number of particles colliding:\n\n| Step | Molecularity | Rate law |\n| A → products | unimolecular | rate = k[A] |\n| A + B → products | bimolecular | rate = k[A][B] |\n| 2A → products | bimolecular | rate = k[A]^{2} |\n| A + B + C → products | termolecular | rate = k[A][B][C] |\n\n**Termolecular** steps (three particles colliding at the same moment) are **rare**. That\'s about as likely as three billiard balls meeting at the exact same spot and time.',
        },
        {
          kind: 'trap',
          body: 'This shortcut ONLY works for **elementary** steps. For an overall reaction like [[eq: 2H2(g) + 2NO(g) -> N2(g) + 2H2O(g)]], you **cannot** write rate = k[H₂]²[NO]². The overall rate law must come from experiment (or from a mechanism).',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.4-t1',
            type: 'mcq',
            prompt: 'What is the rate law for the **elementary step** [[eq: NO(g) + O3(g) -> NO2(g) + O2(g)]]?',
            choices: ['rate = k[NO]', 'rate = k[NO][O₃]', 'rate = k[NO₂][O₂]', 'rate = k[NO]²[O₃]'],
            answer: 1,
            explain: 'Elementary + bimolecular (1 NO + 1 O₃) → **rate = k[NO][O₃]**.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Elementary step: rate law exponents = coefficients (molecularity).',
            'Uni- and bimolecular steps are common. Termolecular steps are rare.',
            'Never do this for an overall reaction!',
          ],
        },
      ],
      check: [
        {
          id: 'c5.4-q1',
          type: 'mcq',
          prompt: 'The elementary step [[eq: 2NO2(g) -> NO3(g) + NO(g)]] has which rate law?',
          choices: ['rate = k[NO₂]', 'rate = k[NO₂]²', 'rate = k[NO₃][NO]', 'It cannot be determined'],
          answer: 1,
          explain: 'Elementary, with 2 NO₂ colliding → **rate = k[NO₂]²**.',
        },
        {
          id: 'c5.4-q2',
          type: 'mcq',
          prompt: 'Why are termolecular elementary steps rare?',
          choices: [
            'They have no activation energy',
            'Three particles colliding at the same instant with the right energy and orientation is very unlikely',
            'They are always endothermic',
            'Molecules can\'t have three bonds',
          ],
          answer: 1,
          explain: 'A **simultaneous three-body collision** with the right energy and orientation is statistically very improbable.',
        },
      ],
      flashcards: [
        { front: 'Rate law of an elementary step', back: 'Exponents = the coefficients (molecularity) of that step.' },
        { front: 'Molecularity of A + B → products', back: 'Bimolecular, so rate = k[A][B]' },
      ],
    },
    {
      id: 'chem-5.6',
      ced: ['5.6'],
      title: 'Reaction Energy Profiles',
      level: 'core',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'Think of a reaction as hiking over a mountain pass to reach the next valley. The pass is the **transition state**, the climb is the **activation energy**, and the difference in valley heights is **ΔH**.',
        },
        {
          kind: 'concept',
          title: 'Reading an energy profile',
          body: '- **x-axis: reaction coordinate.** The progress from reactants to products, as bonds break and form.\n- **Transition state:** the highest-energy point, where old bonds are partly broken and new ones partly formed.\n- **Activation energy (Ea)** = energy(transition state) − energy(reactants)\n- **ΔH** = energy(products) − energy(reactants). Negative = exothermic. Positive = endothermic.',
          diagram: 'energy-profile',
        },
        {
          kind: 'concept',
          title: 'Forward vs. reverse',
          body: 'Ea(reverse) = energy(transition state) − energy(products)\n\nFor an exothermic reaction, the reverse reaction has a **larger** activation energy.\n\n**Arrhenius equation:** relates k to temperature and Ea. Higher T or lower Ea → larger k. (You only need this idea qualitatively. Arrhenius calculations are not on the AP exam.)',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.6-t1',
            type: 'num',
            prompt: 'Reactants are at 50 kJ, the transition state is at 130 kJ and products are at 20 kJ. What is **Ea for the forward reaction**?',
            answer: 80,
            unit: 'kJ',
            explain: 'Ea = 130 − 50 = **80 kJ**. (ΔH = 20 − 50 = −30 kJ, exothermic. Ea reverse = 130 − 20 = 110 kJ.)',
            compute: () => 130 - 50,
          },
        },
        {
          kind: 'summary',
          points: [
            'Ea = transition state − reactants.',
            'ΔH = products − reactants.',
            'Exothermic: the reverse Ea is larger than the forward Ea.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.6-q1',
          type: 'mcq',
          prompt: 'On an energy profile, the products are **higher** in energy than the reactants. The reaction is…',
          choices: ['exothermic', 'endothermic', 'catalyzed', 'zero order'],
          answer: 1,
          explain: 'Products > reactants → ΔH is positive → **endothermic**.',
        },
        {
          id: 'c5.6-q2',
          type: 'num',
          prompt: 'Using the same profile (reactants 50 kJ, transition state 130 kJ, products 20 kJ), what is **Ea for the reverse reaction**?',
          answer: 110,
          unit: 'kJ',
          explain: 'Ea(reverse) = 130 − 20 = **110 kJ**',
          compute: () => 130 - 20,
        },
      ],
      flashcards: [
        { front: 'Activation energy from an energy profile', back: 'Energy of the transition state − energy of the reactants' },
        { front: 'Transition state', back: 'The highest-energy arrangement along the reaction coordinate.' },
      ],
    },
    {
      id: 'chem-5.7',
      ced: ['5.7'],
      title: 'Reaction Mechanisms',
      level: 'core',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'A balanced equation shows the start and the finish, like a movie poster. A **mechanism** is the whole movie, scene by scene.',
        },
        {
          kind: 'concept',
          title: 'The pieces of a mechanism',
          body: 'A mechanism is a **series of elementary steps**. When you add up the steps, they must give the **overall balanced equation**.\n\n- **Intermediate:** **produced** in one step and **consumed** in a later step. It exists only while the reaction is running.\n- **Catalyst:** **consumed** in an early step and **regenerated** later. It\'s present at the start and at the end.',
        },
        {
          kind: 'example',
          title: 'Spot the intermediate',
          problem: 'Step 1: [[eq: NO2(g) + NO2(g) -> NO3(g) + NO(g)]]\nStep 2: [[eq: NO3(g) + CO(g) -> NO2(g) + CO2(g)]]\n\nFind the overall reaction and the intermediate.',
          steps: [
            'Add the steps: 2NO₂ + NO₃ + CO → NO₃ + NO + NO₂ + CO₂',
            'Cancel the species on both sides (NO₃, and one NO₂).',
            'Overall: [[eq: NO2(g) + CO(g) -> NO(g) + CO2(g)]]',
            '**NO₃** is made in step 1 and used in step 2 → it\'s the **intermediate**.',
          ],
          answer: 'Overall: NO₂ + CO → NO + CO₂. Intermediate: NO₃.',
        },
        {
          kind: 'hack',
          title: 'Intermediate vs. catalyst in one glance',
          body: '**Intermediate:** first appears on the **right** (product), later on the **left**. "Made, then used."\n**Catalyst:** first appears on the **left** (reactant), later on the **right**. "Used, then given back."\n\nNeither appears in the overall equation.',
        },
        {
          kind: 'concept',
          title: 'Evidence for a mechanism',
          body: 'Detecting an **intermediate** experimentally is strong evidence for a proposed mechanism over an alternative one. A mechanism can never be proven, only supported. It must also agree with the experimental rate law (next lesson).',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.7-t1',
            type: 'mcq',
            prompt: 'Step 1: [[eq: Cl2(g) -> 2Cl(g)]]\nStep 2: [[eq: Cl(g) + CHCl3(g) -> HCl(g) + CCl3(g)]]\nStep 3: [[eq: CCl3(g) + Cl(g) -> CCl4(g)]]\nWhich species are **intermediates**?',
            choices: ['Cl₂ and CHCl₃', 'Cl and CCl₃', 'HCl and CCl₄', 'Only Cl₂'],
            answer: 1,
            explain: '**Cl** (made in step 1, used in steps 2 and 3) and **CCl₃** (made in step 2, used in step 3) are intermediates.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Mechanism = elementary steps that add up to the overall equation.',
            'Intermediate: made, then used. Catalyst: used, then regenerated.',
            'Detecting an intermediate supports a mechanism.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.7-q1',
          type: 'mcq',
          prompt: 'Step 1: [[eq: H2O2(aq) + I^-(aq) -> H2O(l) + IO^-(aq)]]\nStep 2: [[eq: H2O2(aq) + IO^-(aq) -> H2O(l) + O2(g) + I^-(aq)]]\nWhat role does **I⁻** play?',
          choices: ['Intermediate', 'Catalyst', 'Product', 'Spectator'],
          answer: 1,
          explain: 'I⁻ is **used** in step 1 and **regenerated** in step 2 → **catalyst**. (IO⁻ is the intermediate.)',
        },
        {
          id: 'c5.7-q2',
          type: 'mcq',
          prompt: 'What is the overall reaction for the mechanism in the previous question?',
          choices: [
            '[[eq: 2H2O2(aq) -> 2H2O(l) + O2(g)]]',
            '[[eq: H2O2(aq) -> H2O(l) + O(g)]]',
            '[[eq: H2O2(aq) + I^-(aq) -> H2O(l) + IO^-(aq)]]',
            '[[eq: 2I^-(aq) -> I2(aq) + 2e^-]]',
          ],
          answer: 0,
          explain: 'Add the steps and cancel I⁻ and IO⁻: **2H₂O₂ → 2H₂O + O₂**.',
        },
      ],
      flashcards: [
        { front: 'Reaction intermediate', back: 'Produced in one step and consumed in a later step. Not in the overall equation.' },
        { front: 'Catalyst in a mechanism', back: 'Consumed in an early step and regenerated in a later step.' },
      ],
    },
    {
      id: 'chem-5.11',
      ced: ['5.11'],
      title: 'Catalysis',
      level: 'core',
      minutes: 7,
      cards: [
        {
          kind: 'hook',
          body: 'Your body runs thousands of reactions at 37 °C that would take years in a test tube. The secret is **enzymes**, nature\'s catalysts. A car\'s catalytic converter uses the same trick to clean exhaust.',
        },
        {
          kind: 'concept',
          title: 'How catalysts work',
          body: 'A catalyst speeds up a reaction by providing a **new reaction pathway (mechanism) with a lower activation energy**, and/or by increasing the number of **effective collisions**.\n\n- It is **not consumed overall**: often used in the slow step and regenerated later.\n- It does **not** change ΔH, the energies of the reactants and products.',
          diagram: 'energy-profile-catalyst',
        },
        {
          kind: 'concept',
          title: 'Three ways catalysts work',
          body: '1. **Binding/orienting:** the catalyst binds the reactants and holds them in a favorable orientation, or lowers Ea. Many **enzymes** work this way, forming a new catalyst–reactant intermediate.\n2. **Acid–base catalysis:** a reactant or intermediate **gains or loses a proton**, creating a new intermediate and new elementary steps.\n3. **Surface catalysis:** reactants **bind to a surface** (like Pt in catalytic converters), forming bound intermediates that react more easily.',
        },
        {
          kind: 'trap',
          body: 'A catalyst does **not** make a reaction more product-favored and does **not** change ΔH. It speeds up the forward and reverse reactions alike. It just provides a faster route.',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.11-t1',
            type: 'mcq',
            prompt: 'Adding a catalyst to a reaction…',
            choices: ['lowers ΔH', 'raises the energy of the products', 'provides a pathway with a lower activation energy', 'is used up as the reaction proceeds'],
            answer: 2,
            explain: 'A catalyst gives an **alternative pathway with a lower Ea**. ΔH is unchanged, and the catalyst is regenerated.',
          },
        },
        {
          kind: 'summary',
          points: [
            'A catalyst gives a new mechanism with a lower Ea. ΔH is unchanged.',
            'It is consumed and then regenerated, so its net amount is constant.',
            'Types: enzyme binding, acid–base, surface catalysis.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.11-q1',
          type: 'mcq',
          prompt: 'In surface catalysis, the reaction is sped up because…',
          choices: [
            'the surface heats the reactants',
            'reactants bind to the surface, forming intermediates with lower-energy pathways',
            'the surface is consumed',
            'the products become more stable',
          ],
          answer: 1,
          explain: 'Binding to the surface creates **new bound intermediates** and new elementary steps with a lower activation energy.',
        },
        {
          id: 'c5.11-q2',
          type: 'mcq',
          prompt: 'How does a catalyst affect the **net concentration of catalyst** over a mechanism?',
          choices: ['It decreases to zero', 'It stays constant (consumed, then regenerated)', 'It increases', 'It doubles'],
          answer: 1,
          explain: 'The catalyst is often consumed in one step but **regenerated** in a later step, so its net amount stays **constant**.',
        },
      ],
      flashcards: [
        { front: 'How does a catalyst increase the rate?', back: 'It provides a pathway with a **lower activation energy** (and/or more effective collisions).' },
        { front: 'Does a catalyst change ΔH?', back: '**No.**' },
        { front: 'Three types of catalysis', back: 'Enzyme/binding, acid–base, surface' },
      ],
    },
    // ---------------- ADVANCED ----------------
    {
      id: 'chem-5.8',
      ced: ['5.8'],
      title: 'Mechanisms & Rate Laws: The Slow Step',
      level: 'advanced',
      minutes: 8,
      cards: [
        {
          kind: 'hook',
          body: 'A team relay is only as fast as its slowest runner. In a mechanism, the **slowest elementary step (the rate-determining step)** controls the overall rate.',
        },
        {
          kind: 'concept',
          title: 'When the first step is slow',
          body: 'If the **first step is rate-limiting**, the overall rate law is simply the rate law of that **slow step**, written from its molecularity.\n\nA mechanism is consistent with experiment only if:\n1. its steps **add up** to the overall equation, AND\n2. its predicted rate law **matches** the experimental rate law.',
        },
        {
          kind: 'example',
          title: 'Check a mechanism',
          problem: 'Experiment shows **rate = k[NO₂]²** for [[eq: NO2(g) + CO(g) -> NO(g) + CO2(g)]].\nProposed: Step 1 (slow): [[eq: 2NO2(g) -> NO3(g) + NO(g)]], Step 2 (fast): [[eq: NO3(g) + CO(g) -> NO2(g) + CO2(g)]]',
          steps: [
            'Do the steps add up to the overall equation? Yes (NO₃ cancels, and one NO₂ cancels).',
            'Slow step: 2NO₂ → elementary, bimolecular → rate = k[NO₂]².',
            'Matches the experimental rate law ✓. Note that CO doesn\'t appear: it enters after the slow step.',
          ],
          answer: 'The mechanism is consistent with the data.',
        },
        {
          kind: 'hack',
          title: 'Species after the slow step don\'t count',
          body: 'Anything that first appears **after** the slow step (like CO above) has **no effect on the rate**, so it\'s **zero order**. That\'s why a reactant can be missing from a rate law!',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.8-t1',
            type: 'mcq',
            prompt: 'Step 1 (slow): [[eq: X(g) + Y(g) -> XY(g)]]. Step 2 (fast): [[eq: XY(g) + X(g) -> X2Y(g)]]. Which rate law does this mechanism predict?',
            choices: ['rate = k[X]²[Y]', 'rate = k[X][Y]', 'rate = k[XY][X]', 'rate = k[X]'],
            answer: 1,
            explain: 'The rate law comes from the **slow step** (X + Y, bimolecular): **rate = k[X][Y]**.',
          },
        },
        {
          kind: 'summary',
          points: [
            'First step slow → rate law = the slow step\'s molecularity.',
            'A valid mechanism adds up to the overall equation AND matches the experimental rate law.',
            'Species that appear only after the slow step are zero order.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.8-q1',
          type: 'mcq',
          prompt: 'The experimental rate law for [[eq: 2A(g) + B(g) -> A2B(g)]] is rate = k[A][B]. Which mechanism is consistent with it?',
          choices: [
            'Single step: [[eq: 2A(g) + B(g) -> A2B(g)]]',
            'Step 1 (slow): [[eq: A(g) + B(g) -> AB(g)]]; Step 2 (fast): [[eq: AB(g) + A(g) -> A2B(g)]]',
            'Step 1 (slow): [[eq: 2A(g) -> A2(g)]]; Step 2 (fast): [[eq: A2(g) + B(g) -> A2B(g)]]',
            'Step 1 (fast): [[eq: A(g) + B(g) -> AB(g)]]; Step 2 (slow): [[eq: AB(g) + A(g) -> A2B(g)]]',
          ],
          answer: 1,
          explain: 'The mechanism whose slow step is A + B → AB predicts **rate = k[A][B]** ✓, and its steps add up to the overall equation. The single-step mechanism predicts k[A]²[B], and a slow 2A → A₂ step predicts k[A]². When the slow step is the second one (AB + A), it involves the intermediate AB, which leads to a different rate law.',
        },
        {
          id: 'c5.8-q2',
          type: 'mcq',
          prompt: 'The rate-determining step of a mechanism is…',
          choices: ['the first step', 'the fastest step', 'the slowest step', 'the last step'],
          answer: 2,
          explain: 'The **slowest** elementary step limits the overall rate.',
        },
      ],
      flashcards: [
        { front: 'Rate-determining step', back: 'The **slowest** elementary step of a mechanism. It sets the rate law (when it\'s the first step).' },
        { front: 'Two tests a mechanism must pass', back: '1) The steps add up to the overall equation. 2) The predicted rate law matches experiment.' },
      ],
    },
    {
      id: 'chem-5.9',
      ced: ['5.9'],
      title: 'Pre-Equilibrium Approximation',
      level: 'advanced',
      minutes: 9,
      cards: [
        {
          kind: 'hook',
          body: 'What if the slow step comes **second**, and it uses an intermediate made in a fast first step? Rate laws can\'t contain intermediates, so you need one clever substitution.',
        },
        {
          kind: 'concept',
          title: 'The idea',
          body: 'If a **fast, reversible** first step comes before a slow step, the first step reaches **equilibrium** (it goes back and forth much faster than the slow step uses up its product).\n\nUse that equilibrium to express the **intermediate\'s** concentration in terms of the **reactants**, then substitute into the slow step\'s rate law.\n\nThe final rate law must contain only species from the **overall** reaction (and sometimes a catalyst), never an intermediate.',
        },
        {
          kind: 'example',
          title: '2NO + O₂ → 2NO₂',
          problem: 'Step 1 (fast, reversible): [[eq: 2NO(g) <=> N2O2(g)]]\nStep 2 (slow): [[eq: N2O2(g) + O2(g) -> 2NO2(g)]]\nDerive the rate law.',
          steps: [
            'Slow-step rate law: rate = k₂[N₂O₂][O₂]. But N₂O₂ is an intermediate, so it can\'t stay.',
            'Fast equilibrium: rate forward = rate reverse → k₁[NO]² = k₋₁[N₂O₂] → [N₂O₂] = (k₁/k₋₁)[NO]²',
            'Substitute: rate = k₂(k₁/k₋₁)[NO]²[O₂]',
            'Combine the constants into one k: **rate = k[NO]²[O₂]**',
          ],
          answer: 'rate = k[NO]²[O₂]',
        },
        {
          kind: 'hack',
          title: 'Shortcut that usually works',
          body: 'With a fast pre-equilibrium followed by a slow step, the rate law usually equals **all the reactants that went into making the slow step\'s species, counted from the start**.\n\nAbove: the slow step "needs" N₂O₂ (= 2NO) + O₂ → rate = k[NO]²[O₂].\n\nStill write out the substitution on FRQs for full credit!',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.9-t1',
            type: 'mcq',
            prompt: 'Step 1 (fast, reversible): [[eq: NO(g) + Br2(g) <=> NOBr2(g)]]\nStep 2 (slow): [[eq: NOBr2(g) + NO(g) -> 2NOBr(g)]]\nWhat rate law does this predict?',
            choices: ['rate = k[NOBr₂][NO]', 'rate = k[NO][Br₂]', 'rate = k[NO]²[Br₂]', 'rate = k[NO]²'],
            answer: 2,
            hint: 'Replace [NOBr₂] with K[NO][Br₂].',
            explain: 'rate = k₂[NOBr₂][NO] and [NOBr₂] = K[NO][Br₂] → **rate = k[NO]²[Br₂]**',
          },
        },
        {
          kind: 'summary',
          points: [
            'A fast reversible step before a slow step → treat it as being at equilibrium.',
            'Solve for the intermediate using k_forward[...] = k_reverse[...], then substitute.',
            'The final rate law has no intermediates.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.9-q1',
          type: 'mcq',
          prompt: 'Why can\'t a final rate law contain the concentration of an intermediate?',
          choices: [
            'Intermediates have no concentration',
            'Intermediates exist only briefly and can\'t be controlled or measured as starting conditions',
            'Intermediates are always catalysts',
            'Intermediates are always gases',
          ],
          answer: 1,
          explain: 'Rate laws are written in terms of species you can **set and measure** (reactants, sometimes catalysts). Intermediates are transient.',
        },
        {
          id: 'c5.9-q2',
          type: 'mcq',
          prompt: 'In a pre-equilibrium mechanism, the first step is assumed to be…',
          choices: ['slow and irreversible', 'fast and reversible, reaching equilibrium', 'the rate-determining step', 'termolecular'],
          answer: 1,
          explain: 'The pre-equilibrium approximation assumes a **fast, reversible** first step that stays at equilibrium.',
        },
      ],
      flashcards: [
        { front: 'Pre-equilibrium approximation', back: 'A fast reversible first step is at equilibrium. Use it to replace the intermediate\'s concentration in the slow step\'s rate law.' },
        { front: 'Can a final rate law contain an intermediate?', back: '**No**' },
      ],
    },
    {
      id: 'chem-5.10',
      ced: ['5.10'],
      title: 'Multistep Energy Profiles',
      level: 'advanced',
      minutes: 6,
      cards: [
        {
          kind: 'hook',
          body: 'A two-step mechanism makes a "two-hump" energy profile. Learn to read it and you can spot the intermediate and the slow step at a glance.',
        },
        {
          kind: 'concept',
          title: 'Reading the humps',
          body: '- **Each hump** = one elementary step with its own transition state.\n- **Each valley** between humps = an **intermediate**.\n- The step with the **larger activation energy** (the taller climb from the start of that step) is the **slower, rate-determining step**.\n- Overall **ΔH** = final products − original reactants (the humps don\'t matter for ΔH).',
          diagram: 'multistep-profile',
        },
        {
          kind: 'try',
          question: {
            id: 'c5.10-t1',
            type: 'mcq',
            prompt: 'A reaction energy profile has **3 humps**. How many elementary steps and how many intermediates are there?',
            choices: ['3 steps, 3 intermediates', '3 steps, 2 intermediates', '2 steps, 3 intermediates', '1 step, 2 intermediates'],
            answer: 1,
            hint: 'Count the valleys between the humps.',
            explain: '3 humps = **3 steps**. The valleys between them = **2 intermediates**.',
          },
        },
        {
          kind: 'summary',
          points: [
            'Humps = steps. Valleys between humps = intermediates.',
            'The biggest Ea climb = the rate-determining step.',
            'ΔH depends only on the start and end energies.',
          ],
        },
      ],
      check: [
        {
          id: 'c5.10-q1',
          type: 'mcq',
          prompt: 'In a two-step energy profile, step 1 has Ea = 90 kJ/mol and step 2 has Ea = 30 kJ/mol. Which step is rate-determining?',
          choices: ['Step 1', 'Step 2', 'Both equally', 'Can\'t tell'],
          answer: 0,
          explain: 'The larger activation energy → slower step → **step 1** is rate-determining.',
        },
        {
          id: 'c5.10-q2',
          type: 'mcq',
          prompt: 'The local minimum (valley) between two humps on an energy profile represents…',
          choices: ['a transition state', 'a reaction intermediate', 'the activation energy', 'the catalyst'],
          answer: 1,
          explain: 'Valleys between humps are relatively stable species that are made and then used: **intermediates**.',
        },
      ],
      flashcards: [
        { front: 'Multistep energy profile: what is a valley between humps?', back: 'A reaction **intermediate**' },
        { front: 'Multistep energy profile: which step is rate-determining?', back: 'The step with the **largest activation energy**.' },
      ],
    },
  ],
  checkpoint: [
    {
      id: 'c5-cp1',
      type: 'mcq',
      prompt: 'Experiments show that doubling [A] doubles the rate, and doubling [B] quadruples it. What is the rate law?',
      choices: ['rate = k[A][B]', 'rate = k[A]²[B]', 'rate = k[A][B]²', 'rate = k[A]²[B]²'],
      answer: 2,
      explain: 'Doubling → ×2 means first order in A. Doubling → ×4 means second order in B. **rate = k[A][B]²**',
    },
    {
      id: 'c5-cp2',
      type: 'num',
      prompt: 'A first-order reaction starts at [A]₀ = 1.00 M with k = 0.100 s⁻¹. What is [A] after **10.0 s**?',
      answer: 0.3679,
      unit: 'M',
      explain: 'ln[A] = ln(1.00) − (0.100)(10.0) = −1.00 → [A] = e^{-1.00} = **0.368 M**',
      compute: () => Math.exp(-0.1 * 10),
    },
    {
      id: 'c5-cp3',
      type: 'mcq',
      prompt: 'Which change does **NOT** increase the rate constant k?',
      choices: ['Raising the temperature', 'Adding a catalyst', 'Increasing the reactant concentration', 'All of these increase k'],
      answer: 2,
      explain: 'k depends on temperature and the pathway (catalyst), **not** on concentration. Concentration changes the rate, but not k.',
    },
    {
      id: 'c5-cp4',
      type: 'mcq',
      prompt: 'A plot of ln[A] vs. time is a straight line. Doubling [A]₀ would make the half-life…',
      choices: ['double', 'halve', 'stay the same', 'quadruple'],
      answer: 2,
      explain: 'A linear ln[A] plot → first order → the half-life (0.693/k) is **independent of concentration**.',
    },
  ],
}
